/**
 * The two axes of a `url()`: the spellings of its name, and what its parentheses hold. Kept apart from the sweeps so that a sweep about one form takes the spellings it needs rather than the product of them all.
 */

/** The spellings CSS reads as `url`, the runs that make an ordinary call, a name behind each thing that closes a scan state, a backslash-newline delimiter in front of and inside the name ([#566](https://github.com/stylelint-stylistic/stylelint-stylistic/issues/566)), and in front of a hexadecimal escape a space closes, alone and behind a word, which the value parser keeps in the word in front of the call (1789570277), and one glued to a word in front, which `postcss-value-parser` took into the name, the three signs the tokenizer glues the name to where `postcss-value-parser` parts it, which left the parentheses an address to the parser alone, a solidus behind a star, whose `*\/` `joinsTheName` read as a comment's end (1789574293), a bang glued to the name and parted from it by a space, where a write behind the bang switches how the tokenizer reads the parentheses, the solidus and the bang glued to a name a space parts from its parenthesis, behind which `postcss-scss` opens its url token all the same (1789574294), the solidus glued to a name a string, an at-word, an escape, a comma or a `//` comment parts from its parenthesis and the bang glued to one an interpolation parts, none of which pushes a word to the tokenizer that reads it, so that the name stays its last word (1789574295), a range operator likewise, and a word ending in a digit behind an escaped backslash, which opens no escape to weld the name onto ([#579](https://github.com/stylelint-stylistic/stylelint-stylistic/issues/579)), beside the one backslash that does, and a square-bracket group, whose closing bracket ends the name to every tokenizer while `postcss-value-parser` keeps it in the word in front of the call (1789894076), beside the same group with that bracket escaped, which `@csstools/css-tokenizer` reads as a character of the name, and a semicolon, the other character the value parser keeps inside a word while every tokenizer ends the name on it (1789894076), the name itself parted from its parenthesis by a space, a break and a block comment, none of which pushes a word, so the tokenizer pops the name there and takes the parentheses for an address's while `postcss-value-parser` reads a call with no name at all (1789653630), four signs between a number and the name, which end it to `@csstools/css-tokenizer` and to lightningcss while PostCSS's tokenizer glues them (1789895915), beside the four controls that leave the name where it was: a hyphen and the `#` and `@` the tokenizer reads the letters behind as a hash and an at-word, and a sign an escape covers. A closing brace closing no interpolation ends the name as a sign does, whether a number, a brace group or a template's `${…}` stands in front of it, and a brace that has ended the name once keeps a later interpolation from carrying it on, which is `@csstools/css-tokenizer`'s reading every time — it opens a url token behind all of them — while Less and dart-sass refuse every one of those texts (1789899902); the controls are a brace an escape covers, behind which the tokenizer opens no url token at all, and an interpolation inside another, which dart-sass reads as a call like the single one. A word holding a brace is read at four of the places and makes PostCSS refuse the file at the other five, where the rows stand unparsable on both sides. */
const URL_NAMES: Record<string, string> = {
	plain: `url`,
	upper: `URL`,
	escapedLetter: `u\\rl`,
	hexEscapedLetter: `\\75 rl`,
	escapedName: `\\url`,
	asciiWordInFront: `aurl`,
	nonAsciiInFront: `éurl`,
	hyphenInFront: `image-url`,
	lessInterpolationInFront: `@{p}url`,
	scssInterpolationInFront: `#{$p}url`,
	hexEscapeInFront: `\\61 url`,
	behindComma: `1,url`,
	behindSolidus: `1/url`,
	behindStarAndSolidus: `1*/url`,
	behindBang: `1!url`,
	behindBangAndSpace: `1! url`,
	spaceBeforeParenthesis: `url `,
	breakBeforeParenthesis: `url\n`,
	blockCommentBeforeParenthesis: `url/*c*/`,
	behindSolidusThenSpaceBeforeParenthesis: `1/url `,
	behindBangThenSpaceBeforeParenthesis: `1!url `,
	behindSolidusThenStringBeforeParenthesis: `1/url"x"`,
	behindSolidusThenAtWordBeforeParenthesis: `1/url@x`,
	behindSolidusThenEscapeBeforeParenthesis: `1/url\\,`,
	behindSolidusThenCommaBeforeParenthesis: `1/url,`,
	behindSolidusThenInlineCommentBeforeParenthesis: `1/url // c\n`,
	behindBangThenInterpolationBeforeParenthesis: `1!url#{a}`,
	behindRangeOperator: `1>=url`,
	behindRangeOperatorAndSpace: `1>= url`,
	behindVerticalTab: `1\vurl`,
	behindString: `"x"url`,
	behindBlockComment: `/*c*/url`,
	behindInlineComment: `//c\nurl`,
	behindAddress: `url(x)url`,
	backslashThenLineFeedInFront: `\\\nurl`,
	backslashThenWindowsPairInFront: `\\\r\nurl`,
	backslashThenCarriageReturnInFront: `\\\rurl`,
	backslashThenFormFeedInFront: `\\\furl`,
	backslashThenFormFeedInside: `u\\\frl`,
	backslashThenLineFeedBehindWord: `a\\\nurl`,
	backslashThenLineFeedInFrontOfHexEscape: `\\\n\\75 rl`,
	backslashThenLineFeedBehindWordInFrontOfHexEscape: `a\\\n\\75 rl`,
	backslashThenCarriageReturnBehindColour: `#FFF\\\rurl`,
	backslashThenFormFeedBehindDimension: `1PX\\\furl`,
	backslashThenLineFeedBehindEscapedBackslash: `\\\\\\\nurl`,
	backslashesThenLineFeedsAroundWord: `\\\na\\\n\\\nurl`,
	escapedBackslashAndDigitInFront: `x\\\\9 url`,
	escapedBackslashAndDigitThenHexEscapedLetter: `x\\\\9 \\75 rl`,
	hexEscapeAndSpaceInFront: `x\\9 url`,
	bracketGroupInFront: `[c]url`,
	bracketGroupWithEscapedCloseInFront: `[c\\]url`,
	semicolonInFront: `1;url`,
	signInFront: `1%url`,
	plusInFront: `1+url`,
	starInFront: `1*url`,
	ampersandInFront: `1&url`,
	hyphenInFrontOfNumber: `1-url`,
	hashInFront: `1#url`,
	atSignInFront: `1@url`,
	escapedSignInFront: `1\\%url`,
	closingBraceInFront: `1}url`,
	braceGroupInFront: `{p}url`,
	templateInterpolationInFront: `\${p}url`,
	interpolationThenClosingBraceInFront: `#{$p}1}url`,
	escapedClosingBraceInFront: `1\\}url`,
	closingBraceThenInterpolationInFront: `1}#{$p}url`,
	nestedInterpolationInFront: `#{#{p}}url`,
}

/** Bare, quoted, and either behind whitespace, each with characters a reader may misread; the two spellings a quotation mark and a parenthesis behind whitespace make are the divergence [#557](https://github.com/stylelint-stylistic/stylelint-stylistic/issues/557) closed, the three block comments behind whitespace the one [#660](https://github.com/stylelint-stylistic/stylelint-stylistic/issues/660) closed, and the three comments holding a parenthesis in parentheses Sass reads as code the one [#661](https://github.com/stylelint-stylistic/stylelint-stylistic/issues/661) closed, the two interpolations holding a call the reading of an address past the call's parenthesis, and the interpolation holding a comment with a quotation mark and a parenthesis what that reading has to keep of it; a parenthesis nothing closes, bare and inside a string, is what parts the writes [#533](https://github.com/stylelint-stylistic/stylelint-stylistic/issues/533) refused from the writes it kept; `bareSlashStar` and `bareBlockComment` are their control, the same delimiters with no whitespace in front of them, except under `postcss-scss`, where Sass reads `bareBlockComment`'s parentheses as code; the two strings holding the opening delimiter of a comment are what a string hides inside parentheses whose comments are read, the spaced one under every syntax and the other under `postcss-scss`; the two strings holding a parenthesis behind whitespace are where `postcss-value-parser` closed the call inside the string, `bareStringHoldingParenthesis` their control; `bareDimensionColourFraction` holds what the case, zero and colour rules write where they read no address; the escaped double slash behind a pair of parentheses stands where `postcss-scss` still holds one url token and Sass reads the escape, which the walk read as a comment, and the one behind a string is its control, which the walk goes on reading as one since a fix taking the whitespace in front of the string away turns it into a comment. */
const URL_ADDRESSES: Record<string, string> = {
	bareProtocol: `http://a/b.png`,
	bareSlashStar: `a/*b.png`,
	bareBlockComment: `a /* c */ `,
	bareParenthesis: `a(b)c.png`,
	bareQuote: `a"b.png`,
	bareOpenParenthesis: `a(b.png`,
	quotedOpenParenthesis: `"a(b.png"`,
	bareOneCharacter: `a`,
	bareDimensionColourFraction: `1.0PX,#FFF,.5`,
	quotedProtocol: `"http://a/b.png"`,
	quotedThenSlashes: `"a" // c`,
	quotedThenSlashesBroken: `"a" // c\n`,
	spacedQuotedThenSlashes: ` "a" // c `,
	spacedQuotedThenSlashesBroken: ` "a" // c\n`,
	quotedThenBlockComment: `"a" /* c */`,
	spacedQuotedThenBlockComment: ` "a" /* c */ `,
	spacedBareParenthesis: ` a(b)c.png `,
	spacedBareBlockComment: ` a /* c */ `,
	spacedBareEscapedBlockComment: ` a\\/* c */ `,
	spacedBareEscapedSlashes: ` a\\// c `,
	spacedParenthesisThenEscapedSlashes: ` a(b) \\// c `,
	spacedQuotedThenEscapedSlashes: ` "a" \\// c `,
	spacedBareBlockCommentHoldingParenthesis: ` a /* ) */ `,
	spacedBareBlockCommentFirst: ` /* c */ a.png `,
	quotedThenArgument: `"a", format("woff2")`,
	bareBlockCommentHoldingParenthesis: `a /* ) / b */ `,
	bareInlineCommentHoldingParenthesis: `a // ) , b\n`,
	variableThenBlockComment: `$a /* ) */`,
	interpolatedCallThenProtocol: `#{f(a)}//c/a.png`,
	variableThenInterpolatedCallThenSlashes: `$a #{f(b)} // c\n`,
	variableThenInterpolationHoldingComment: `$a #{c // it's )\n}`,
	spacedBareStringHoldingParenthesis: ` a ") / b , .5 1.0 #FFF 1PX f( 1 )" `,
	spacedBareStringHoldingParenthesisThenComment: ` a ")" /* ) */ b `,
	bareStringHoldingParenthesis: `a ") / b , .5 1.0 #FFF 1PX f( 1 )" `,
	spacedStringHoldingSlashStar: ` a "/*" b/c `,
	stringHoldingSlashStarThenSlashes: `a "/*" // c\n`,
	spacedBareProtocol: ` http://a/b.png `,
	spacedQuotedProtocol: ` "http://a/b.png" `,
	empty: ``,
}

export { URL_ADDRESSES, URL_NAMES }
