import { messages, ruleName } from "./index.js"

const testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`lower`],

	accept: [
		{
			code: `a { color: pink; }`,
			description: `a selector with no pseudo-element`,
		},
		{
			code: `a:before { color: pink; }`,
			description: `a lower-case pseudo-element written with one colon`,
		},
		{
			code: `a:after { color: pink; }`,
			description: `another single-colon pseudo-element`,
		},
		{
			code: `a:first-letter { color: pink; }`,
			description: `a single-colon pseudo-element of the first letter`,
		},
		{
			code: `a:first-line { color: pink; }`,
			description: `a single-colon pseudo-element of the first line`,
		},
		{
			code: `a:before, a[data-before='BEFORE'] { color: pink; }`,
			description: `an upper-case attribute value beside a pseudo-element, which is no name of one`,
		},
		{
			code: `a::before { color: pink; }`,
			description: `a lower-case pseudo-element written with two colons`,
		},
		{
			code: `a::after { color: pink; }`,
			description: `another double-colon pseudo-element`,
		},
		{
			code: `a::first-letter { color: pink; }`,
			description: `a double-colon pseudo-element of the first letter`,
		},
		{
			code: `a::first-line { color: pink; }`,
			description: `a double-colon pseudo-element of the first line`,
		},
		{
			code: `::selection { }`,
			description: `a pseudo-element standing on its own`,
		},
		{
			code: `a::spelling-error { color: pink; }`,
			description: `a pseudo-element of a spelling error`,
		},
		{
			code: `a::grammar-error { color: pink; }`,
			description: `a pseudo-element of a grammar error`,
		},
		{
			code: `li::marker { font-variant-numeric: tabular-nums; }`,
			description: `a pseudo-element of a list marker`,
		},
		{
			code: `a::some-pseudo-element { }`,
			description: `a pseudo-element no specification knows`,
		},
		{
			code: `p:first-child:before { }`,
			description: `a pseudo-class followed by a pseudo-element`,
		},
		{
			code: `h1:not(h2, h3) { }`,
			description: `a pseudo-class taking a selector list, which this rule leaves to the pseudo-class rules`,
		},
		{
			code: `h1:NOT(h2, h3) { }`,
			description: `the same pseudo-class in upper case, left alone for the same reason`,
		},
		{
			code: `a:focus { }`,
			description: `a pseudo-class`,
		},
		{
			code: `a:FOCUS { }`,
			description: `the same pseudo-class in upper case`,
		},
		{
			code: `input::-moz-placeholder { color: pink; }`,
			description: `a vendor-prefixed pseudo-element`,
		},
		{
			code: `:root { --foo: 1px; }`,
			description: `a custom property under the root selector`,
		},
		{
			code: `html { --foo: 1px; }`,
			description: `a custom property under a type selector`,
		},
		{
			code: `:root { --custom-property-set: {} }`,
			description: `a custom property set under the root selector`,
		},
		{
			code: `html { --custom-property-set: {} }`,
			description: `a custom property set under a type selector`,
		},
		{
			code: `html/*comment*/ { }`,
			description: `a comment standing behind a type selector`,
		},
	],

	reject: [
		{
			code: `a:Before { color: pink; }`,
			fixed: `a:before { color: pink; }`,
			description: `a single-colon pseudo-element opening with a capital`,
			message: messages.expected(`:Before`, `:before`),
			line: 1,
			column: 2,
		},
		{
			code: `a:bEfOrE { color: pink; }`,
			fixed: `a:before { color: pink; }`,
			description: `the same in mixed case`,
			message: messages.expected(`:bEfOrE`, `:before`),
			line: 1,
			column: 2,
		},
		{
			code: `a:BEFORE { color: pink; }`,
			fixed: `a:before { color: pink; }`,
			description: `the same in upper case`,
			message: messages.expected(`:BEFORE`, `:before`),
			line: 1,
			column: 2,
		},
		{
			code: `a:After { color: pink; }`,
			fixed: `a:after { color: pink; }`,
			description: `another single-colon pseudo-element opening with a capital`,
			message: messages.expected(`:After`, `:after`),
			line: 1,
			column: 2,
		},
		{
			code: `a:First-letter { color: pink; }`,
			fixed: `a:first-letter { color: pink; }`,
			description: `a single-colon pseudo-element of the first letter, opening with a capital`,
			message: messages.expected(`:First-letter`, `:first-letter`),
			line: 1,
			column: 2,
		},
		{
			code: `a:First-line { color: pink; }`,
			fixed: `a:first-line { color: pink; }`,
			description: `a single-colon pseudo-element of the first line, opening with a capital`,
			message: messages.expected(`:First-line`, `:first-line`),
			line: 1,
			column: 2,
		},
		{
			code: `a::Before { color: pink; }`,
			fixed: `a::before { color: pink; }`,
			description: `a double-colon pseudo-element opening with a capital`,
			message: messages.expected(`::Before`, `::before`),
			line: 1,
			column: 2,
		},
		{
			code: `a::bEfOrE { color: pink; }`,
			fixed: `a::before { color: pink; }`,
			description: `the same in mixed case`,
			message: messages.expected(`::bEfOrE`, `::before`),
			line: 1,
			column: 2,
		},
		{
			code: `a::BEFORE { color: pink; }`,
			fixed: `a::before { color: pink; }`,
			description: `the same in upper case`,
			message: messages.expected(`::BEFORE`, `::before`),
			line: 1,
			column: 2,
		},
		{
			code: `a::After { color: pink; }`,
			fixed: `a::after { color: pink; }`,
			description: `another double-colon pseudo-element opening with a capital`,
			message: messages.expected(`::After`, `::after`),
			line: 1,
			column: 2,
		},
		{
			code: `a::First-letter { color: pink; }`,
			fixed: `a::first-letter { color: pink; }`,
			description: `a double-colon pseudo-element of the first letter, opening with a capital`,
			message: messages.expected(`::First-letter`, `::first-letter`),
			line: 1,
			column: 2,
		},
		{
			code: `a::First-line { color: pink; }`,
			fixed: `a::first-line { color: pink; }`,
			description: `a double-colon pseudo-element of the first line, opening with a capital`,
			message: messages.expected(`::First-line`, `::first-line`),
			line: 1,
			column: 2,
		},
		{
			code: `::Selection { }`,
			fixed: `::selection { }`,
			description: `a pseudo-element standing on its own, opening with a capital`,
			message: messages.expected(`::Selection`, `::selection`),
			line: 1,
			column: 1,
		},
		{
			code: `::sElEcTiOn { }`,
			fixed: `::selection { }`,
			description: `the same in mixed case`,
			message: messages.expected(`::sElEcTiOn`, `::selection`),
			line: 1,
			column: 1,
		},
		{
			code: `::SELECTION { }`,
			fixed: `::selection { }`,
			description: `the same in upper case`,
			message: messages.expected(`::SELECTION`, `::selection`),
			line: 1,
			column: 1,
		},
		{
			code: `a::Spelling-error { color: pink; }`,
			fixed: `a::spelling-error { color: pink; }`,
			description: `a pseudo-element of a spelling error, opening with a capital`,
			message: messages.expected(`::Spelling-error`, `::spelling-error`),
			line: 1,
			column: 2,
		},
		{
			code: `a::Grammar-error { color: pink; }`,
			fixed: `a::grammar-error { color: pink; }`,
			description: `a pseudo-element of a grammar error, opening with a capital`,
			message: messages.expected(`::Grammar-error`, `::grammar-error`),
			line: 1,
			column: 2,
		},
		{
			code: `li::Marker { font-variant-numeric: tabular-nums; }`,
			fixed: `li::marker { font-variant-numeric: tabular-nums; }`,
			description: `a pseudo-element of a list marker, opening with a capital`,
			message: messages.expected(`::Marker`, `::marker`),
			line: 1,
			column: 3,
		},
		{
			code: `a::Some-pseudo-element { }`,
			fixed: `a::some-pseudo-element { }`,
			description: `a pseudo-element no specification knows, opening with a capital`,
			message: messages.expected(`::Some-pseudo-element`, `::some-pseudo-element`),
			line: 1,
			column: 2,
		},
		{
			code: `a::sOmE-pSeUdO-eLeMenT { }`,
			fixed: `a::some-pseudo-element { }`,
			description: `the same in mixed case`,
			message: messages.expected(`::sOmE-pSeUdO-eLeMenT`, `::some-pseudo-element`),
			line: 1,
			column: 2,
		},
		{
			code: `a::SOME-PSEUDO-ELEMENT { }`,
			fixed: `a::some-pseudo-element { }`,
			description: `the same in upper case`,
			message: messages.expected(`::SOME-PSEUDO-ELEMENT`, `::some-pseudo-element`),
			line: 1,
			column: 2,
		},
		{
			code: `p:first-child:Before { }`,
			fixed: `p:first-child:before { }`,
			description: `a single-colon pseudo-element opening with a capital, behind a pseudo-class`,
			message: messages.expected(`:Before`, `:before`),
			line: 1,
			column: 14,
		},
		{
			code: `p:First-child:Before { }`,
			fixed: `p:First-child:before { }`,
			description: `the same behind a pseudo-class that opens with a capital of its own`,
			message: messages.expected(`:Before`, `:before`),
			line: 1,
			column: 14,
		},
		{
			code: `p:first-child::Before { }`,
			fixed: `p:first-child::before { }`,
			description: `a double-colon pseudo-element opening with a capital, behind a pseudo-class`,
			message: messages.expected(`::Before`, `::before`),
			line: 1,
			column: 14,
		},
		{
			code: `p:First-child::Before { }`,
			fixed: `p:First-child::before { }`,
			description: `the same behind a pseudo-class that opens with a capital of its own`,
			message: messages.expected(`::Before`, `::before`),
			line: 1,
			column: 14,
		},
		{
			code: `input::-MOZ-PLACEHOLDER { color: pink; }`,
			fixed: `input::-moz-placeholder { color: pink; }`,
			description: `a vendor-prefixed pseudo-element in upper case`,
			message: messages.expected(`::-MOZ-PLACEHOLDER`, `::-moz-placeholder`),
			line: 1,
			column: 6,
		},
		{
			code: `a::bEfOrE/*comment*/ { color: pink; }`,
			fixed: `a::before/*comment*/ { color: pink; }`,
			description: `a pseudo-element in mixed case, with a comment behind it`,
			message: messages.expected(`::bEfOrE`, `::before`),
			line: 1,
			column: 2,
		},
	],
})

testRule({
	ruleName,
	config: [`lower`],
	customSyntax: `postcss-scss`,

	accept: [
		{
			code: `::#{$variable} {}`,
			description: `a pseudo-element built by interpolation`,
		},
		{
			code: `::#{$VARIABLE} {}`,
			description: `the same interpolation written in upper case`,
		},
		{
			code: `a::#{$variable} {}`,
			description: `the same interpolation behind a type selector`,
		},
		{
			code: `a::#{$variable}/*comment*/ {}`,
			description: `the same with a comment behind it`,
		},
	],
})

testRule({
	ruleName,
	config: [`upper`],

	accept: [
		{
			code: `a { color: pink; }`,
			description: `a selector with no pseudo-element`,
		},
		{
			code: `a:BEFORE { color: pink; }`,
			description: `an upper-case pseudo-element written with one colon`,
		},
		{
			code: `a:AFTER { color: pink; }`,
			description: `another single-colon pseudo-element`,
		},
		{
			code: `a:FIRST-LETTER { color: pink; }`,
			description: `a single-colon pseudo-element of the first letter`,
		},
		{
			code: `a:FIRST-LINE { color: pink; }`,
			description: `a single-colon pseudo-element of the first line`,
		},
		{
			code: `a:BEFORE, a[data-before='before'] { color: pink; }`,
			description: `a lower-case attribute value beside a pseudo-element, which is no name of one`,
		},
		{
			code: `a::BEFORE { color: pink; }`,
			description: `an upper-case pseudo-element written with two colons`,
		},
		{
			code: `a::AFTER { color: pink; }`,
			description: `another double-colon pseudo-element`,
		},
		{
			code: `a::FIRST-LETTER { color: pink; }`,
			description: `a double-colon pseudo-element of the first letter`,
		},
		{
			code: `a::FIRST-LINE { color: pink; }`,
			description: `a double-colon pseudo-element of the first line`,
		},
		{
			code: `::SELECTION { }`,
			description: `a pseudo-element standing on its own`,
		},
		{
			code: `a::SPELLING-ERROR { color: pink; }`,
			description: `a pseudo-element of a spelling error`,
		},
		{
			code: `a::GRAMMAR-ERROR { color: pink; }`,
			description: `a pseudo-element of a grammar error`,
		},
		{
			code: `li::MARKER { font-variant-numeric: tabular-nums; }`,
			description: `a pseudo-element of a list marker`,
		},
		{
			code: `a::SOME-PSEUDO-ELEMENT { }`,
			description: `a pseudo-element no specification knows`,
		},
		{
			code: `p:first-child:BEFORE { }`,
			description: `a pseudo-class followed by an upper-case pseudo-element`,
		},
		{
			code: `h1:not(h2, h3) { }`,
			description: `a pseudo-class taking a selector list, which this rule leaves to the pseudo-class rules`,
		},
		{
			code: `h1:NOT(h2, h3) { }`,
			description: `the same pseudo-class in upper case, left alone for the same reason`,
		},
		{
			code: `a:focus { }`,
			description: `a pseudo-class`,
		},
		{
			code: `a:FOCUS { }`,
			description: `the same pseudo-class in upper case`,
		},
		{
			code: `input::-MOZ-PLACEHOLDER { color: pink; }`,
			description: `a vendor-prefixed pseudo-element`,
		},
		{
			code: `a:FOCUS/*comment*/ { }`,
			description: `a pseudo-class with a comment behind it`,
		},
	],

	reject: [
		{
			code: `a:Before { color: pink; }`,
			fixed: `a:BEFORE { color: pink; }`,
			description: `a single-colon pseudo-element opening with a capital`,
			message: messages.expected(`:Before`, `:BEFORE`),
			line: 1,
			column: 2,
		},
		{
			code: `a:bEfOrE { color: pink; }`,
			fixed: `a:BEFORE { color: pink; }`,
			description: `the same in mixed case`,
			message: messages.expected(`:bEfOrE`, `:BEFORE`),
			line: 1,
			column: 2,
		},
		{
			code: `a:before { color: pink; }`,
			fixed: `a:BEFORE { color: pink; }`,
			description: `the same in lower case`,
			message: messages.expected(`:before`, `:BEFORE`),
			line: 1,
			column: 2,
		},
		{
			code: `a:After { color: pink; }`,
			fixed: `a:AFTER { color: pink; }`,
			description: `another single-colon pseudo-element opening with a capital`,
			message: messages.expected(`:After`, `:AFTER`),
			line: 1,
			column: 2,
		},
		{
			code: `a:First-letter { color: pink; }`,
			fixed: `a:FIRST-LETTER { color: pink; }`,
			description: `a single-colon pseudo-element of the first letter, opening with a capital`,
			message: messages.expected(`:First-letter`, `:FIRST-LETTER`),
			line: 1,
			column: 2,
		},
		{
			code: `a:First-line { color: pink; }`,
			fixed: `a:FIRST-LINE { color: pink; }`,
			description: `a single-colon pseudo-element of the first line, opening with a capital`,
			message: messages.expected(`:First-line`, `:FIRST-LINE`),
			line: 1,
			column: 2,
		},
		{
			code: `a::Before { color: pink; }`,
			fixed: `a::BEFORE { color: pink; }`,
			description: `a double-colon pseudo-element opening with a capital`,
			message: messages.expected(`::Before`, `::BEFORE`),
			line: 1,
			column: 2,
		},
		{
			code: `a::bEfOrE { color: pink; }`,
			fixed: `a::BEFORE { color: pink; }`,
			description: `the same in mixed case`,
			message: messages.expected(`::bEfOrE`, `::BEFORE`),
			line: 1,
			column: 2,
		},
		{
			code: `a::before { color: pink; }`,
			fixed: `a::BEFORE { color: pink; }`,
			description: `the same in lower case`,
			message: messages.expected(`::before`, `::BEFORE`),
			line: 1,
			column: 2,
		},
		{
			code: `a::After { color: pink; }`,
			fixed: `a::AFTER { color: pink; }`,
			description: `another double-colon pseudo-element opening with a capital`,
			message: messages.expected(`::After`, `::AFTER`),
			line: 1,
			column: 2,
		},
		{
			code: `a::First-letter { color: pink; }`,
			fixed: `a::FIRST-LETTER { color: pink; }`,
			description: `a double-colon pseudo-element of the first letter, opening with a capital`,
			message: messages.expected(`::First-letter`, `::FIRST-LETTER`),
			line: 1,
			column: 2,
		},
		{
			code: `a::First-line { color: pink; }`,
			fixed: `a::FIRST-LINE { color: pink; }`,
			description: `a double-colon pseudo-element of the first line, opening with a capital`,
			message: messages.expected(`::First-line`, `::FIRST-LINE`),
			line: 1,
			column: 2,
		},
		{
			code: `::Selection { }`,
			fixed: `::SELECTION { }`,
			description: `a pseudo-element standing on its own, opening with a capital`,
			message: messages.expected(`::Selection`, `::SELECTION`),
			line: 1,
			column: 1,
		},
		{
			code: `::sElEcTiOn { }`,
			fixed: `::SELECTION { }`,
			description: `the same in mixed case`,
			message: messages.expected(`::sElEcTiOn`, `::SELECTION`),
			line: 1,
			column: 1,
		},
		{
			code: `::selection { }`,
			fixed: `::SELECTION { }`,
			description: `the same in lower case`,
			message: messages.expected(`::selection`, `::SELECTION`),
			line: 1,
			column: 1,
		},
		{
			code: `a::Spelling-error { color: pink; }`,
			fixed: `a::SPELLING-ERROR { color: pink; }`,
			description: `a pseudo-element of a spelling error, opening with a capital`,
			message: messages.expected(`::Spelling-error`, `::SPELLING-ERROR`),
			line: 1,
			column: 2,
		},
		{
			code: `a::Grammar-error { color: pink; }`,
			fixed: `a::GRAMMAR-ERROR { color: pink; }`,
			description: `a pseudo-element of a grammar error, opening with a capital`,
			message: messages.expected(`::Grammar-error`, `::GRAMMAR-ERROR`),
			line: 1,
			column: 2,
		},
		{
			code: `li::Marker { font-variant-numeric: tabular-nums; }`,
			fixed: `li::MARKER { font-variant-numeric: tabular-nums; }`,
			description: `a pseudo-element of a list marker, opening with a capital`,
			message: messages.expected(`::Marker`, `::MARKER`),
			line: 1,
			column: 3,
		},
		{
			code: `a::Some-pseudo-element { }`,
			fixed: `a::SOME-PSEUDO-ELEMENT { }`,
			description: `a pseudo-element no specification knows, opening with a capital`,
			message: messages.expected(`::Some-pseudo-element`, `::SOME-PSEUDO-ELEMENT`),
			line: 1,
			column: 2,
		},
		{
			code: `a::sOmE-pSeUdO-eLeMenT { }`,
			fixed: `a::SOME-PSEUDO-ELEMENT { }`,
			description: `the same in mixed case`,
			message: messages.expected(`::sOmE-pSeUdO-eLeMenT`, `::SOME-PSEUDO-ELEMENT`),
			line: 1,
			column: 2,
		},
		{
			code: `a::some-pseudo-element { }`,
			fixed: `a::SOME-PSEUDO-ELEMENT { }`,
			description: `the same in lower case`,
			message: messages.expected(`::some-pseudo-element`, `::SOME-PSEUDO-ELEMENT`),
			line: 1,
			column: 2,
		},
		{
			code: `p:first-child:Before { }`,
			fixed: `p:first-child:BEFORE { }`,
			description: `a single-colon pseudo-element opening with a capital, behind a pseudo-class`,
			message: messages.expected(`:Before`, `:BEFORE`),
			line: 1,
			column: 14,
		},
		{
			code: `p:First-child:Before { }`,
			fixed: `p:First-child:BEFORE { }`,
			description: `the same behind a pseudo-class that opens with a capital of its own`,
			message: messages.expected(`:Before`, `:BEFORE`),
			line: 1,
			column: 14,
		},
		{
			code: `p:first-child::Before { }`,
			fixed: `p:first-child::BEFORE { }`,
			description: `a double-colon pseudo-element opening with a capital, behind a pseudo-class`,
			message: messages.expected(`::Before`, `::BEFORE`),
			line: 1,
			column: 14,
		},
		{
			code: `p:First-child::Before { }`,
			fixed: `p:First-child::BEFORE { }`,
			description: `the same behind a pseudo-class that opens with a capital of its own`,
			message: messages.expected(`::Before`, `::BEFORE`),
			line: 1,
			column: 14,
		},
		{
			code: `input::-moz-placeholder { color: pink; }`,
			fixed: `input::-MOZ-PLACEHOLDER { color: pink; }`,
			description: `a vendor-prefixed pseudo-element in lower case`,
			message: messages.expected(`::-moz-placeholder`, `::-MOZ-PLACEHOLDER`),
			line: 1,
			column: 6,
		},
		{
			code: `::Selection/*comment*/ { }`,
			fixed: `::SELECTION/*comment*/ { }`,
			description: `a pseudo-element opening with a capital, with a comment behind it`,
			message: messages.expected(`::Selection`, `::SELECTION`),
			line: 1,
			column: 1,
		},
	],
})

testRule({
	ruleName,
	config: [`upper`],
	customSyntax: `postcss-scss`,

	accept: [
		{
			code: `::#{$variable} {}`,
			description: `a pseudo-element built by interpolation`,
		},
		{
			code: `::#{$VARIABLE} {}`,
			description: `the same interpolation written in upper case`,
		},
		{
			code: `a::#{$variable} {}`,
			description: `the same interpolation behind a type selector`,
		},
	],
})
