import { messages, ruleName } from "./index.js"

let testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`lower`],

	accept: [
		{
			description: `an empty rule, with no declaration to measure`,
			code: `a { }`,
		},
		{
			description: `a lower-case property`,
			code: `a { display: block; }`,
		},
		{
			description: `a hyphenated lower-case property`,
			code: `a { border-radius: 8px; }`,
		},
		{
			description: `the same declaration under a pseudo-class selector`,
			code: `a:hover { display: block; }`,
		},
		{
			description: `the same declaration under another pseudo-class`,
			code: `a:focus { display: block; }`,
		},
		{
			description: `the same declaration under a pseudo-class no specification knows`,
			code: `a:other { display: block; }`,
		},
		{
			description: `the same declaration under a pseudo-element`,
			code: `a::before { display: block; }`,
		},
		{
			description: `the same declaration under a pseudo-element no specification knows`,
			code: `a::other { display: block; }`,
		},
		{
			description: `a custom property set, whose name the rule leaves alone`,
			code: `:root { --custom-property-set: {} }`,
		},
		{
			description: `a custom property in lower case`,
			code: `:root { --custom-property-name: red; }`,
		},
		{
			description: `a mixed-case custom property, whose name is the user's to spell`,
			code: `:root { --custom-PropertyName: red; }`,
		},
		{
			description: `a vendor-prefixed property in lower case`,
			code: `a { -webkit-animation-duration: 3s; }`,
		},
		{
			description: `a declaration standing directly inside a media query`,
			code: `@media screen and (orientation: landscape) { width: 500px; }`,
		},
		{
			description: `a property no specification knows, measured by its case all the same`,
			code: `a { property: value; }`,
		},
	],

	reject: [
		{
			description: `a property opening with a capital`,
			code: `a { Display: block; }`,
			fixed: `a { display: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 12,
			message: messages.expected(`Display`, `display`),
		},
		{
			description: `a property ending in a capital`,
			code: `a { DisplaY: block; }`,
			fixed: `a { display: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 12,
			message: messages.expected(`DisplaY`, `display`),
		},
		{
			description: `a property in upper case`,
			code: `a { DISPLAY: block; }`,
			fixed: `a { display: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 12,
			message: messages.expected(`DISPLAY`, `display`),
		},
		{
			description: `the second word of a hyphenated property opening with a capital`,
			code: `a { border-Radius: block; }`,
			fixed: `a { border-radius: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`border-Radius`, `border-radius`),
		},
		{
			description: `the second word of a hyphenated property in upper case`,
			code: `a { border-RADIUS: block; }`,
			fixed: `a { border-radius: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`border-RADIUS`, `border-radius`),
		},
		{
			description: `the first word of a hyphenated property in upper case`,
			code: `a { BORDER-radius: block; }`,
			fixed: `a { border-radius: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`BORDER-radius`, `border-radius`),
		},
		{
			description: `a hyphenated property in upper case`,
			code: `a { BORDER-RADIUS: block; }`,
			fixed: `a { border-radius: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`BORDER-RADIUS`, `border-radius`),
		},
		{
			description: `the vendor prefix in upper case`,
			code: `a { -WEBKIT-animation-duration: 3s; }`,
			fixed: `a { -webkit-animation-duration: 3s; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 31,
			message: messages.expected(`-WEBKIT-animation-duration`, `-webkit-animation-duration`),
		},
		{
			description: `the word after the vendor prefix opening with a capital`,
			code: `a { -webkit-Animation-duration: 3s; }`,
			fixed: `a { -webkit-animation-duration: 3s; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 31,
			message: messages.expected(`-webkit-Animation-duration`, `-webkit-animation-duration`),
		},
		{
			description: `a property opening with a capital, under a pseudo-class selector`,
			code: `a:hover { Display: block; }`,
			fixed: `a:hover { display: block; }`,
			line: 1,
			column: 11,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`Display`, `display`),
		},
		{
			description: `the same declaration under another pseudo-class`,
			code: `a:focus { Display: block; }`,
			fixed: `a:focus { display: block; }`,
			line: 1,
			column: 11,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`Display`, `display`),
		},
		{
			description: `the same declaration under a pseudo-class no specification knows`,
			code: `a:other { Display: block; }`,
			fixed: `a:other { display: block; }`,
			line: 1,
			column: 11,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`Display`, `display`),
		},
		{
			description: `the same declaration under a pseudo-element`,
			code: `a::before { Display: block; }`,
			fixed: `a::before { display: block; }`,
			line: 1,
			column: 13,
			endLine: 1,
			endColumn: 20,
			message: messages.expected(`Display`, `display`),
		},
		{
			description: `the same declaration under a pseudo-element no specification knows`,
			code: `a::other { Display: block; }`,
			fixed: `a::other { display: block; }`,
			line: 1,
			column: 12,
			endLine: 1,
			endColumn: 19,
			message: messages.expected(`Display`, `display`),
		},
		{
			description: `a property opening with a capital, directly inside a media query`,
			code: `@media screen and (orientation: landscape) { Width: 500px; }`,
			fixed: `@media screen and (orientation: landscape) { width: 500px; }`,
			line: 1,
			column: 46,
			endLine: 1,
			endColumn: 51,
			message: messages.expected(`Width`, `width`),
		},
		{
			description: `a property no specification knows, opening with a capital`,
			code: `a { Property: value; }`,
			fixed: `a { property: value; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 13,
			message: messages.expected(`Property`, `property`),
		},
	],
})

testRule({
	ruleName,
	customSyntax: `postcss-scss`,
	config: [`lower`],

	accept: [
		{
			description: `an SCSS variable, whose name is no property`,
			code: `$width: 5em;`,
		},
		{
			description: `the same variable written with a capital`,
			code: `$Width: 5em;`,
		},
		{
			description: `a key inside an SCSS map, which is no property either`,
			code: `$map: (width: 100px);`,
		},
		{
			description: `the same key written with a capital`,
			code: `$map: (Width: 100px);`,
		},
		{
			description: `a value written as a parenthesised list`,
			code: `a { font: (italic bold 10px/8px) }`,
		},
		{
			description: `a declaration under a selector referencing the parent`,
			code: `&-sidebar { border: 1px solid; }`,
		},
		{
			description: `a nested property block`,
			code: `a { font: { size: 30em; } }`,
		},
		{
			description: `a property name built by interpolation`,
			code: `p.#{$name} { #{$attr}-color: blue; }`,
		},
		{
			description: `the same name with a capital inside the interpolation`,
			code: `p.#{$name} { #{$Attr}-color: blue; }`,
		},
		{
			description: `the word after the interpolation opening with a capital`,
			code: `p.#{$name} { #{$attr}-Color: blue; }`,
		},
		{
			description: `a declaration under a placeholder selector`,
			code: `#context a%extreme { color: red; }`,
		},
		{
			description: `a declaration inside an at-root block`,
			code: `.parent { @at-root { .child1 { display: block; } } }`,
		},
		{
			description: `a declaration inside a mixin`,
			code: `@mixin large-text { font-size: 20px; }`,
		},
		{
			description: `a declaration inside a conditional at-rule`,
			code: `p { @if 1 + 1 == 2 { border: 1px solid;  } }`,
		},
	],

	reject: [
		{
			description: `a property opening with a capital, under a selector referencing the parent`,
			code: `&-sidebar { Border: 1px solid; }`,
			fixed: `&-sidebar { border: 1px solid; }`,
			line: 1,
			column: 13,
			endLine: 1,
			endColumn: 19,
			message: messages.expected(`Border`, `border`),
		},
		{
			description: `a property opening with a capital, its value a parenthesised list`,
			code: `a { Font: (italic bold 10px/8px) }`,
			fixed: `a { font: (italic bold 10px/8px) }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 9,
			message: messages.expected(`Font`, `font`),
		},
		{
			description: `a property opening with a capital inside a nested property block`,
			code: `a { font: { Size: 30em; } }`,
			fixed: `a { font: { size: 30em; } }`,
			line: 1,
			column: 13,
			endLine: 1,
			endColumn: 17,
			message: messages.expected(`Size`, `size`),
		},
		{
			description: `a property opening with a capital under a placeholder selector`,
			code: `#context a%extreme { Color: red; }`,
			fixed: `#context a%extreme { color: red; }`,
			line: 1,
			column: 22,
			endLine: 1,
			endColumn: 27,
			message: messages.expected(`Color`, `color`),
		},
		{
			description: `a property opening with a capital inside an at-root block`,
			code: `.parent { @at-root { .child1 { Display: block; } } }`,
			fixed: `.parent { @at-root { .child1 { display: block; } } }`,
			line: 1,
			column: 32,
			endLine: 1,
			endColumn: 39,
			message: messages.expected(`Display`, `display`),
		},
		{
			description: `a property opening with a capital inside a mixin`,
			code: `@mixin large-text { Font-size: 20px; }`,
			fixed: `@mixin large-text { font-size: 20px; }`,
			line: 1,
			column: 21,
			endLine: 1,
			endColumn: 30,
			message: messages.expected(`Font-size`, `font-size`),
		},
		{
			description: `a property opening with a capital inside a conditional at-rule`,
			code: `p { @if 1 + 1 == 2 { Border: 1px solid;  } }`,
			fixed: `p { @if 1 + 1 == 2 { border: 1px solid;  } }`,
			line: 1,
			column: 22,
			endLine: 1,
			endColumn: 28,
			message: messages.expected(`Border`, `border`),
		},
	],
})

testRule({
	ruleName,
	customSyntax: `postcss-less`,
	config: [`lower`],

	accept: [
		{
			description: `a Less at-variable, whose name is no property`,
			code: `@variable: 10px`,
		},
		{
			description: `the same variable written with a capital`,
			code: `@Variable: 10px`,
		},
		{
			description: `the same variable written in upper case`,
			code: `@VARIABLE: 10px`,
		},
		{
			description: `a declaration whose value is a Less variable`,
			code: `a { color: @light-blue; }`,
		},
		{
			description: `a mixin call, which is no declaration`,
			code: `a { .bordered; }`,
		},
		{
			description: `the same call written with a capital`,
			code: `a { .Bordered; }`,
		},
		{
			description: `the same call written with an argument`,
			code: `a { .Bordered(5px); }`,
		},
		{
			description: `a declaration inside a mixin definition`,
			code: `.mixin(@color: black) { color: @color; }`,
		},
		{
			description: `a declaration under a selector built by interpolation`,
			code: `.@{my-selector} { font-weight: bold; }`,
		},
		{
			description: `a property name built by interpolation`,
			code: `.widget { @{property}: #0ee; }`,
		},
		{
			description: `the same name with a capital inside the interpolation`,
			code: `.widget { @{Property}: #0ee; }`,
		},
		{
			description: `a property marked as mergeable`,
			code: `a { box-shadow+: inset 0 0 10px #555; }`,
		},
		{
			description: `a property marked as mergeable with a space`,
			code: `a { box-shadow+_: inset 0 0 10px #555; }`,
		},
		{
			description: `a declaration under a nested selector`,
			code: `.bucket { tr & { color: blue; } }`,
		},
		{
			description: `a mergeable property opening with a capital, which the rule does not measure at all`,
			code: `a { Box-shadow+: inset 0 0 10px #555; }`,
		},
		{
			description: `a mergeable-with-space property opening with a capital, left alone for the same reason`,
			code: `a { Transform+_: scale(2); }`,
		},
	],

	reject: [
		{
			description: `a property opening with a capital, its value a Less variable`,
			code: `a { Color: @light-blue; }`,
			fixed: `a { color: @light-blue; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 10,
			message: messages.expected(`Color`, `color`),
		},
		{
			description: `a property opening with a capital under a selector built by interpolation`,
			code: `.@{my-selector} { Font-weight: bold; }`,
			fixed: `.@{my-selector} { font-weight: bold; }`,
			line: 1,
			column: 19,
			endLine: 1,
			endColumn: 30,
			message: messages.expected(`Font-weight`, `font-weight`),
		},
		{
			description: `a property opening with a capital inside a mixin definition`,
			code: `.mixin(@color: black) { Color: @color; }`,
			fixed: `.mixin(@color: black) { color: @color; }`,
			line: 1,
			column: 25,
			endLine: 1,
			endColumn: 30,
			message: messages.expected(`Color`, `color`),
		},
		{
			description: `a property opening with a capital inside two nested media queries`,
			code: `@media screen { @media (min-width: 768px) { Color: red; }}`,
			fixed: `@media screen { @media (min-width: 768px) { color: red; }}`,
			line: 1,
			column: 45,
			endLine: 1,
			endColumn: 50,
			message: messages.expected(`Color`, `color`),
		},
		{
			description: `a property opening with a capital under a nested selector`,
			code: `.bucket { tr & { Color: blue; } }`,
			fixed: `.bucket { tr & { color: blue; } }`,
			line: 1,
			column: 18,
			endLine: 1,
			endColumn: 23,
			message: messages.expected(`Color`, `color`),
		},
	],
})

testRule({
	ruleName,
	config: [`upper`],

	accept: [
		{
			description: `an empty rule, with no declaration to measure`,
			code: `a { }`,
		},
		{
			description: `an upper-case property`,
			code: `a { DISPLAY: block; }`,
		},
		{
			description: `a hyphenated upper-case property`,
			code: `a { BORDER-RADIUS: 8px; }`,
		},
		{
			description: `the same declaration under a pseudo-class selector`,
			code: `a:hover { DISPLAY: block; }`,
		},
		{
			description: `the same declaration under another pseudo-class`,
			code: `a:focus { DISPLAY: block; }`,
		},
		{
			description: `the same declaration under a pseudo-class no specification knows`,
			code: `a:other { DISPLAY: block; }`,
		},
		{
			description: `the same declaration under a pseudo-element`,
			code: `a::before { DISPLAY: block; }`,
		},
		{
			description: `the same declaration under a pseudo-element no specification knows`,
			code: `a::other { DISPLAY: block; }`,
		},
		{
			description: `a custom property set, whose name the rule leaves alone`,
			code: `:root { --custom-property-set: {} }`,
		},
		{
			description: `a custom property in lower case`,
			code: `:root { --custom-property-name: red; }`,
		},
		{
			description: `a mixed-case custom property, whose name is the user's to spell`,
			code: `:root { --custom-PropertyName: red; }`,
		},
		{
			description: `a vendor-prefixed property in upper case`,
			code: `a { -WEBKIT-ANIMATION-DURATION: 3s; }`,
		},
		{
			description: `a declaration standing directly inside a media query`,
			code: `@media screen and (orientation: landscape) { WIDTH: 500px; }`,
		},
		{
			description: `a property no specification knows, measured by its case all the same`,
			code: `a { PROPERTY: value; }`,
		},
	],

	reject: [
		{
			description: `a property opening with a capital`,
			code: `a { Display: block; }`,
			fixed: `a { DISPLAY: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 12,
			message: messages.expected(`Display`, `DISPLAY`),
		},
		{
			description: `a property ending in a capital`,
			code: `a { DisplaY: block; }`,
			fixed: `a { DISPLAY: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 12,
			message: messages.expected(`DisplaY`, `DISPLAY`),
		},
		{
			description: `a property in lower case`,
			code: `a { display: block; }`,
			fixed: `a { DISPLAY: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 12,
			message: messages.expected(`display`, `DISPLAY`),
		},
		{
			description: `the second word of a hyphenated property opening with a capital`,
			code: `a { border-Radius: block; }`,
			fixed: `a { BORDER-RADIUS: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`border-Radius`, `BORDER-RADIUS`),
		},
		{
			description: `the first word of a hyphenated property in lower case`,
			code: `a { border-RADIUS: block; }`,
			fixed: `a { BORDER-RADIUS: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`border-RADIUS`, `BORDER-RADIUS`),
		},
		{
			description: `the second word of a hyphenated property in lower case`,
			code: `a { BORDER-radius: block; }`,
			fixed: `a { BORDER-RADIUS: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`BORDER-radius`, `BORDER-RADIUS`),
		},
		{
			description: `a hyphenated property in lower case`,
			code: `a { border-radius: block; }`,
			fixed: `a { BORDER-RADIUS: block; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`border-radius`, `BORDER-RADIUS`),
		},
		{
			description: `the words after the vendor prefix in lower case`,
			code: `a { -WEBKIT-animation-duration: 3s; }`,
			fixed: `a { -WEBKIT-ANIMATION-DURATION: 3s; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 31,
			message: messages.expected(`-WEBKIT-animation-duration`, `-WEBKIT-ANIMATION-DURATION`),
		},
		{
			description: `a vendor-prefixed property in lower case but for one capital`,
			code: `a { -webkit-Animation-duration: 3s; }`,
			fixed: `a { -WEBKIT-ANIMATION-DURATION: 3s; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 31,
			message: messages.expected(`-webkit-Animation-duration`, `-WEBKIT-ANIMATION-DURATION`),
		},
		{
			description: `a property opening with a capital, under a pseudo-class selector`,
			code: `a:hover { Display: block; }`,
			fixed: `a:hover { DISPLAY: block; }`,
			line: 1,
			column: 11,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`Display`, `DISPLAY`),
		},
		{
			description: `the same declaration under another pseudo-class`,
			code: `a:focus { Display: block; }`,
			fixed: `a:focus { DISPLAY: block; }`,
			line: 1,
			column: 11,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`Display`, `DISPLAY`),
		},
		{
			description: `the same declaration under a pseudo-class no specification knows`,
			code: `a:other { Display: block; }`,
			fixed: `a:other { DISPLAY: block; }`,
			line: 1,
			column: 11,
			endLine: 1,
			endColumn: 18,
			message: messages.expected(`Display`, `DISPLAY`),
		},
		{
			description: `the same declaration under a pseudo-element`,
			code: `a::before { Display: block; }`,
			fixed: `a::before { DISPLAY: block; }`,
			line: 1,
			column: 13,
			endLine: 1,
			endColumn: 20,
			message: messages.expected(`Display`, `DISPLAY`),
		},
		{
			description: `the same declaration under a pseudo-element no specification knows`,
			code: `a::other { Display: block; }`,
			fixed: `a::other { DISPLAY: block; }`,
			line: 1,
			column: 12,
			endLine: 1,
			endColumn: 19,
			message: messages.expected(`Display`, `DISPLAY`),
		},
		{
			description: `a property opening with a capital, directly inside a media query`,
			code: `@media screen and (orientation: landscape) { Width: 500px; }`,
			fixed: `@media screen and (orientation: landscape) { WIDTH: 500px; }`,
			line: 1,
			column: 46,
			endLine: 1,
			endColumn: 51,
			message: messages.expected(`Width`, `WIDTH`),
		},
		{
			description: `a property no specification knows, opening with a capital`,
			code: `a { Property: value; }`,
			fixed: `a { PROPERTY: value; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 13,
			message: messages.expected(`Property`, `PROPERTY`),
		},
	],
})

testRule({
	ruleName,
	customSyntax: `postcss-scss`,
	config: [`upper`],

	accept: [
		{
			description: `an SCSS variable, whose name is no property`,
			code: `$width: 5em;`,
		},
		{
			description: `the same variable written with a capital`,
			code: `$Width: 5em;`,
		},
		{
			description: `a key inside an SCSS map, which is no property either`,
			code: `$map: (width: 100px);`,
		},
		{
			description: `the same key written with a capital`,
			code: `$map: (Width: 100px);`,
		},
		{
			description: `a value written as a parenthesised list`,
			code: `a { FONT: (italic bold 10px/8px) }`,
		},
		{
			description: `a declaration under a selector referencing the parent`,
			code: `&-sidebar { BORDER: 1px solid; }`,
		},
		{
			description: `a nested property block`,
			code: `a { font: { SIZE: 30em; } }`,
		},
		{
			description: `a property name built by interpolation`,
			code: `p.#{$name} { #{$attr}-color: blue; }`,
		},
		{
			description: `the same name with a capital inside the interpolation`,
			code: `p.#{$name} { #{$Attr}-color: blue; }`,
		},
		{
			description: `the word after the interpolation opening with a capital`,
			code: `p.#{$name} { #{$attr}-Color: blue; }`,
		},
		{
			description: `a declaration under a placeholder selector`,
			code: `#context a%extreme { COLOR: red; }`,
		},
		{
			description: `a declaration inside an at-root block`,
			code: `.parent { @at-root { .child1 { DISPLAY: block; } } }`,
		},
		{
			description: `a declaration inside a mixin`,
			code: `@mixin large-text { FONT-SIZE: 20px; }`,
		},
		{
			description: `a declaration inside a conditional at-rule`,
			code: `p { @if 1 + 1 == 2 { BORDER: 1px solid;  } }`,
		},
	],

	reject: [
		{
			description: `a property opening with a capital, under a selector referencing the parent`,
			code: `&-sidebar { Border: 1px solid; }`,
			fixed: `&-sidebar { BORDER: 1px solid; }`,
			line: 1,
			column: 13,
			endLine: 1,
			endColumn: 19,
			message: messages.expected(`Border`, `BORDER`),
		},
		{
			description: `a property opening with a capital, its value a parenthesised list`,
			code: `a { Font: (italic bold 10px/8px) }`,
			fixed: `a { FONT: (italic bold 10px/8px) }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 9,
			message: messages.expected(`Font`, `FONT`),
		},
		{
			description: `a property opening with a capital inside a nested property block`,
			code: `a { font: { Size: 30em; } }`,
			fixed: `a { font: { SIZE: 30em; } }`,
			line: 1,
			column: 13,
			endLine: 1,
			endColumn: 17,
			message: messages.expected(`Size`, `SIZE`),
		},
		{
			description: `a property opening with a capital under a placeholder selector`,
			code: `#context a%extreme { Color: red; }`,
			fixed: `#context a%extreme { COLOR: red; }`,
			line: 1,
			column: 22,
			endLine: 1,
			endColumn: 27,
			message: messages.expected(`Color`, `COLOR`),
		},
		{
			description: `a property opening with a capital inside an at-root block`,
			code: `.parent { @at-root { .child1 { Display: block; } } }`,
			fixed: `.parent { @at-root { .child1 { DISPLAY: block; } } }`,
			line: 1,
			column: 32,
			endLine: 1,
			endColumn: 39,
			message: messages.expected(`Display`, `DISPLAY`),
		},
		{
			description: `a property opening with a capital inside a mixin`,
			code: `@mixin large-text { Font-size: 20px; }`,
			fixed: `@mixin large-text { FONT-SIZE: 20px; }`,
			line: 1,
			column: 21,
			endLine: 1,
			endColumn: 30,
			message: messages.expected(`Font-size`, `FONT-SIZE`),
		},
		{
			description: `a property opening with a capital inside a conditional at-rule`,
			code: `p { @if 1 + 1 == 2 { Border: 1px solid;  } }`,
			fixed: `p { @if 1 + 1 == 2 { BORDER: 1px solid;  } }`,
			line: 1,
			column: 22,
			endLine: 1,
			endColumn: 28,
			message: messages.expected(`Border`, `BORDER`),
		},
	],
})

testRule({
	ruleName,
	customSyntax: `postcss-less`,
	config: [`upper`],

	accept: [
		{
			description: `a Less at-variable, whose name is no property`,
			code: `@variable: 10px`,
		},
		{
			description: `the same variable written with a capital`,
			code: `@Variable: 10px`,
		},
		{
			description: `the same variable written in upper case`,
			code: `@VARIABLE: 10px`,
		},
		{
			description: `a declaration whose value is a Less variable`,
			code: `a { COLOR: @light-blue; }`,
		},
		{
			description: `a mixin call, which is no declaration`,
			code: `a { .bordered; }`,
		},
		{
			description: `the same call written with a capital`,
			code: `a { .Bordered; }`,
		},
		{
			description: `the same call written with an argument`,
			code: `a { .Bordered(5px); }`,
		},
		{
			description: `a declaration inside a mixin definition`,
			code: `.mixin(@color: black) { COLOR: @color; }`,
		},
		{
			description: `a declaration under a selector built by interpolation`,
			code: `.@{my-selector} { FONT-WEIGHT: bold; }`,
		},
		{
			description: `a property name built by interpolation`,
			code: `.widget { @{property}: #0ee; }`,
		},
		{
			description: `the same name with a capital inside the interpolation`,
			code: `.widget { @{Property}: #0ee; }`,
		},
		{
			description: `a property marked as mergeable`,
			code: `a { BOX_SHADOW+: inset 0 0 10px #555; }`,
		},
		{
			description: `a property marked as mergeable with a space`,
			code: `a { BOX-SHADOW+_: inset 0 0 10px #555; }`,
		},
		{
			description: `a declaration under a nested selector`,
			code: `.bucket { tr & { COLOR: blue; } }`,
		},
		{
			description: `a mergeable property opening with a capital, which the rule does not measure at all`,
			code: `a { Box-shadow+: inset 0 0 10px #555; }`,
		},
		{
			description: `a mergeable-with-space property opening with a capital, left alone for the same reason`,
			code: `a { Transform+_: scale(2); }`,
		},
	],

	reject: [
		{
			description: `a property opening with a capital, its value a Less variable`,
			code: `a { Color: @light-blue; }`,
			fixed: `a { COLOR: @light-blue; }`,
			line: 1,
			column: 5,
			endLine: 1,
			endColumn: 10,
			message: messages.expected(`Color`, `COLOR`),
		},
		{
			description: `a property opening with a capital under a selector built by interpolation`,
			code: `.@{my-selector} { Font-weight: bold; }`,
			fixed: `.@{my-selector} { FONT-WEIGHT: bold; }`,
			line: 1,
			column: 19,
			endLine: 1,
			endColumn: 30,
			message: messages.expected(`Font-weight`, `FONT-WEIGHT`),
		},
		{
			description: `a property opening with a capital inside a mixin definition`,
			code: `.mixin(@color: black) { Color: @color; }`,
			fixed: `.mixin(@color: black) { COLOR: @color; }`,
			line: 1,
			column: 25,
			endLine: 1,
			endColumn: 30,
			message: messages.expected(`Color`, `COLOR`),
		},
		{
			description: `a property opening with a capital inside two nested media queries`,
			code: `@media screen { @media (min-width: 768px) { Color: red; }}`,
			fixed: `@media screen { @media (min-width: 768px) { COLOR: red; }}`,
			line: 1,
			column: 45,
			endLine: 1,
			endColumn: 50,
			message: messages.expected(`Color`, `COLOR`),
		},
		{
			description: `a property opening with a capital under a nested selector`,
			code: `.bucket { tr & { Color: blue; } }`,
			fixed: `.bucket { tr & { COLOR: blue; } }`,
			line: 1,
			column: 18,
			endLine: 1,
			endColumn: 23,
			message: messages.expected(`Color`, `COLOR`),
		},
	],
})

testRule({
	ruleName,
	config: [`lower`, { ignoreSelectors: [`:exports`] }],

	accept: [
		{
			description: `a camel-cased property under a selector the ignoreSelectors option names`,
			code: `:exports { camelCasedColorVariable: blue  }`,
		},
	],
})
