import { messages, ruleName } from "./index.js"

const testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`lower`],

	accept: [
		{
			code: `a { line-height: 1; }`,
			description: `a unitless number`,
		},
		{
			code: `a { color: #000; }`,
			description: `a hex colour, whose digits carry no unit`,
		},
		{
			code: `a { font-size: 100%; }`,
			description: `a percentage`,
		},
		{
			code: `a { font-size: .5rem; }`,
			description: `a unit after a fraction with no leading zero`,
		},
		{
			code: `a { font-size: 0.5rem; }`,
			description: `a unit after a fraction with a leading zero`,
		},
		{
			code: `a { width: 10px; }`,
			description: `a lower-case unit`,
		},
		{
			code: `a { margin: 0 10em 5rem 2in; }`,
			description: `a run of values with lower-case units`,
		},
		{
			code: `a { background-position: top right, 1em 5vh; }`,
			description: `a keyword pair and a pair of units in one value`,
		},
		{
			code: `a { top: calc(10em - 3em); }`,
			description: `units inside a calc expression`,
		},
		{
			code: `a { top: calc(10px*2rem); }`,
			description: `units on either side of a multiplication inside calc`,
		},
		{
			code: `a { background-image: linear-gradient(to right, white calc(100% - 50em), silver); }`,
			description: `a unit inside a calc expression nested in a gradient`,
		},
		{
			code: `a { transform: rotate(90deg); }`,
			description: `a unit inside the arguments of a function`,
		},
		{
			code: `a { color: green; }`,
			description: `a keyword, which carries no unit`,
		},
		{
			code: `a { color: green10PX; }`,
			description: `a keyword that ends in what looks like a unit`,
		},
		{
			code: `a { width: /* 100PX */ 1em; }`,
			description: `a unit inside a comment, which the rule does not read`,
		},
		{
			code: `a::before { content: "10PX"}`,
			description: `a unit inside a string`,
		},
		{
			code: `a { font-size: $fs10PX; }`,
			description: `a unit inside the name of an SCSS variable`,
		},
		{
			code: `a { font-size: @fs10PX; }`,
			description: `a unit inside the name of a Less variable`,
		},
		{
			code: `a { font-size: var(--some-fs-10PX); }`,
			description: `a unit inside the name of a custom property`,
		},
		{
			code: `a { margin: url(13PX); }`,
			description: `a unit inside the address of a url call`,
		},
		{
			code: `a { margin: uRl(13PX); }`,
			description: `the same call written in mixed case`,
		},
		{
			code: `a { margin: URL(13PX); }`,
			description: `the same call written in upper case`,
		},
		{
			code: `a { marginPX: 10px; }`,
			description: `a unit inside a property name`,
		},
		{
			code: `a10PX { margin: 10px; }`,
			description: `a unit inside a type selector`,
		},
		{
			code: `#a10PX { margin: 10px; }`,
			description: `a unit inside an id selector`,
		},
		{
			code: `.a10PX { margin: 10px; }`,
			description: `a unit inside a class selector`,
		},
		{
			code: `input[type=10PX] { margin: 10px; }`,
			description: `a unit inside the value of an attribute selector`,
		},
		{
			code: `a:hover10PX { margin: 10px; }`,
			description: `a unit inside a pseudo-class`,
		},
		{
			code: `a::before10PX { margin: 10px; }`,
			description: `a unit inside a pseudo-element`,
		},
		{
			code: `a { margin: 13xpx; }`,
			description: `a unit no specification knows, written in lower case`,
		},
		{
			code: `@media (min-width: 10px) {}`,
			description: `a unit inside a media feature`,
		},
		{
			code: `@media (min-width: 10px)\n  and (max-width: 20px) {}`,
			description: `a unit inside each of two media features`,
		},
		{
			code: `@media not screen and (min-width: 100px) {}`,
			description: `a unit inside a negated media query`,
		},
		{
			code: `@import 'foo.css'`,
			description: `an at-rule that is neither a media query nor a variable`,
		},
	],

	reject: [
		{
			code: `a { width: 10pX; }`,
			fixed: `a { width: 10px; }`,
			description: `a unit ending in a capital`,
			message: messages.expected(`pX`, `px`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
		{
			code: `a { width: 10Px; }`,
			fixed: `a { width: 10px; }`,
			description: `a unit opening with a capital`,
			message: messages.expected(`Px`, `px`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
		{
			code: `a { width: 10PX; }`,
			fixed: `a { width: 10px; }`,
			description: `a unit in upper case`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
		{
			code: `a { margin: 10px 10PX; }`,
			fixed: `a { margin: 10px 10px; }`,
			description: `the second of two units in upper case`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 20,
			endLine: 1,
			endColumn: 22,
		},
		{
			code: `a { font-size: .5REM; }`,
			fixed: `a { font-size: .5rem; }`,
			description: `an upper-case unit after a fraction with no leading zero`,
			message: messages.expected(`REM`, `rem`),
			line: 1,
			column: 18,
			endLine: 1,
			endColumn: 21,
		},
		{
			code: `a { font-size: 0.5REM; }`,
			fixed: `a { font-size: 0.5rem; }`,
			description: `an upper-case unit after a fraction with a leading zero`,
			message: messages.expected(`REM`, `rem`),
			line: 1,
			column: 19,
			endLine: 1,
			endColumn: 22,
		},
		{
			code: `a { margin: calc(10px + 10PX); }`,
			fixed: `a { margin: calc(10px + 10px); }`,
			description: `an upper-case unit inside a calc expression`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 27,
			endLine: 1,
			endColumn: 29,
		},
		{
			code: `a { top: calc(10px*2REM); }`,
			fixed: `a { top: calc(10px*2rem); }`,
			description: `an upper-case unit after a multiplication inside calc`,
			message: messages.expected(`REM`, `rem`),
			line: 1,
			column: 21,
			endLine: 1,
			endColumn: 24,
		},
		{
			code: `a { margin: -webkit-calc(13PX + 10px); }`,
			fixed: `a { margin: -webkit-calc(13px + 10px); }`,
			description: `an upper-case unit inside a vendor-prefixed calc expression`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 28,
			endLine: 1,
			endColumn: 30,
		},
		{
			code: `a { margin: some-function(13PX + 10px); }`,
			fixed: `a { margin: some-function(13px + 10px); }`,
			description: `an upper-case unit inside the arguments of a function no specification knows`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 29,
			endLine: 1,
			endColumn: 31,
		},
		{
			code: `root { --margin: 10PX; }`,
			fixed: `root { --margin: 10px; }`,
			description: `an upper-case unit in the value of a custom property`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 20,
			endLine: 1,
			endColumn: 22,
		},
		{
			code: `root { --margin: 10px + 10PX; }`,
			fixed: `root { --margin: 10px + 10px; }`,
			description: `an upper-case unit in a sum inside a custom property`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 27,
			endLine: 1,
			endColumn: 29,
		},
		{
			code: `a { margin: 13XPX; }`,
			fixed: `a { margin: 13xpx; }`,
			message: messages.expected(`XPX`, `xpx`),
			description: `a unit no specification knows, written in upper case`,
			line: 1,
			column: 15,
			endLine: 1,
			endColumn: 18,
		},
		{
			code: `@media (min-width: 13PX) {}`,
			fixed: `@media (min-width: 13px) {}`,
			message: messages.expected(`PX`, `px`),
			description: `an upper-case unit inside a media feature`,
			line: 1,
			column: 22,
			endLine: 1,
			endColumn: 24,
		},
		{
			code: `@MEDIA (min-width: 13PX) {}`,
			fixed: `@MEDIA (min-width: 13px) {}`,
			message: messages.expected(`PX`, `px`),
			description: `the same query under an upper-case at-rule name`,
			line: 1,
			column: 22,
			endLine: 1,
			endColumn: 24,
		},
		{
			code: `@Media (min-width: 13PX) {}`,
			fixed: `@Media (min-width: 13px) {}`,
			message: messages.expected(`PX`, `px`),
			description: `the same query under a mixed-case at-rule name`,
			line: 1,
			column: 22,
			endLine: 1,
			endColumn: 24,
		},
		{
			code: `@media (min-width: 10px)\n  and (max-width: 20PX) {}`,
			fixed: `@media (min-width: 10px)\n  and (max-width: 20px) {}`,
			message: messages.expected(`PX`, `px`),
			description: `an upper-case unit in the second of two media features`,
			line: 2,
			column: 21,
			endLine: 2,
			endColumn: 23,
		},
		{
			code: `@media (width < 10.01REM) {}`,
			fixed: `@media (width < 10.01rem) {}`,
			message: messages.expected(`REM`, `rem`),
			description: `an upper-case unit inside a media feature written in range syntax`,
			line: 1,
			column: 22,
			endLine: 1,
			endColumn: 25,
		},
		{
			code: `@media not screen and (min-width: 100PX) {}`,
			fixed: `@media not screen and (min-width: 100px) {}`,
			message: messages.expected(`PX`, `px`),
			description: `an upper-case unit inside a negated media query`,
			line: 1,
			column: 38,
			endLine: 1,
			endColumn: 40,
		},
		{
			code: `@media not screen and (min-width: 100PX) { width: 100Px; }`,
			fixed: `@media not screen and (min-width: 100px) { width: 100px; }`,
			description: `an upper-case unit in a negated media query and another in its block`,
			warnings: [
				{
					message: messages.expected(`PX`, `px`),
					line: 1,
					column: 38,
					endLine: 1,
					endColumn: 40,
				},
				{
					message: messages.expected(`Px`, `px`),
					line: 1,
					column: 54,
					endLine: 1,
					endColumn: 56,
				},
			],
		},
		{
			code: `a { background: url("10PX.png") 10PX 20px no-repeat; }`,
			fixed: `a { background: url("10PX.png") 10px 20px no-repeat; }`,
			description: `an upper-case unit inside a url address and another beside it in the value`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 35,
			endLine: 1,
			endColumn: 37,
		},
	],
})

testRule({
	ruleName,
	customSyntax: `postcss-scss`,
	config: [`lower`],

	accept: [
		{
			code: `a { width: 1em; \n// width: 10PX\n }`,
			description: `a unit inside an end-of-line comment, which the rule does not read`,
		},
		{
			code: `a { margin: calc(100% - #{$margin * 2}); }`,
			description: `an interpolation inside a calc expression, which carries no unit of its own`,
		},
	],

	reject: [
		{
			code: `a { margin: 10PX; }`,
			fixed: `a { margin: 10px; }`,
			description: `an upper-case unit`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 15,
			endLine: 1,
			endColumn: 17,
		},
		{
			code: `a { margin: 10pX; }`,
			fixed: `a { margin: 10px; }`,
			description: `a unit ending in a capital`,
			message: messages.expected(`pX`, `px`),
			line: 1,
			column: 15,
			endLine: 1,
			endColumn: 17,
		},
		{
			code: `a { margin: 10Px; }`,
			fixed: `a { margin: 10px; }`,
			description: `a unit opening with a capital`,
			message: messages.expected(`Px`, `px`),
			line: 1,
			column: 15,
			endLine: 1,
			endColumn: 17,
		},
		{
			code: `a { margin: 10PX + 10px; }`,
			fixed: `a { margin: 10px + 10px; }`,
			description: `an upper-case unit in a sum`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 15,
			endLine: 1,
			endColumn: 17,
		},
		{
			code: `a { $margin: 10PX; }`,
			fixed: `a { $margin: 10px; }`,
			description: `an upper-case unit in the value of an SCSS variable`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 16,
			endLine: 1,
			endColumn: 18,
		},
		{
			code: `a { $margin: 10px + 10PX; }`,
			fixed: `a { $margin: 10px + 10px; }`,
			description: `an upper-case unit in a sum inside an SCSS variable`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 23,
			endLine: 1,
			endColumn: 25,
		},
		{
			code: `a { margin: $margin + 10PX; }`,
			fixed: `a { margin: $margin + 10px; }`,
			description: `an upper-case unit added to an SCSS variable`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 25,
			endLine: 1,
			endColumn: 27,
		},
		{
			code: `$breakpoints: ( small: 767px, medium: 992PX, large: 1200px );`,
			fixed: `$breakpoints: ( small: 767px, medium: 992px, large: 1200px );`,
			description: `an upper-case unit in the second entry of an SCSS map`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 42,
			endLine: 1,
			endColumn: 44,
		},
		{
			code: `a { font: (italic bold 10px/8PX) }`,
			fixed: `a { font: (italic bold 10px/8px) }`,
			description: `an upper-case unit in a value written as a parenthesised list`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 30,
			endLine: 1,
			endColumn: 32,
		},
		{
			code: `font: 14PX/#{$line-height};`,
			fixed: `font: 14px/#{$line-height};`,
			description: `an upper-case unit in a value that ends in an interpolation`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 9,
			endLine: 1,
			endColumn: 11,
		},
		{
			code: `a { margin: calc(100% - #{$margin * 2PX}); }`,
			fixed: `a { margin: calc(100% - #{$margin * 2px}); }`,
			description: `an upper-case unit inside an interpolation nested in calc`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 38,
			endLine: 1,
			endColumn: 41,
		},
	],
})

testRule({
	ruleName,
	customSyntax: `postcss-less`,
	config: [`lower`],

	accept: [
		{
			code: `a { width: 1em; \n// width: 10PX\n }`,
			description: `a unit inside an end-of-line comment, which the rule does not read`,
		},
	],

	reject: [
		{
			code: `@variable: 10PX`,
			fixed: `@variable: 10px`,
			description: `an upper-case unit in the value of a Less at-variable`,
			message: messages.expected(`PX`, `px`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
		{
			code: `@variable: 10pX`,
			fixed: `@variable: 10px`,
			description: `a unit ending in a capital in the value of a Less at-variable`,
			message: messages.expected(`pX`, `px`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
		{
			code: `@variable: 10Px`,
			fixed: `@variable: 10px`,
			description: `a unit opening with a capital in the value of a Less at-variable`,
			message: messages.expected(`Px`, `px`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
	],
})

testRule({
	ruleName,
	config: [`upper`],

	accept: [
		{
			code: `a { line-height: 1; }`,
			description: `a unitless number`,
		},
		{
			code: `a { color: #000; }`,
			description: `a hex colour, whose digits carry no unit`,
		},
		{
			code: `a { font-size: 100%; }`,
			description: `a percentage`,
		},
		{
			code: `a { font-size: .5REM; }`,
			description: `a unit after a fraction with no leading zero`,
		},
		{
			code: `a { font-size: 0.5REM; }`,
			description: `a unit after a fraction with a leading zero`,
		},
		{
			code: `a { width: 10PX; }`,
			description: `an upper-case unit`,
		},
		{
			code: `a { margin: 0 10EM 5REM 2IN; }`,
			description: `a run of values with upper-case units`,
		},
		{
			code: `a { background-position: top right, 1EM 5VH; }`,
			description: `a keyword pair and a pair of units in one value`,
		},
		{
			code: `a { top: calc(10EM - 3EM); }`,
			description: `units inside a calc expression`,
		},
		{
			code: `a { background-image: linear-gradient(to right, white calc(100% - 50EM), silver); }`,
			description: `a unit inside a calc expression nested in a gradient`,
		},
		{
			code: `a { transform: rotate(90DEG); }`,
			description: `a unit inside the arguments of a function`,
		},
		{
			code: `a { color: green; }`,
			description: `a keyword, which carries no unit`,
		},
		{
			code: `a { color: green10px; }`,
			description: `a keyword that ends in what looks like a unit`,
		},
		{
			code: `a { width: /* 100px */ 1EM; }`,
			description: `a unit inside a comment, which the rule does not read`,
		},
		{
			code: `a::before { content: "10px"}`,
			description: `a unit inside a string`,
		},
		{
			code: `a { font-size: $fs10px; }`,
			description: `a unit inside the name of an SCSS variable`,
		},
		{
			code: `a { font-size: @fs10px; }`,
			description: `a unit inside the name of a Less variable`,
		},
		{
			code: `a { font-size: var(--some-fs-10px); }`,
			description: `a unit inside the name of a custom property`,
		},
		{
			code: `a { margin: url(13px); }`,
			description: `a unit inside the address of a url call`,
		},
		{
			code: `a { margin10px: 10PX; }`,
			description: `a unit inside a property name`,
		},
		{
			code: `a10px { margin: 10PX; }`,
			description: `a unit inside a type selector`,
		},
		{
			code: `#a10px { margin: 10PX; }`,
			description: `a unit inside an id selector`,
		},
		{
			code: `.a10px { margin: 10PX; }`,
			description: `a unit inside a class selector`,
		},
		{
			code: `input[type=10px] { margin: 10PX; }`,
			description: `a unit inside the value of an attribute selector`,
		},
		{
			code: `a:hover10px { margin: 10PX; }`,
			description: `a unit inside a pseudo-class`,
		},
		{
			code: `a::before10px { margin: 10PX; }`,
			description: `a unit inside a pseudo-element`,
		},
		{
			code: `a { margin: 13XPX; }`,
			description: `a unit no specification knows, written in upper case`,
		},
	],

	reject: [
		{
			code: `a { width: 10pX; }`,
			fixed: `a { width: 10PX; }`,
			description: `a unit ending in a capital`,
			message: messages.expected(`pX`, `PX`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
		{
			code: `a { width: 10Px; }`,
			fixed: `a { width: 10PX; }`,
			description: `a unit opening with a capital`,
			message: messages.expected(`Px`, `PX`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
		{
			code: `a { width: 10px; }`,
			fixed: `a { width: 10PX; }`,
			description: `a unit in lower case`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
		{
			code: `a { font-size: .5rem; }`,
			fixed: `a { font-size: .5REM; }`,
			description: `a lower-case unit after a fraction with no leading zero`,
			message: messages.expected(`rem`, `REM`),
			line: 1,
			column: 18,
			endLine: 1,
			endColumn: 21,
		},
		{
			code: `a { font-size: 0.5rem; }`,
			fixed: `a { font-size: 0.5REM; }`,
			description: `a lower-case unit after a fraction with a leading zero`,
			message: messages.expected(`rem`, `REM`),
			line: 1,
			column: 19,
			endLine: 1,
			endColumn: 22,
		},
		{
			code: `a { margin: 10PX 10px; }`,
			fixed: `a { margin: 10PX 10PX; }`,
			description: `the second of two units in lower case`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 20,
			endLine: 1,
			endColumn: 22,
		},
		{
			code: `a { margin: calc(10PX + 10px); }`,
			fixed: `a { margin: calc(10PX + 10PX); }`,
			description: `a lower-case unit inside a calc expression`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 27,
			endLine: 1,
			endColumn: 29,
		},
		{
			code: `a { margin: -webkit-calc(13px + 10PX); }`,
			fixed: `a { margin: -webkit-calc(13PX + 10PX); }`,
			description: `a lower-case unit inside a vendor-prefixed calc expression`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 28,
			endLine: 1,
			endColumn: 30,
		},
		{
			code: `a { margin: some-function(13px + 10PX); }`,
			fixed: `a { margin: some-function(13PX + 10PX); }`,
			description: `a lower-case unit inside the arguments of a function no specification knows`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 29,
			endLine: 1,
			endColumn: 31,
		},
		{
			code: `root { --margin: 10px; }`,
			fixed: `root { --margin: 10PX; }`,
			description: `a lower-case unit in the value of a custom property`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 20,
			endLine: 1,
			endColumn: 22,
		},
		{
			code: `root { --margin: 10PX + 10px; }`,
			fixed: `root { --margin: 10PX + 10PX; }`,
			description: `a lower-case unit in a sum inside a custom property`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 27,
			endLine: 1,
			endColumn: 29,
		},
		{
			code: `a { margin: 13xpx; }`,
			fixed: `a { margin: 13XPX; }`,
			message: messages.expected(`xpx`, `XPX`),
			description: `a unit no specification knows, written in lower case`,
			line: 1,
			column: 15,
			endLine: 1,
			endColumn: 18,
		},
	],
})

testRule({
	ruleName,
	customSyntax: `postcss-scss`,
	config: [`upper`],

	accept: [
		{
			code: `a { width: 1EM; \n// width: 10px\n }`,
			description: `a unit inside an end-of-line comment, which the rule does not read`,
		},
		{
			code: `a { margin: calc(100% - #{$margin * 2}); }`,
			description: `an interpolation inside a calc expression, which carries no unit of its own`,
		},
	],

	reject: [
		{
			code: `a { margin: 10px; }`,
			fixed: `a { margin: 10PX; }`,
			description: `a lower-case unit`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 15,
			endLine: 1,
			endColumn: 17,
		},
		{
			code: `a { margin: 10pX; }`,
			fixed: `a { margin: 10PX; }`,
			description: `a unit ending in a capital`,
			message: messages.expected(`pX`, `PX`),
			line: 1,
			column: 15,
			endLine: 1,
			endColumn: 17,
		},
		{
			code: `a { margin: 10Px; }`,
			fixed: `a { margin: 10PX; }`,
			description: `a unit opening with a capital`,
			message: messages.expected(`Px`, `PX`),
			line: 1,
			column: 15,
			endLine: 1,
			endColumn: 17,
		},
		{
			code: `a { margin: 10px + 10PX; }`,
			fixed: `a { margin: 10PX + 10PX; }`,
			description: `a lower-case unit in a sum`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 15,
			endLine: 1,
			endColumn: 17,
		},
		{
			code: `a { $margin: 10px; }`,
			fixed: `a { $margin: 10PX; }`,
			description: `a lower-case unit in the value of an SCSS variable`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 16,
			endLine: 1,
			endColumn: 18,
		},
		{
			code: `a { $margin: 10PX + 10px; }`,
			fixed: `a { $margin: 10PX + 10PX; }`,
			description: `a lower-case unit in a sum inside an SCSS variable`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 23,
			endLine: 1,
			endColumn: 25,
		},
		{
			code: `a { margin: $margin + 10px; }`,
			fixed: `a { margin: $margin + 10PX; }`,
			description: `a lower-case unit added to an SCSS variable`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 25,
			endLine: 1,
			endColumn: 27,
		},
		{
			code: `$breakpoints: ( small: 767PX, medium: 992px, large: 1200PX );`,
			fixed: `$breakpoints: ( small: 767PX, medium: 992PX, large: 1200PX );`,
			description: `a lower-case unit in the second entry of an SCSS map`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 42,
			endLine: 1,
			endColumn: 44,
		},
		{
			code: `a { font: (italic bold 10PX/8px) }`,
			fixed: `a { font: (italic bold 10PX/8PX) }`,
			description: `a lower-case unit in a value written as a parenthesised list`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 30,
			endLine: 1,
			endColumn: 32,
		},
		{
			code: `font: 14px/#{$line-height};`,
			fixed: `font: 14PX/#{$line-height};`,
			description: `a lower-case unit in a value that ends in an interpolation`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 9,
			endLine: 1,
			endColumn: 11,
		},
		{
			code: `a { margin: calc(100% - #{$margin * 2px}); }`,
			fixed: `a { margin: calc(100% - #{$margin * 2PX}); }`,
			description: `a lower-case unit inside an interpolation nested in calc`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 38,
			endLine: 1,
			endColumn: 41,
		},
	],
})

testRule({
	ruleName,
	customSyntax: `postcss-less`,
	config: [`upper`],

	accept: [
		{
			code: `a { width: 1EM; \n// width: 10px\n }`,
			description: `a unit inside an end-of-line comment, which the rule does not read`,
		},
	],

	reject: [
		{
			code: `@variable: 10px`,
			fixed: `@variable: 10PX`,
			description: `a lower-case unit in the value of a Less at-variable`,
			message: messages.expected(`px`, `PX`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
		{
			code: `@variable: 10pX`,
			fixed: `@variable: 10PX`,
			description: `a unit ending in a capital in the value of a Less at-variable`,
			message: messages.expected(`pX`, `PX`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
		{
			code: `@variable: 10Px`,
			fixed: `@variable: 10PX`,
			description: `a unit opening with a capital in the value of a Less at-variable`,
			message: messages.expected(`Px`, `PX`),
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 16,
		},
	],
})
