import { expect, it } from "vitest"

import { hasEmptyLine } from "./index.js"

it(`hasEmptyLine`, () => {
	expect(hasEmptyLine(`\n\n`)).toBe(true)
	expect(hasEmptyLine(`\r\n\r\n`)).toBe(true)
	expect(hasEmptyLine(`\n\n\n\n`)).toBe(true)
	expect(hasEmptyLine(`\r\n\r\n\r\n\r\n`)).toBe(true)
	expect(hasEmptyLine(`   \n\n`)).toBe(true)
	expect(hasEmptyLine(`\n\n   \n\n`)).toBe(true)
	expect(hasEmptyLine(`\n \n`)).toBe(true)
	expect(hasEmptyLine(`\r\n \r\n`)).toBe(true)
	expect(hasEmptyLine(`\n \n \n \n`)).toBe(true)
	expect(hasEmptyLine(`\r \n\n r\n\r\n\r\n`)).toBe(true)
	expect(hasEmptyLine(`   \n \n`)).toBe(true)
	expect(hasEmptyLine(`\n \n   \n \n`)).toBe(true)
	expect(hasEmptyLine(`\n\t\n`)).toBe(true)
	expect(hasEmptyLine(`\n\t \n`)).toBe(true)
	expect(hasEmptyLine(`\r\n\t\r\n`)).toBe(true)
	expect(hasEmptyLine(`\n\t\n\n \t\n`)).toBe(true)
	expect(hasEmptyLine(`\r\n\t\r\n\t\r\n\r\n`)).toBe(true)
	expect(hasEmptyLine(`   \n\t\n`)).toBe(true)
	expect(hasEmptyLine(`\n\t\n  \t  \n\n`)).toBe(true)
	expect(hasEmptyLine(``)).toBe(false)
	expect(hasEmptyLine(` `)).toBe(false)
	expect(hasEmptyLine(`\t`)).toBe(false)
	expect(hasEmptyLine(`\n`)).toBe(false)
	expect(hasEmptyLine(`\r\n`)).toBe(false)
	expect(hasEmptyLine(`\r\r`)).toBe(true)
	expect(hasEmptyLine(`\f\f`)).toBe(true)
	expect(hasEmptyLine(`\r\t\r`)).toBe(true)
	expect(hasEmptyLine(`\n\r\n`)).toBe(true)
	expect(hasEmptyLine(`\r\n\n`)).toBe(true)
	expect(hasEmptyLine(`\r`)).toBe(false)
	expect(hasEmptyLine(`\f`)).toBe(false)
	expect(hasEmptyLine(`\r\n \t`)).toBe(false)
})
