import { messages, ruleName } from "./index.js"

const testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [true],

	accept: [
		{
			code: `@import 'x.css';`,
			description: `an import closed by its own semicolon`,
		},
		{
			code: `.foo { color: red }`,
			description: `a declaration with no semicolon behind it`,
		},
		{
			code: `.foo { color: red; }`,
			description: `a declaration closed by a semicolon`,
		},
		{
			code: `.foo { color: red; display: block; }`,
			description: `two declarations, each closed by a semicolon`,
		},
		{
			code: `.foo { color: red; display: block }`,
			description: `two declarations, the last with no semicolon behind it`,
		},
		{
			code: `@media screen { a { color: red; } }`,
			description: `a rule nested inside a media query`,
		},
		{
			code: `/* comment */`,
			description: `a comment`,
		},
		{
			code: `/* comment; */`,
			description: `a semicolon inside a comment`,
		},
		{
			code: `/* ;;comment;; words;; */`,
			description: `semicolons standing among the words of a comment`,
		},
		{
			code: `a { content: ''; }`,
			description: `an empty string for a value`,
		},
		{
			code: `a { content: ';'; }`,
			description: `a semicolon inside a string`,
		},
		{
			code: `a { content: ';;'; }`,
			description: `two semicolons inside a string`,
		},
		{
			code: `a { content: ';\t; ;'; }`,
			description: `semicolons and whitespace inside a string`,
		},
		{
			code: `:root { --foo: red; --bar: blue; }`,
			description: `two custom properties, each closed by a semicolon`,
		},
	],

	reject: [
		{
			code: `;`,
			fixed: ``,
			description: `a semicolon standing alone in the stylesheet`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: ` ;`,
			fixed: ` `,
			description: `the same semicolon behind a space`,
			message: messages.rejected,
			line: 1,
			column: 2,
		},
		{
			code: `  ;`,
			fixed: `  `,
			description: `the same behind two spaces`,
			message: messages.rejected,
			line: 1,
			column: 3,
		},
		{
			code: `\n;`,
			fixed: `\n`,
			description: `the same behind a newline`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `\n\n;`,
			fixed: `\n\n`,
			description: `the same behind two newlines`,
			message: messages.rejected,
			line: 3,
			column: 1,
		},
		{
			code: `\r\n;`,
			fixed: `\r\n`,
			description: `the same behind a carriage-return line break`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `\r\n\r\n;`,
			fixed: `\r\n\r\n`,
			description: `the same behind two carriage-return line breaks`,
			message: messages.rejected,
			line: 3,
			column: 1,
		},
		{
			code: `\r;`,
			fixed: `\r`,
			description: `the same behind a bare carriage return`,
			message: messages.rejected,
			line: 1,
			column: 2,
		},
		{
			code: `\r\r;`,
			fixed: `\r\r`,
			description: `the same behind two bare carriage returns`,
			message: messages.rejected,
			line: 1,
			column: 3,
		},
		{
			code: `\t;`,
			fixed: `\t`,
			description: `the same behind a tab`,
			message: messages.rejected,
			line: 1,
			column: 2,
		},
		{
			code: `\t\t;`,
			fixed: `\t\t`,
			description: `the same behind two tabs`,
			message: messages.rejected,
			line: 1,
			column: 3,
		},
		{
			code: `; ; ;`,
			fixed: `  `,
			description: `three semicolons standing apart in the stylesheet`,
			warnings: [
				{
					message: messages.rejected,
					line: 1,
					column: 1,
				},
				{
					message: messages.rejected,
					line: 1,
					column: 3,
				},
				{
					message: messages.rejected,
					line: 1,
					column: 5,
				},
			],
		},
		{
			code: `a {;}`,
			fixed: `a {}`,
			description: `a semicolon standing alone inside a block`,
			message: messages.rejected,
			line: 1,
			column: 4,
		},
		{
			code: `a { ;}`,
			fixed: `a { }`,
			description: `the same semicolon behind a space`,
			message: messages.rejected,
			line: 1,
			column: 5,
		},
		{
			code: `a {; }`,
			fixed: `a { }`,
			description: `the same in front of a space`,
			message: messages.rejected,
			line: 1,
			column: 4,
		},
		{
			code: `a { ; }`,
			fixed: `a {  }`,
			description: `the same between two spaces`,
			message: messages.rejected,
			line: 1,
			column: 5,
		},
		{
			code: `a {  ;}`,
			fixed: `a {  }`,
			description: `the same behind two spaces`,
			message: messages.rejected,
			line: 1,
			column: 6,
		},
		{
			code: `a {;  }`,
			fixed: `a {  }`,
			description: `the same in front of two spaces`,
			message: messages.rejected,
			line: 1,
			column: 4,
		},
		{
			code: `a {  ;  }`,
			fixed: `a {    }`,
			description: `the same between two spaces on either side`,
			message: messages.rejected,
			line: 1,
			column: 6,
		},
		{
			code: `a {   ;   }`,
			fixed: `a {      }`,
			description: `the same between three spaces on either side`,
			message: messages.rejected,
			line: 1,
			column: 7,
		},
		{
			code: `a {\n;}`,
			fixed: `a {\n}`,
			description: `the same behind a newline`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `a {;\n}`,
			fixed: `a {\n}`,
			description: `the same in front of a newline`,
			message: messages.rejected,
			line: 1,
			column: 4,
		},
		{
			code: `a {\n;\n}`,
			fixed: `a {\n\n}`,
			description: `the same between two newlines`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `a {\r\n;}`,
			fixed: `a {\r\n}`,
			description: `the same behind a carriage-return line break`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `a {;\r\n}`,
			fixed: `a {\r\n}`,
			description: `the same in front of a carriage-return line break`,
			message: messages.rejected,
			line: 1,
			column: 4,
		},
		{
			code: `a {\r\n;\r\n}`,
			fixed: `a {\r\n\r\n}`,
			description: `the same between two carriage-return line breaks`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `a {\t;}`,
			fixed: `a {\t}`,
			description: `the same behind a tab`,
			message: messages.rejected,
			line: 1,
			column: 5,
		},
		{
			code: `a {;\t}`,
			fixed: `a {\t}`,
			description: `the same in front of a tab`,
			message: messages.rejected,
			line: 1,
			column: 4,
		},
		{
			code: `a {\t;\t}`,
			fixed: `a {\t\t}`,
			description: `the same between two tabs`,
			message: messages.rejected,
			line: 1,
			column: 5,
		},
		{
			code: `a { ;\n;\t; }`,
			fixed: `a { \n\t }`,
			description: `three semicolons standing alone inside a block`,
			warnings: [
				{
					message: messages.rejected,
					line: 1,
					column: 5,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 1,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 3,
				},
			],
		},
		{
			code: `a { color: red; };`,
			fixed: `a { color: red; }`,
			description: `a semicolon behind the closing brace`,
			message: messages.rejected,
			line: 1,
			column: 18,
		},
		{
			code: `a { color: red; } ;`,
			fixed: `a { color: red; } `,
			description: `the same semicolon behind a space`,
			message: messages.rejected,
			line: 1,
			column: 19,
		},
		{
			code: `a { color: red; }\n;`,
			fixed: `a { color: red; }\n`,
			description: `the same behind a newline`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `a { color: red; }\n\n;`,
			fixed: `a { color: red; }\n\n`,
			description: `the same behind two newlines`,
			message: messages.rejected,
			line: 3,
			column: 1,
		},
		{
			code: `a { color: red; }\r\n;`,
			fixed: `a { color: red; }\r\n`,
			description: `the same behind a carriage-return line break`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `a { color: red; }\r\n\r\n;`,
			fixed: `a { color: red; }\r\n\r\n`,
			description: `the same behind two carriage-return line breaks`,
			message: messages.rejected,
			line: 3,
			column: 1,
		},
		{
			code: `a { color: red; }\r;`,
			fixed: `a { color: red; }\r`,
			description: `the same behind a bare carriage return`,
			message: messages.rejected,
			line: 1,
			column: 19,
		},
		{
			code: `a { color: red; }\r\r;`,
			fixed: `a { color: red; }\r\r`,
			description: `the same behind two bare carriage returns`,
			message: messages.rejected,
			line: 1,
			column: 20,
		},
		{
			code: `a { color: red; }\t;`,
			fixed: `a { color: red; }\t`,
			description: `the same behind a tab`,
			message: messages.rejected,
			line: 1,
			column: 19,
		},
		{
			code: `a { color: red; }\t\t;`,
			fixed: `a { color: red; }\t\t`,
			description: `the same behind two tabs`,
			message: messages.rejected,
			line: 1,
			column: 20,
		},
		{
			code: `a { color: red; };\t;\n; ;`,
			fixed: `a { color: red; }\t\n `,
			description: `four semicolons behind the closing brace`,
			warnings: [
				{
					message: messages.rejected,
					line: 1,
					column: 20,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 1,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 3,
				},
				{
					message: messages.rejected,
					line: 1,
					column: 18,
				},
			],
		},
		{
			code: `;a { color: red; }`,
			fixed: `a { color: red; }`,
			description: `a semicolon in front of a rule`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `; a { color: red; }`,
			fixed: ` a { color: red; }`,
			description: `the same semicolon in front of a space`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `;  a { color: red; }`,
			fixed: `  a { color: red; }`,
			description: `the same in front of two spaces`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `;\na { color: red; }`,
			fixed: `\na { color: red; }`,
			description: `the same in front of a newline`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `;\n\na { color: red; }`,
			fixed: `\n\na { color: red; }`,
			description: `the same in front of two newlines`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `;\r\na { color: red; }`,
			fixed: `\r\na { color: red; }`,
			description: `the same in front of a carriage-return line break`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `;\r\n\r\na { color: red; }`,
			fixed: `\r\n\r\na { color: red; }`,
			description: `the same in front of two carriage-return line breaks`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `;\ta { color: red; }`,
			fixed: `\ta { color: red; }`,
			description: `the same in front of a tab`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `;\t\ta { color: red; }`,
			fixed: `\t\ta { color: red; }`,
			description: `the same in front of two tabs`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `;\n;\t; ;a { color: red; }`,
			fixed: `\n\t a { color: red; }`,
			description: `four semicolons in front of a rule`,
			warnings: [
				{
					message: messages.rejected,
					line: 1,
					column: 1,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 1,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 3,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 5,
				},
			],
		},
		{
			code: `/*comment*/\n;\t; ;a { color: red; }`,
			fixed: `/*comment*/\n\t a { color: red; }`,
			description: `semicolons standing between a comment and a rule`,
			warnings: [
				{
					message: messages.rejected,
					line: 2,
					column: 1,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 3,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 5,
				},
			],
		},
		{
			code: `;/*comment*/\n;\t; ;a { color: red; }`,
			fixed: `/*comment*/\n\t a { color: red; }`,
			description: `the same, with one more semicolon in front of the comment`,
			warnings: [
				{
					message: messages.rejected,
					line: 1,
					column: 1,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 1,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 3,
				},
				{
					message: messages.rejected,
					line: 2,
					column: 5,
				},
			],
		},
		{
			code: `@media screen { ; }`,
			fixed: `@media screen {  }`,
			description: `a semicolon standing alone inside a media query`,
			message: messages.rejected,
			line: 1,
			column: 17,
		},
		{
			code: `@media screen { ;a { color: red; } }`,
			fixed: `@media screen { a { color: red; } }`,
			description: `a semicolon in front of a rule inside a media query`,
			message: messages.rejected,
			line: 1,
			column: 17,
		},
		{
			code: `@media screen { a { color: red; }; }`,
			fixed: `@media screen { a { color: red; } }`,
			description: `a semicolon behind a rule inside a media query`,
			message: messages.rejected,
			line: 1,
			column: 34,
		},
		{
			code: `@media screen { };`,
			fixed: `@media screen { }`,
			description: `a semicolon behind the closing brace of a media query`,
			message: messages.rejected,
			line: 1,
			column: 18,
		},
		{
			code: `;@media screen { }`,
			fixed: `@media screen { }`,
			description: `a semicolon in front of a media query`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `;/* comment */`,
			fixed: `/* comment */`,
			description: `a semicolon in front of a comment`,
			message: messages.rejected,
			line: 1,
			column: 1,
		},
		{
			code: `/* comment */;`,
			fixed: `/* comment */`,
			description: `a semicolon behind a comment`,
			message: messages.rejected,
			line: 1,
			column: 14,
		},
		{
			code: `/* comment */ ; /*comment */`,
			fixed: `/* comment */  /*comment */`,
			description: `a semicolon between two comments`,
			message: messages.rejected,
			line: 1,
			column: 15,
		},
		{
			code: `/* comment */\n;\n/* comment */`,
			fixed: `/* comment */\n\n/* comment */`,
			description: `the same semicolon on a line of its own`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `/* comment */\r\n;\r\n/* comment */`,
			fixed: `/* comment */\r\n\r\n/* comment */`,
			description: `the same written with carriage-return line breaks`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `/* comment */\t;\t/* comment */`,
			fixed: `/* comment */\t\t/* comment */`,
			description: `the same between tabs`,
			message: messages.rejected,
			line: 1,
			column: 15,
		},
		{
			code: `a {;/*c*/;/*c*/; color: red;; }`,
			fixed: `a {/*c*//*c*/ color: red; }`,
			description: `semicolons around two comments, and a second one behind the declaration`,
			warnings: [
				{
					message: messages.rejected,
					line: 1,
					column: 29,
				},
				{
					message: messages.rejected,
					line: 1,
					column: 4,
				},
				{
					message: messages.rejected,
					line: 1,
					column: 10,
				},
				{
					message: messages.rejected,
					line: 1,
					column: 16,
				},
			],
		},
		{
			code: `a { color: red;; }`,
			fixed: `a { color: red; }`,
			description: `a second semicolon behind a declaration`,
			message: messages.rejected,
			line: 1,
			column: 16,
		},
		{
			code: `a { color: red; ; }`,
			fixed: `a { color: red;  }`,
			description: `the same semicolon behind a space`,
			message: messages.rejected,
			line: 1,
			column: 17,
		},
		{
			code: `a { color: red;  ; }`,
			fixed: `a { color: red;   }`,
			description: `the same behind two spaces`,
			message: messages.rejected,
			line: 1,
			column: 18,
		},
		{
			code: `a { color: red;\n; }`,
			fixed: `a { color: red;\n }`,
			description: `the same behind a newline`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `a { color: red;\n\n; }`,
			fixed: `a { color: red;\n\n }`,
			description: `the same behind two newlines`,
			message: messages.rejected,
			line: 3,
			column: 1,
		},
		{
			code: `a { color: red;\r\n; }`,
			fixed: `a { color: red;\r\n }`,
			description: `the same behind a carriage-return line break`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `a { color: red;\r\n\r\n; }`,
			fixed: `a { color: red;\r\n\r\n }`,
			description: `the same behind two carriage-return line breaks`,
			message: messages.rejected,
			line: 3,
			column: 1,
		},
		{
			code: `a { color: red;\t; }`,
			fixed: `a { color: red;\t }`,
			description: `the same behind a tab`,
			message: messages.rejected,
			line: 1,
			column: 17,
		},
		{
			code: `a { color: red;\t\t; }`,
			fixed: `a { color: red;\t\t }`,
			description: `the same behind two tabs`,
			message: messages.rejected,
			line: 1,
			column: 18,
		},
		{
			code: `a { color: red ;; }`,
			fixed: `a { color: red ; }`,
			description: `a second semicolon behind a declaration whose value ends in a space`,
			message: messages.rejected,
			line: 1,
			column: 17,
		},
		{
			code: `a { color: red  ;; }`,
			fixed: `a { color: red  ; }`,
			description: `the same, with two spaces in front of the first semicolon`,
			message: messages.rejected,
			line: 1,
			column: 18,
		},
		{
			code: `a { color: red   ;; }`,
			fixed: `a { color: red   ; }`,
			description: `the same, with three`,
			message: messages.rejected,
			line: 1,
			column: 19,
		},
		{
			code: `a { color: red\n;; }`,
			fixed: `a { color: red\n; }`,
			description: `the same, with a newline in front of the first semicolon`,
			message: messages.rejected,
			line: 2,
			column: 2,
		},
		{
			code: `a { color: red\n\n;; }`,
			fixed: `a { color: red\n\n; }`,
			description: `the same, with two newlines`,
			message: messages.rejected,
			line: 3,
			column: 2,
		},
		{
			code: `a { color: red\r\n;; }`,
			fixed: `a { color: red\r\n; }`,
			description: `the same, with a carriage-return line break`,
			message: messages.rejected,
			line: 2,
			column: 2,
		},
		{
			code: `a { color: red\r\n\r\n;; }`,
			fixed: `a { color: red\r\n\r\n; }`,
			description: `the same, with two carriage-return line breaks`,
			message: messages.rejected,
			line: 3,
			column: 2,
		},
		{
			code: `a { color: red\t;; }`,
			fixed: `a { color: red\t; }`,
			description: `the same, with a tab`,
			message: messages.rejected,
			line: 1,
			column: 17,
		},
		{
			code: `a {\n  color: #FFF;;\n  /* foo */\n  /* bar */\n}`,
			fixed: `a {\n  color: #FFF;\n  /* foo */\n  /* bar */\n}`,
			description: `a second semicolon in front of the two comments that close the block`,
			message: messages.rejected,
			line: 2,
			column: 15,
		},
		{
			code: `a {\n  /* foo */\n  /* bar */\n  color: #FFF;;\n}`,
			fixed: `a {\n  /* foo */\n  /* bar */\n  color: #FFF;\n}`,
			description: `a second semicolon behind the two comments that open the block`,
			message: messages.rejected,
			line: 4,
			column: 15,
		},
		{
			code: `a {\n  /* foo */\n  color: #FFF;;\n  /* bar */\n}`,
			fixed: `a {\n  /* foo */\n  color: #FFF;\n  /* bar */\n}`,
			description: `a second semicolon between two comments`,
			message: messages.rejected,
			line: 3,
			column: 15,
		},
		{
			code: `@import 'x.css';;`,
			fixed: `@import 'x.css';`,
			description: `a second semicolon behind an import`,
			message: messages.rejected,
			line: 1,
			column: 17,
		},
		{
			code: `@import 'x.css'; ;`,
			fixed: `@import 'x.css'; `,
			description: `the same semicolon behind a space`,
			message: messages.rejected,
			line: 1,
			column: 18,
		},
		{
			code: `@import 'x.css';  ;`,
			fixed: `@import 'x.css';  `,
			description: `the same behind two spaces`,
			message: messages.rejected,
			line: 1,
			column: 19,
		},
		{
			code: `@import 'x.css';\n;`,
			fixed: `@import 'x.css';\n`,
			description: `the same behind a newline`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `@import 'x.css';\n\n;`,
			fixed: `@import 'x.css';\n\n`,
			description: `the same behind two newlines`,
			message: messages.rejected,
			line: 3,
			column: 1,
		},
		{
			code: `@import 'x.css';\r\n;`,
			fixed: `@import 'x.css';\r\n`,
			description: `the same behind a carriage-return line break`,
			message: messages.rejected,
			line: 2,
			column: 1,
		},
		{
			code: `@import 'x.css';\r\n\r\n;`,
			fixed: `@import 'x.css';\r\n\r\n`,
			description: `the same behind two carriage-return line breaks`,
			message: messages.rejected,
			line: 3,
			column: 1,
		},
		{
			code: `@import 'x.css';\t;`,
			fixed: `@import 'x.css';\t`,
			description: `the same behind a tab`,
			message: messages.rejected,
			line: 1,
			column: 18,
		},
		{
			code: `div a {\n  float: left;\n}\ndiv {\n  float: left;;\n}`,
			fixed: `div a {\n  float: left;\n}\ndiv {\n  float: left;\n}`,
			description: `a second semicolon behind the declaration of the second rule`,
			message: messages.rejected,
			line: 5,
			column: 15,
		},
		{
			code: `div a {\n  float: left;\n}\ndiv {\n  float: left;  ;\n}`,
			fixed: `div a {\n  float: left;\n}\ndiv {\n  float: left;  \n}`,
			description: `the same semicolon behind two spaces`,
			message: messages.rejected,
			line: 5,
			column: 17,
		},
		{
			code: `div a {\n  float: left;\n}\ndiv {\n  float: left;\n;\n}`,
			fixed: `div a {\n  float: left;\n}\ndiv {\n  float: left;\n\n}`,
			description: `the same on a line of its own`,
			message: messages.rejected,
			line: 6,
			column: 1,
		},
		{
			code: `:root { --foo: red;; --bar: blue; }`,
			fixed: `:root { --foo: red; --bar: blue; }`,
			description: `a second semicolon behind the first custom property`,
			message: messages.rejected,
			line: 1,
			column: 20,
		},
		{
			code: `:root { --foo: red; --bar: blue;; }`,
			fixed: `:root { --foo: red; --bar: blue; }`,
			description: `a second semicolon behind the last custom property`,
			message: messages.rejected,
			line: 1,
			column: 33,
		},
	],
})

testRule({
	ruleName,
	config: [true],
	customSyntax: `postcss-html`,

	accept: [
		{
			code: `<div>
<style>
a {
  color: red;
}
</style>
</div>`,
			description: `an embedded stylesheet with no semicolon to spare`,
		},
	],

	reject: [
		{
			code: `<div>
<style>
;
</style>
</div>`,
			fixed: `<div>
<style>

</style>
</div>`,
			description: `a semicolon standing alone in an embedded stylesheet`,
			message: messages.rejected,
			line: 3,
			column: 1,
		},
		{
			code: `<div>
<style>
a {
  color: red;;
}
</style>
</div>`,
			fixed: `<div>
<style>
a {
  color: red;
}
</style>
</div>`,
			description: `a second semicolon behind a declaration in an embedded stylesheet`,
			message: messages.rejected,
			line: 4,
			column: 14,
		},
	],
})

testRule({
	ruleName,
	config: [true],
	customSyntax: `postcss-less`,

	accept: [
		{
			code: `@import 'x.css';`,
			description: `an import closed by its own semicolon`,
		},
		{
			code: `a { .mixin(); .mixin2; }`,
			description: `two mixin calls, each closed by a semicolon`,
		},
		{
			code: `a { .mixin();; .mixin2;; }`,
			description: `a second semicolon behind each mixin call, which the syntax reads as part of the call`,
		},
	],

	reject: [
		{
			code: `a { .mixin();\ncolor: red;; }`,
			fixed: `a { .mixin();\ncolor: red; }`,
			description: `a second semicolon behind a declaration standing after a mixin call`,
			message: messages.rejected,
			line: 2,
			column: 12,
		},
	],
})
