import { messages, ruleName } from "./index.js"

const testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`always`],

	accept: [
		{
			code: `.foo { }`,
			description: `a selector with no attribute in it`,
		},
		{
			code: `[ target ] { }`,
			description: `a space inside each bracket, the attribute standing with no value`,
		},
		{
			code: `[  target  ] { }`,
			description: `two spaces inside each bracket, the attribute standing with no value`,
		},
		{
			code: `[ target=_blank ] { }`,
			description: `a space inside each bracket`,
		},
		{
			code: `[  target=_blank  ] { }`,
			description: `two spaces inside each bracket`,
		},
		{
			code: `[ target='_blank' ] { }`,
			description: `a space inside each bracket, the value in apostrophes`,
		},
		{
			code: `[ target="_blank" ] { }`,
			description: `a space inside each bracket, the value in quotation marks`,
		},
		{
			code: `[ title~=flower ] { }`,
			description: `a space inside each bracket, the whitespace-list operator`,
		},
		{
			code: `[ title|=flower ] { }`,
			description: `a space inside each bracket, the hyphen-list operator`,
		},
		{
			code: `[ title^=flower ] { }`,
			description: `a space inside each bracket, the prefix operator`,
		},
		{
			code: `[ title$=flower ] { }`,
			description: `a space inside each bracket, the suffix operator`,
		},
		{
			code: `a[ href*=w3schools ] { }`,
			description: `a space inside each bracket, the substring operator, behind a type selector`,
		},
		{
			code: `img[ alt~=person ][ src*=lorem ] { }`,
			description: `a space inside each bracket of either attribute selector`,
		},
		{
			code: `[ target=_blank ]:hover { }`,
			description: `a space inside each bracket, in front of a pseudo-class`,
		},
		{
			code: `[ target=_blank ]::before { }`,
			description: `a space inside each bracket, in front of a pseudo-element`,
		},
		{
			code: `option[ data-hidden=true ] { }`,
			description: `a space inside each bracket, behind a type selector`,
		},
		{
			code: `option[ dataHidden ] { }`,
			description: `a space inside each bracket, the attribute standing with no value, behind a type selector`,
		},
		{
			code: `@media screen and (max-width: 480px) { img[ align=right ] {} }`,
			description: `a space inside each bracket, inside a media query`,
		},
		{
			code: `[ target=_blank ] .foo { }`,
			description: `a space inside each bracket, in front of a descendant selector`,
		},
		{
			code: `li[ aria-hidden=false ]:nth-child(1) { }`,
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[ aria-hidden=false ]:nth-child( 1) { }`,
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class carrying a space inside its opening parenthesis`,
		},
		{
			code: `li[ aria-hidden=false ]:nth-child(1 ) { }`,
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class carrying a space inside its closing parenthesis`,
		},
		{
			code: `li[ aria-hidden=false ]:nth-child( 1 ) { }`,
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
		},
		{
			code: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			description: `a space inside each bracket of either attribute selector, the two selectors joined by a sibling combinator`,
		},
		{
			code: `[ target ] { content: "[" }`,
			description: `a space inside each bracket, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
		},
		{
			code: `[ target ] { content: "]" }`,
			description: `a space inside each bracket, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
		},
		{
			code: `[ foo=bar i ] { }`,
			description: `a space inside each bracket, a case flag behind the value`,
		},
		{
			code: `:root { --foo: 1px; }`,
			description: `a custom property under the root selector`,
		},
		{
			code: `html { --foo: 1px; }`,
			description: `a custom property under a type selector`,
		},
		{
			code: `:root { --custom-property-set: {} }`,
			description: `a custom property set under the root selector`,
		},
		{
			code: `html { --custom-property-set: {} }`,
			description: `a custom property set under a type selector`,
		},
		{
			code: `a[b=#{c}] { }`,
			description: `an attribute selector the parser cannot read`,
		},
	],

	reject: [
		{
			code: `[target ] { }`,
			fixed: `[ target ] { }`,
			description: `a space inside the closing bracket alone, the attribute standing with no value`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[ target] { }`,
			fixed: `[ target ] { }`,
			description: `a space inside the opening bracket alone, the attribute standing with no value`,
			message: messages.expectedClosing,
			line: 1,
			column: 8,
		},
		{
			code: `[target  ] { }`,
			fixed: `[ target  ] { }`,
			description: `two spaces inside the closing bracket alone, the attribute standing with no value`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[  target] { }`,
			fixed: `[  target ] { }`,
			description: `two spaces inside the opening bracket alone, the attribute standing with no value`,
			message: messages.expectedClosing,
			line: 1,
			column: 9,
		},
		{
			code: `[target=_blank ] { }`,
			fixed: `[ target=_blank ] { }`,
			description: `a space inside the closing bracket alone`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[ target=_blank] { }`,
			fixed: `[ target=_blank ] { }`,
			description: `a space inside the opening bracket alone`,
			message: messages.expectedClosing,
			line: 1,
			column: 15,
		},
		{
			code: `[target=_blank  ] { }`,
			fixed: `[ target=_blank  ] { }`,
			description: `two spaces inside the closing bracket alone`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[  target=_blank] { }`,
			fixed: `[  target=_blank ] { }`,
			description: `two spaces inside the opening bracket alone`,
			message: messages.expectedClosing,
			line: 1,
			column: 16,
		},
		{
			code: `[target='_blank' ] { }`,
			fixed: `[ target='_blank' ] { }`,
			description: `a space inside the closing bracket alone, the value in apostrophes`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[ target='_blank'] { }`,
			fixed: `[ target='_blank' ] { }`,
			description: `a space inside the opening bracket alone, the value in apostrophes`,
			message: messages.expectedClosing,
			line: 1,
			column: 17,
		},
		{
			code: `[target="_blank" ] { }`,
			fixed: `[ target="_blank" ] { }`,
			description: `a space inside the closing bracket alone, the value in quotation marks`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[ target="_blank"] { }`,
			fixed: `[ target="_blank" ] { }`,
			description: `a space inside the opening bracket alone, the value in quotation marks`,
			message: messages.expectedClosing,
			line: 1,
			column: 17,
		},
		{
			code: `a[href*=w3schools ] { }`,
			fixed: `a[ href*=w3schools ] { }`,
			description: `a space inside the closing bracket alone, the substring operator, behind a type selector`,
			message: messages.expectedOpening,
			line: 1,
			column: 3,
		},
		{
			code: `a[ href*=w3schools] { }`,
			fixed: `a[ href*=w3schools ] { }`,
			description: `a space inside the opening bracket alone, the substring operator, behind a type selector`,
			message: messages.expectedClosing,
			line: 1,
			column: 18,
		},
		{
			code: `img[alt~=person ][ src*=lorem ] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			description: `a space inside the closing bracket alone of the first attribute selector, a space inside each bracket of the second`,
			message: messages.expectedOpening,
			line: 1,
			column: 5,
		},
		{
			code: `img[ alt~=person][ src*=lorem ] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			description: `a space inside the opening bracket alone of the first attribute selector, a space inside each bracket of the second`,
			message: messages.expectedClosing,
			line: 1,
			column: 16,
		},
		{
			code: `img[ alt~=person ][src*=lorem ] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			description: `a space inside each bracket of the first attribute selector, a space inside the closing bracket alone of the second`,
			message: messages.expectedOpening,
			line: 1,
			column: 20,
		},
		{
			code: `img[ alt~=person ][ src*=lorem] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			description: `a space inside each bracket of the first attribute selector, a space inside the opening bracket alone of the second`,
			message: messages.expectedClosing,
			line: 1,
			column: 30,
		},
		{
			code: `[target=_blank ]:hover { }`,
			fixed: `[ target=_blank ]:hover { }`,
			description: `a space inside the closing bracket alone, in front of a pseudo-class`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[ target=_blank]:hover { }`,
			fixed: `[ target=_blank ]:hover { }`,
			description: `a space inside the opening bracket alone, in front of a pseudo-class`,
			message: messages.expectedClosing,
			line: 1,
			column: 15,
		},
		{
			code: `[target=_blank ]::before { }`,
			fixed: `[ target=_blank ]::before { }`,
			description: `a space inside the closing bracket alone, in front of a pseudo-element`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[ target=_blank]::before { }`,
			fixed: `[ target=_blank ]::before { }`,
			description: `a space inside the opening bracket alone, in front of a pseudo-element`,
			message: messages.expectedClosing,
			line: 1,
			column: 15,
		},
		{
			code: `option[data-hidden=true ] { }`,
			fixed: `option[ data-hidden=true ] { }`,
			description: `a space inside the closing bracket alone, behind a type selector`,
			message: messages.expectedOpening,
			line: 1,
			column: 8,
		},
		{
			code: `option[ data-hidden=true] { }`,
			fixed: `option[ data-hidden=true ] { }`,
			description: `a space inside the opening bracket alone, behind a type selector`,
			message: messages.expectedClosing,
			line: 1,
			column: 24,
		},
		{
			code: `option[dataHidden ] { }`,
			fixed: `option[ dataHidden ] { }`,
			description: `a space inside the closing bracket alone, the attribute standing with no value, behind a type selector`,
			message: messages.expectedOpening,
			line: 1,
			column: 8,
		},
		{
			code: `option[ dataHidden] { }`,
			fixed: `option[ dataHidden ] { }`,
			description: `a space inside the opening bracket alone, the attribute standing with no value, behind a type selector`,
			message: messages.expectedClosing,
			line: 1,
			column: 18,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align=right ] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[ align=right ] {} }`,
			description: `a space inside the closing bracket alone, inside a media query`,
			message: messages.expectedOpening,
			line: 1,
			column: 44,
		},
		{
			code: `@media screen and (max-width: 480px) { img[ align=right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[ align=right ] {} }`,
			description: `a space inside the opening bracket alone, inside a media query`,
			message: messages.expectedClosing,
			line: 1,
			column: 55,
		},
		{
			code: `[target=_blank ] .foo { }`,
			fixed: `[ target=_blank ] .foo { }`,
			description: `a space inside the closing bracket alone, in front of a descendant selector`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[ target=_blank] .foo { }`,
			fixed: `[ target=_blank ] .foo { }`,
			description: `a space inside the opening bracket alone, in front of a descendant selector`,
			message: messages.expectedClosing,
			line: 1,
			column: 15,
		},
		{
			code: `li[aria-hidden=false ]:nth-child(1) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child(1) { }`,
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class`,
			message: messages.expectedOpening,
			line: 1,
			column: 4,
		},
		{
			code: `li[ aria-hidden=false]:nth-child(1) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child(1) { }`,
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class`,
			message: messages.expectedClosing,
			line: 1,
			column: 21,
		},
		{
			code: `li[aria-hidden=false ]:nth-child( 1 ) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child( 1 ) { }`,
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			message: messages.expectedOpening,
			line: 1,
			column: 4,
		},
		{
			code: `li[ aria-hidden=false]:nth-child( 1 ) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child( 1 ) { }`,
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			message: messages.expectedClosing,
			line: 1,
			column: 21,
		},
		{
			code: `ul li[aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			description: `a space inside the closing bracket alone of the first attribute selector, a space inside each bracket of the second, the two selectors joined by a sibling combinator`,
			message: messages.expectedOpening,
			line: 1,
			column: 7,
		},
		{
			code: `ul li[ aria-hidden=false] + li[ aria-hidden=false ] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			description: `a space inside the opening bracket alone of the first attribute selector, a space inside each bracket of the second, the two selectors joined by a sibling combinator`,
			message: messages.expectedClosing,
			line: 1,
			column: 24,
		},
		{
			code: `ul li[ aria-hidden=false ] + li[aria-hidden=false ] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			description: `a space inside each bracket of the first attribute selector, a space inside the closing bracket alone of the second, the two selectors joined by a sibling combinator`,
			message: messages.expectedOpening,
			line: 1,
			column: 33,
		},
		{
			code: `ul li[ aria-hidden=false ] + li[ aria-hidden=false] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			description: `a space inside each bracket of the first attribute selector, a space inside the opening bracket alone of the second, the two selectors joined by a sibling combinator`,
			message: messages.expectedClosing,
			line: 1,
			column: 50,
		},
		{
			code: `[target ] { content: "[" }`,
			fixed: `[ target ] { content: "[" }`,
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[ target] { content: "[" }`,
			fixed: `[ target ] { content: "[" }`,
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			message: messages.expectedClosing,
			line: 1,
			column: 8,
		},
		{
			code: `[target ] { content: "]" }`,
			fixed: `[ target ] { content: "]" }`,
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[ target] { content: "]" }`,
			fixed: `[ target ] { content: "]" }`,
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			message: messages.expectedClosing,
			line: 1,
			column: 8,
		},
		{
			code: `[ foo=bar i] { }`,
			fixed: `[ foo=bar i ] { }`,
			description: `a space inside the opening bracket alone, a case flag behind the value`,
			message: messages.expectedClosing,
			line: 1,
			column: 11,
		},
		{
			code: `[foo=bar i ] { }`,
			fixed: `[ foo=bar i ] { }`,
			description: `a space inside the closing bracket alone, a case flag behind the value`,
			message: messages.expectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `img[alt~=person][src*=lorem] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			description: `no space inside either bracket of either attribute selector`,
			warnings: [
				{
					message: messages.expectedOpening,
					line: 1,
					column: 5,
				},
				{
					message: messages.expectedClosing,
					line: 1,
					column: 15,
				},
				{
					message: messages.expectedOpening,
					line: 1,
					column: 18,
				},
				{
					message: messages.expectedClosing,
					line: 1,
					column: 27,
				},
			],
		},
		{
			code: `[/**/foo=bar i] { }`,
			fixed: `[ /**/foo=bar i ] { }`,
			description: `no space inside either bracket, a comment opening the brackets, a case flag behind the value`,
			warnings: [
				{
					message: messages.expectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.expectedClosing,
					line: 1,
					column: 14,
				},
			],
		},
		{
			code: `[foo=bar i /**/] { }`,
			fixed: `[ foo=bar i /**/ ] { }`,
			description: `no space inside either bracket, a comment closing them, a space in front of it, a case flag behind the value`,
			warnings: [
				{
					message: messages.expectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.expectedClosing,
					line: 1,
					column: 15,
				},
			],
		},
		{
			code: `[foo=bar i/**/] { }`,
			fixed: `[ foo=bar i/**/ ] { }`,
			description: `no space inside either bracket, a comment closing them, a case flag behind the value`,

			warnings: [
				{
					message: messages.expectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.expectedClosing,
					line: 1,
					column: 14,
				},
			],
		},
		{
			code: `[foo=bar/**/] { }`,
			fixed: `[ foo=bar/**/ ] { }`,
			description: `no space inside either bracket, a comment closing them`,
			warnings: [
				{
					message: messages.expectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.expectedClosing,
					line: 1,
					column: 12,
				},
			],
		},
		{
			code: `[foo/**/] { }`,
			fixed: `[ foo/**/ ] { }`,
			description: `no space inside either bracket, the attribute standing with no value, a comment closing them`,
			warnings: [
				{
					message: messages.expectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.expectedClosing,
					line: 1,
					column: 8,
				},
			],
		},
	],
})

testRule({
	ruleName,
	config: [`never`],

	accept: [
		{
			code: `.foo { }`,
			description: `a selector with no attribute in it`,
		},
		{
			code: `[target] { }`,
			description: `no space inside either bracket, the attribute standing with no value`,
		},
		{
			code: `[target=_blank] { }`,
			description: `no space inside either bracket`,
		},
		{
			code: `[target='_blank'] { }`,
			description: `no space inside either bracket, the value in apostrophes`,
		},
		{
			code: `[target="_blank"] { }`,
			description: `no space inside either bracket, the value in quotation marks`,
		},
		{
			code: `[title~=flower] { }`,
			description: `no space inside either bracket, the whitespace-list operator`,
		},
		{
			code: `[title|=flower] { }`,
			description: `no space inside either bracket, the hyphen-list operator`,
		},
		{
			code: `[title^=flower] { }`,
			description: `no space inside either bracket, the prefix operator`,
		},
		{
			code: `[title$=flower] { }`,
			description: `no space inside either bracket, the suffix operator`,
		},
		{
			code: `a[href*=w3schools] { }`,
			description: `no space inside either bracket, the substring operator, behind a type selector`,
		},
		{
			code: `img[alt~=person][src*=lorem] { }`,
			description: `no space inside either bracket of either attribute selector`,
		},
		{
			code: `[target=_blank]:hover { }`,
			description: `no space inside either bracket, in front of a pseudo-class`,
		},
		{
			code: `[target=_blank]::before { }`,
			description: `no space inside either bracket, in front of a pseudo-element`,
		},
		{
			code: `option[data-hidden=true] { }`,
			description: `no space inside either bracket, behind a type selector`,
		},
		{
			code: `option[dataHidden] { }`,
			description: `no space inside either bracket, the attribute standing with no value, behind a type selector`,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			description: `no space inside either bracket, inside a media query`,
		},
		{
			code: `[target=_blank] .foo { }`,
			description: `no space inside either bracket, in front of a descendant selector`,
		},
		{
			code: `li[aria-hidden=false]:nth-child(1) { }`,
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden=false]:nth-child( 1) { }`,
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class carrying a space inside its opening parenthesis`,
		},
		{
			code: `li[aria-hidden=false]:nth-child(1 ) { }`,
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class carrying a space inside its closing parenthesis`,
		},
		{
			code: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
		},
		{
			code: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			description: `no space inside either bracket of either attribute selector, the two selectors joined by a sibling combinator`,
		},
		{
			code: `[target] { content: "[" }`,
			description: `no space inside either bracket, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
		},
		{
			code: `[target] { content: "]" }`,
			description: `no space inside either bracket, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
		},
		{
			code: `[foo=bar i] { }`,
			description: `no space inside either bracket, a case flag behind the value`,
		},
	],

	reject: [
		{
			code: `[ target] { }`,
			fixed: `[target] { }`,
			description: `a space inside the opening bracket alone, the attribute standing with no value`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target ] { }`,
			fixed: `[target] { }`,
			description: `a space inside the closing bracket alone, the attribute standing with no value`,
			message: messages.rejectedClosing,
			line: 1,
			column: 8,
		},
		{
			code: `[  target] { }`,
			fixed: `[target] { }`,
			description: `two spaces inside the opening bracket alone, the attribute standing with no value`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target  ] { }`,
			fixed: `[target] { }`,
			description: `two spaces inside the closing bracket alone, the attribute standing with no value`,
			message: messages.rejectedClosing,
			line: 1,
			column: 9,
		},
		{
			code: `[ target=_blank] { }`,
			fixed: `[target=_blank] { }`,
			description: `a space inside the opening bracket alone`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target=_blank ] { }`,
			fixed: `[target=_blank] { }`,
			description: `a space inside the closing bracket alone`,
			message: messages.rejectedClosing,
			line: 1,
			column: 15,
		},
		{
			code: `[  target=_blank] { }`,
			fixed: `[target=_blank] { }`,
			description: `two spaces inside the opening bracket alone`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target=_blank  ] { }`,
			fixed: `[target=_blank] { }`,
			description: `two spaces inside the closing bracket alone`,
			message: messages.rejectedClosing,
			line: 1,
			column: 16,
		},
		{
			code: `[ target='_blank'] { }`,
			fixed: `[target='_blank'] { }`,
			description: `a space inside the opening bracket alone, the value in apostrophes`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target='_blank' ] { }`,
			fixed: `[target='_blank'] { }`,
			description: `a space inside the closing bracket alone, the value in apostrophes`,
			message: messages.rejectedClosing,
			line: 1,
			column: 17,
		},
		{
			code: `[ target="_blank"] { }`,
			fixed: `[target="_blank"] { }`,
			description: `a space inside the opening bracket alone, the value in quotation marks`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target="_blank" ] { }`,
			fixed: `[target="_blank"] { }`,
			description: `a space inside the closing bracket alone, the value in quotation marks`,
			message: messages.rejectedClosing,
			line: 1,
			column: 17,
		},
		{
			code: `a[ href*=w3schools] { }`,
			fixed: `a[href*=w3schools] { }`,
			description: `a space inside the opening bracket alone, the substring operator, behind a type selector`,
			message: messages.rejectedOpening,
			line: 1,
			column: 3,
		},
		{
			code: `a[href*=w3schools ] { }`,
			fixed: `a[href*=w3schools] { }`,
			description: `a space inside the closing bracket alone, the substring operator, behind a type selector`,
			message: messages.rejectedClosing,
			line: 1,
			column: 18,
		},
		{
			code: `img[ alt~=person][src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			description: `a space inside the opening bracket alone of the first attribute selector, no space inside either bracket of the second`,
			message: messages.rejectedOpening,
			line: 1,
			column: 5,
		},
		{
			code: `img[alt~=person ][src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			description: `a space inside the closing bracket alone of the first attribute selector, no space inside either bracket of the second`,
			message: messages.rejectedClosing,
			line: 1,
			column: 16,
		},
		{
			code: `img[alt~=person][ src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			description: `no space inside either bracket of the first attribute selector, a space inside the opening bracket alone of the second`,
			message: messages.rejectedOpening,
			line: 1,
			column: 18,
		},
		{
			code: `img[alt~=person][src*=lorem ] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			description: `no space inside either bracket of the first attribute selector, a space inside the closing bracket alone of the second`,
			message: messages.rejectedClosing,
			line: 1,
			column: 28,
		},
		{
			code: `[ target=_blank]:hover { }`,
			fixed: `[target=_blank]:hover { }`,
			description: `a space inside the opening bracket alone, in front of a pseudo-class`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target=_blank ]:hover { }`,
			fixed: `[target=_blank]:hover { }`,
			description: `a space inside the closing bracket alone, in front of a pseudo-class`,
			message: messages.rejectedClosing,
			line: 1,
			column: 15,
		},
		{
			code: `[ target=_blank]::before { }`,
			fixed: `[target=_blank]::before { }`,
			description: `a space inside the opening bracket alone, in front of a pseudo-element`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target=_blank ]::before { }`,
			fixed: `[target=_blank]::before { }`,
			description: `a space inside the closing bracket alone, in front of a pseudo-element`,
			message: messages.rejectedClosing,
			line: 1,
			column: 15,
		},
		{
			code: `option[ data-hidden=true] { }`,
			fixed: `option[data-hidden=true] { }`,
			description: `a space inside the opening bracket alone, behind a type selector`,
			message: messages.rejectedOpening,
			line: 1,
			column: 8,
		},
		{
			code: `option[data-hidden=true ] { }`,
			fixed: `option[data-hidden=true] { }`,
			description: `a space inside the closing bracket alone, behind a type selector`,
			message: messages.rejectedClosing,
			line: 1,
			column: 24,
		},
		{
			code: `option[ dataHidden] { }`,
			fixed: `option[dataHidden] { }`,
			description: `a space inside the opening bracket alone, the attribute standing with no value, behind a type selector`,
			message: messages.rejectedOpening,
			line: 1,
			column: 8,
		},
		{
			code: `option[dataHidden ] { }`,
			fixed: `option[dataHidden] { }`,
			description: `a space inside the closing bracket alone, the attribute standing with no value, behind a type selector`,
			message: messages.rejectedClosing,
			line: 1,
			column: 18,
		},
		{
			code: `@media screen and (max-width: 480px) { img[ align=right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			description: `a space inside the opening bracket alone, inside a media query`,
			message: messages.rejectedOpening,
			line: 1,
			column: 44,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align=right ] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			description: `a space inside the closing bracket alone, inside a media query`,
			message: messages.rejectedClosing,
			line: 1,
			column: 55,
		},
		{
			code: `[ target=_blank] .foo { }`,
			fixed: `[target=_blank] .foo { }`,
			description: `a space inside the opening bracket alone, in front of a descendant selector`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target=_blank ] .foo { }`,
			fixed: `[target=_blank] .foo { }`,
			description: `a space inside the closing bracket alone, in front of a descendant selector`,
			message: messages.rejectedClosing,
			line: 1,
			column: 15,
		},
		{
			code: `li[ aria-hidden=false]:nth-child(1) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1) { }`,
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class`,
			message: messages.rejectedOpening,
			line: 1,
			column: 4,
		},
		{
			code: `li[aria-hidden=false ]:nth-child(1) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1) { }`,
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class`,
			message: messages.rejectedClosing,
			line: 1,
			column: 21,
		},
		{
			code: `li[ aria-hidden=false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			message: messages.rejectedOpening,
			line: 1,
			column: 4,
		},
		{
			code: `li[aria-hidden=false ]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			message: messages.rejectedClosing,
			line: 1,
			column: 21,
		},
		{
			code: `ul li[ aria-hidden=false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			description: `a space inside the opening bracket alone of the first attribute selector, no space inside either bracket of the second, the two selectors joined by a sibling combinator`,
			message: messages.rejectedOpening,
			line: 1,
			column: 7,
		},
		{
			code: `ul li[aria-hidden=false ] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			description: `a space inside the closing bracket alone of the first attribute selector, no space inside either bracket of the second, the two selectors joined by a sibling combinator`,
			message: messages.rejectedClosing,
			line: 1,
			column: 24,
		},
		{
			code: `ul li[aria-hidden=false] + li[ aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			description: `no space inside either bracket of the first attribute selector, a space inside the opening bracket alone of the second, the two selectors joined by a sibling combinator`,
			message: messages.rejectedOpening,
			line: 1,
			column: 31,
		},
		{
			code: `ul li[aria-hidden=false] + li[aria-hidden=false ] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			description: `no space inside either bracket of the first attribute selector, a space inside the closing bracket alone of the second, the two selectors joined by a sibling combinator`,
			message: messages.rejectedClosing,
			line: 1,
			column: 48,
		},
		{
			code: `[ target] { content: "[" }`,
			fixed: `[target] { content: "[" }`,
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target ] { content: "[" }`,
			fixed: `[target] { content: "[" }`,
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			message: messages.rejectedClosing,
			line: 1,
			column: 8,
		},
		{
			code: `[ target] { content: "]" }`,
			fixed: `[target] { content: "]" }`,
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[target ] { content: "]" }`,
			fixed: `[target] { content: "]" }`,
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			message: messages.rejectedClosing,
			line: 1,
			column: 8,
		},
		{
			code: `[ foo=bar i] { }`,
			fixed: `[foo=bar i] { }`,
			description: `a space inside the opening bracket alone, a case flag behind the value`,
			message: messages.rejectedOpening,
			line: 1,
			column: 2,
		},
		{
			code: `[foo=bar i ] { }`,
			fixed: `[foo=bar i] { }`,
			description: `a space inside the closing bracket alone, a case flag behind the value`,
			message: messages.rejectedClosing,
			line: 1,
			column: 11,
		},
		{
			code: `img[ alt~=person ][ src*=lorem ] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			description: `a space inside each bracket of either attribute selector`,
			warnings: [
				{
					message: messages.rejectedOpening,
					line: 1,
					column: 5,
				},
				{
					message: messages.rejectedClosing,
					line: 1,
					column: 17,
				},
				{
					message: messages.rejectedOpening,
					line: 1,
					column: 20,
				},
				{
					message: messages.rejectedClosing,
					line: 1,
					column: 31,
				},
			],
		},
		{
			code: `[ /**/foo=bar i ] { }`,
			fixed: `[/**/foo=bar i] { }`,
			description: `a space inside each bracket, a comment opening the brackets, a case flag behind the value`,
			warnings: [
				{
					message: messages.rejectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.rejectedClosing,
					line: 1,
					column: 16,
				},
			],
		},
		{
			code: `[ foo=bar i /**/ ] { }`,
			fixed: `[foo=bar i /**/] { }`,
			description: `a space inside each bracket, a comment closing them, a space in front of it, a case flag behind the value`,
			warnings: [
				{
					message: messages.rejectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.rejectedClosing,
					line: 1,
					column: 17,
				},
			],
		},
		{
			code: `[ foo=bar i/**/ ] { }`,
			fixed: `[foo=bar i/**/] { }`,
			description: `a space inside each bracket, a comment closing them, a case flag behind the value`,
			warnings: [
				{
					message: messages.rejectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.rejectedClosing,
					line: 1,
					column: 16,
				},
			],
		},
		{
			code: `[ foo=bar/**/ ] { }`,
			fixed: `[foo=bar/**/] { }`,
			description: `a space inside each bracket, a comment closing them`,
			warnings: [
				{
					message: messages.rejectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.rejectedClosing,
					line: 1,
					column: 14,
				},
			],
		},
		{
			code: `[ foo/**/ ] { }`,
			fixed: `[foo/**/] { }`,
			description: `a space inside each bracket, the attribute standing with no value, a comment closing them`,
			warnings: [
				{
					message: messages.rejectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.rejectedClosing,
					line: 1,
					column: 10,
				},
			],
		},
	],
})

testRule({
	ruleName,
	config: [`never`],
	customSyntax: `postcss-scss`,

	reject: [
		{
			// https://github.com/stylelint-stylistic/stylelint-stylistic/issues/190
			code: `.a // c\n:not( [ t='y' ] ) {}`,
			fixed: `.a // c\n:not( [t='y'] ) {}`,
			description: `a selector carrying an inline comment, whose fix reaches the copy the file spells, reported in the file's own coordinates`,
			warnings: [
				{
					message: messages.rejectedOpening,
					line: 2,
					column: 9,
				},
				{
					message: messages.rejectedClosing,
					line: 2,
					column: 15,
				},
			],
		},
		{
			code: `[ t='y' ] // c\n{}`,
			fixed: `[t='y'] // c\n{}`,
			description: `the same, with the comment behind the attribute`,
			warnings: [
				{
					message: messages.rejectedOpening,
					line: 1,
					column: 2,
				},
				{
					message: messages.rejectedClosing,
					line: 1,
					column: 8,
				},
			],
		},
	],
})

testRule({
	ruleName,
	config: [`always`],
	customSyntax: `postcss-scss`,

	reject: [
		{
			code: `.a // c\n[t='y'] {}`,
			fixed: `.a // c\n[ t='y' ] {}`,
			description: `a selector carrying an inline comment, spaced out with the comment spelled as the file spells it`,
			warnings: [
				{
					message: messages.expectedOpening,
					line: 2,
					column: 2,
				},
				{
					message: messages.expectedClosing,
					line: 2,
					column: 6,
				},
			],
		},
	],
})
