import { messages, ruleName } from "./index.ts"

let testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`always`],

	accept: [
		{
			// The search took an escaped bracket in the value for the attribute's closing one
			description: `an escaped closing bracket in the value, which is a character of the value and no bracket`,
			code: `[ a=b\\] ] {}`,
		},
		{
			description: `a selector with no attribute in it`,
			code: `.foo { }`,
		},
		{
			description: `a space inside each bracket, the attribute standing with no value`,
			code: `[ target ] { }`,
		},
		{
			description: `two spaces inside each bracket, the attribute standing with no value`,
			code: `[  target  ] { }`,
		},
		{
			description: `a space inside each bracket`,
			code: `[ target=_blank ] { }`,
		},
		{
			description: `two spaces inside each bracket`,
			code: `[  target=_blank  ] { }`,
		},
		{
			description: `a space inside each bracket, the value in apostrophes`,
			code: `[ target='_blank' ] { }`,
		},
		{
			description: `a space inside each bracket, the value in quotation marks`,
			code: `[ target="_blank" ] { }`,
		},
		{
			description: `a space inside each bracket, the whitespace-list operator`,
			code: `[ title~=flower ] { }`,
		},
		{
			description: `a space inside each bracket, the hyphen-list operator`,
			code: `[ title|=flower ] { }`,
		},
		{
			description: `a space inside each bracket, the prefix operator`,
			code: `[ title^=flower ] { }`,
		},
		{
			description: `a space inside each bracket, the suffix operator`,
			code: `[ title$=flower ] { }`,
		},
		{
			description: `a space inside each bracket, the substring operator, behind a type selector`,
			code: `a[ href*=w3schools ] { }`,
		},
		{
			description: `a space inside each bracket of either attribute selector`,
			code: `img[ alt~=person ][ src*=lorem ] { }`,
		},
		{
			description: `a space inside each bracket, in front of a pseudo-class`,
			code: `[ target=_blank ]:hover { }`,
		},
		{
			description: `a space inside each bracket, in front of a pseudo-element`,
			code: `[ target=_blank ]::before { }`,
		},
		{
			description: `a space inside each bracket, behind a type selector`,
			code: `option[ data-hidden=true ] { }`,
		},
		{
			description: `a space inside each bracket, the attribute standing with no value, behind a type selector`,
			code: `option[ dataHidden ] { }`,
		},
		{
			description: `a space inside each bracket, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[ align=right ] {} }`,
		},
		{
			description: `a space inside each bracket, in front of a descendant selector`,
			code: `[ target=_blank ] .foo { }`,
		},
		{
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class`,
			code: `li[ aria-hidden=false ]:nth-child(1) { }`,
		},
		{
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class carrying a space inside its opening parenthesis`,
			code: `li[ aria-hidden=false ]:nth-child( 1) { }`,
		},
		{
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class carrying a space inside its closing parenthesis`,
			code: `li[ aria-hidden=false ]:nth-child(1 ) { }`,
		},
		{
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[ aria-hidden=false ]:nth-child( 1 ) { }`,
		},
		{
			description: `a space inside each bracket of either attribute selector, the two selectors joined by a sibling combinator`,
			code: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
		},
		{
			description: `a space inside each bracket, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[ target ] { content: "[" }`,
		},
		{
			description: `a space inside each bracket, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[ target ] { content: "]" }`,
		},
		{
			description: `a space inside each bracket, a case flag behind the value`,
			code: `[ foo=bar i ] { }`,
		},
		{
			description: `a custom property under the root selector`,
			code: `:root { --foo: 1px; }`,
		},
		{
			description: `a custom property under a type selector`,
			code: `html { --foo: 1px; }`,
		},
		{
			description: `a custom property set under the root selector`,
			code: `:root { --custom-property-set: {} }`,
		},
		{
			description: `a custom property set under a type selector`,
			code: `html { --custom-property-set: {} }`,
		},
		{
			description: `an attribute selector the parser cannot read`,
			code: `a[b=#{c}] { }`,
		},
	],

	reject: [
		{
			// The search took an escaped opening bracket in the name for a bracket, and the fix wrote a space into the name
			description: `an escaped opening bracket in the name, which is a character of the name and no bracket`,
			code: `[a\\[b=c] {}`,
			fixed: `[ a\\[b=c ] {}`,
			warnings: [
				{ line: 1, column: 2, message: messages.expectedOpening },
				{ line: 1, column: 7, message: messages.expectedClosing },
			],
		},
		{
			// The search closed no string at the quotation mark behind an escaped backslash, and the closing bracket passed for the string's text
			description: `no space in front of the closing bracket behind a string ending in an escaped backslash`,
			code: `[ a="b\\\\"] {}`,
			fixed: `[ a="b\\\\" ] {}`,
			line: 1,
			column: 9,
			message: messages.expectedClosing,
		},
		{
			// Pins the run in front of the bracket read over the copy with the escapes masked
			description: `a backslash ending the value in front of a space, which spells a character of the value, leaving no run for the option`,
			code: `[ a=b\\ ] {}`,
			fixed: `[ a=b\\  ] {}`,
			line: 1,
			column: 7,
			message: messages.expectedClosing,
		},
		{
			// Pins the refusal of a write behind a backslash the character it escapes would change behind
			description: `a backslash ending the value in front of a line break and the bracket, where the space would stand behind the backslash as its escaped character, so the warning stands`,
			code: `[ a=b\\\n] {}`,
			fixed: `[ a=b\\\n] {}`,
			line: 1,
			column: 7,
			message: messages.expectedClosing,
		},
		{
			// Pins the attribute passed over and the one beside it fixed all the same: the parser prints the first with a tab in another place and a backslash gone, and every index here is measured in that print
			description: `a backslash in front of a tab twice over inside the value of the first attribute of a list, the second standing with no whitespace inside its brackets`,
			code: `[a=\\\t\\\tb], [c=d] {}`,
			fixed: `[a=\\\t\\\tb], [ c=d ] {}`,
			warnings: [
				{
					line: 1,
					column: 14,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 16,
					message: messages.expectedClosing,
				},
			],
		},
		{
			// Pins the space written in front of the bracket: the run the parser files opens on the tab behind the backslash, so the write over it was refused and the warning stood
			description: `a backslash ending the value in front of a tab, which the parser reads as whitespace of its own and the grammar as a character of the value`,
			code: `[a=b\\\t] {}`,
			fixed: `[ a=b\\\t ] {}`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 6,
					message: messages.expectedClosing,
				},
			],
		},
		{
			// Pins the tab left where it stands: the write took it for the run it was asked for
			description: `a backslash opening the value in front of a tab, the bracket carrying no whitespace at either end`,
			code: `[a=\\\tb] {}`,
			fixed: `[ a=\\\tb ] {}`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 6,
					message: messages.expectedClosing,
				},
			],
		},
		{
			// Pins the run read where it stands rather than at the part the parser picked by `insensitive`, which it sets for a literal `i` alone
			description: `a case flag the parser reads as no insensitivity mark, whose value carries the run the parser files for the closing bracket`,
			code: `[a=b s] {}`,
			fixed: `[ a=b s ] {}`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 6,
					message: messages.expectedClosing,
				},
			],
		},
		{
			// Pins the line break kept: the write went to the run in front of the flag, which is the break, and carried it off
			description: `the same flag standing behind a line break, which is no run of the closing bracket`,
			code: `[a=b\ns] {}`,
			fixed: `[ a=b\ns ] {}`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 2,
					column: 1,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value`,
			code: `[target ] { }`,
			fixed: `[ target ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value`,
			code: `[ target] { }`,
			fixed: `[ target ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedClosing,
		},
		{
			description: `two spaces inside the closing bracket alone, the attribute standing with no value`,
			code: `[target  ] { }`,
			fixed: `[ target  ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `two spaces inside the opening bracket alone, the attribute standing with no value`,
			code: `[  target] { }`,
			fixed: `[  target ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone`,
			code: `[target=_blank ] { }`,
			fixed: `[ target=_blank ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone`,
			code: `[ target=_blank] { }`,
			fixed: `[ target=_blank ] { }`,
			line: 1,
			column: 15,
			message: messages.expectedClosing,
		},
		{
			description: `two spaces inside the closing bracket alone`,
			code: `[target=_blank  ] { }`,
			fixed: `[ target=_blank  ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `two spaces inside the opening bracket alone`,
			code: `[  target=_blank] { }`,
			fixed: `[  target=_blank ] { }`,
			line: 1,
			column: 16,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the value in apostrophes`,
			code: `[target='_blank' ] { }`,
			fixed: `[ target='_blank' ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the value in apostrophes`,
			code: `[ target='_blank'] { }`,
			fixed: `[ target='_blank' ] { }`,
			line: 1,
			column: 17,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the value in quotation marks`,
			code: `[target="_blank" ] { }`,
			fixed: `[ target="_blank" ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the value in quotation marks`,
			code: `[ target="_blank"] { }`,
			fixed: `[ target="_blank" ] { }`,
			line: 1,
			column: 17,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the substring operator, behind a type selector`,
			code: `a[href*=w3schools ] { }`,
			fixed: `a[ href*=w3schools ] { }`,
			line: 1,
			column: 3,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the substring operator, behind a type selector`,
			code: `a[ href*=w3schools] { }`,
			fixed: `a[ href*=w3schools ] { }`,
			line: 1,
			column: 18,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone of the first attribute selector, a space inside each bracket of the second`,
			code: `img[alt~=person ][ src*=lorem ] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			line: 1,
			column: 5,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone of the first attribute selector, a space inside each bracket of the second`,
			code: `img[ alt~=person][ src*=lorem ] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			line: 1,
			column: 16,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside each bracket of the first attribute selector, a space inside the closing bracket alone of the second`,
			code: `img[ alt~=person ][src*=lorem ] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			line: 1,
			column: 20,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside each bracket of the first attribute selector, a space inside the opening bracket alone of the second`,
			code: `img[ alt~=person ][ src*=lorem] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			line: 1,
			column: 30,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, in front of a pseudo-class`,
			code: `[target=_blank ]:hover { }`,
			fixed: `[ target=_blank ]:hover { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, in front of a pseudo-class`,
			code: `[ target=_blank]:hover { }`,
			fixed: `[ target=_blank ]:hover { }`,
			line: 1,
			column: 15,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, in front of a pseudo-element`,
			code: `[target=_blank ]::before { }`,
			fixed: `[ target=_blank ]::before { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, in front of a pseudo-element`,
			code: `[ target=_blank]::before { }`,
			fixed: `[ target=_blank ]::before { }`,
			line: 1,
			column: 15,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector`,
			code: `option[data-hidden=true ] { }`,
			fixed: `option[ data-hidden=true ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector`,
			code: `option[ data-hidden=true] { }`,
			fixed: `option[ data-hidden=true ] { }`,
			line: 1,
			column: 24,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, behind a type selector`,
			code: `option[dataHidden ] { }`,
			fixed: `option[ dataHidden ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, behind a type selector`,
			code: `option[ dataHidden] { }`,
			fixed: `option[ dataHidden ] { }`,
			line: 1,
			column: 18,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align=right ] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[ align=right ] {} }`,
			line: 1,
			column: 44,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[ align=right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[ align=right ] {} }`,
			line: 1,
			column: 55,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, in front of a descendant selector`,
			code: `[target=_blank ] .foo { }`,
			fixed: `[ target=_blank ] .foo { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, in front of a descendant selector`,
			code: `[ target=_blank] .foo { }`,
			fixed: `[ target=_blank ] .foo { }`,
			line: 1,
			column: 15,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false ]:nth-child(1) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child(1) { }`,
			line: 1,
			column: 4,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class`,
			code: `li[ aria-hidden=false]:nth-child(1) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child(1) { }`,
			line: 1,
			column: 21,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[aria-hidden=false ]:nth-child( 1 ) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child( 1 ) { }`,
			line: 1,
			column: 4,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[ aria-hidden=false]:nth-child( 1 ) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child( 1 ) { }`,
			line: 1,
			column: 21,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone of the first attribute selector, a space inside each bracket of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			line: 1,
			column: 7,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone of the first attribute selector, a space inside each bracket of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[ aria-hidden=false] + li[ aria-hidden=false ] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			line: 1,
			column: 24,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside each bracket of the first attribute selector, a space inside the closing bracket alone of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[ aria-hidden=false ] + li[aria-hidden=false ] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			line: 1,
			column: 33,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside each bracket of the first attribute selector, a space inside the opening bracket alone of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[ aria-hidden=false ] + li[ aria-hidden=false] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			line: 1,
			column: 50,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[target ] { content: "[" }`,
			fixed: `[ target ] { content: "[" }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[ target] { content: "[" }`,
			fixed: `[ target ] { content: "[" }`,
			line: 1,
			column: 8,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[target ] { content: "]" }`,
			fixed: `[ target ] { content: "]" }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[ target] { content: "]" }`,
			fixed: `[ target ] { content: "]" }`,
			line: 1,
			column: 8,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, a case flag behind the value`,
			code: `[ foo=bar i] { }`,
			fixed: `[ foo=bar i ] { }`,
			line: 1,
			column: 11,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, a case flag behind the value`,
			code: `[foo=bar i ] { }`,
			fixed: `[ foo=bar i ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `no space inside either bracket of either attribute selector`,
			code: `img[alt~=person][src*=lorem] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			warnings: [
				{
					line: 1,
					column: 5,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 15,
					message: messages.expectedClosing,
				},
				{
					line: 1,
					column: 18,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 27,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `no space inside either bracket, a comment opening the brackets, a case flag behind the value`,
			code: `[/**/foo=bar i] { }`,
			fixed: `[ /**/foo=bar i ] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 14,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `no space inside either bracket, a comment closing them, a space in front of it, a case flag behind the value`,
			code: `[foo=bar i /**/] { }`,
			fixed: `[ foo=bar i /**/ ] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 15,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `no space inside either bracket, a comment closing them, a case flag behind the value`,
			code: `[foo=bar i/**/] { }`,
			fixed: `[ foo=bar i/**/ ] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 14,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `no space inside either bracket, a comment closing them`,
			code: `[foo=bar/**/] { }`,
			fixed: `[ foo=bar/**/ ] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 12,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `no space inside either bracket, the attribute standing with no value, a comment closing them`,
			code: `[foo/**/] { }`,
			fixed: `[ foo/**/ ] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 8,
					message: messages.expectedClosing,
				},
			],
		},
	],
})

testRule({
	ruleName,
	config: [`never`],

	accept: [
		{
			// Pins the run in front of the bracket read over the copy with the escapes masked
			description: `a backslash ending the value in front of a space, which spells a character of the value and no run`,
			code: `[a=b\\ ] {}`,
		},
		{
			description: `a selector with no attribute in it`,
			code: `.foo { }`,
		},
		{
			description: `no space inside either bracket, the attribute standing with no value`,
			code: `[target] { }`,
		},
		{
			description: `no space inside either bracket`,
			code: `[target=_blank] { }`,
		},
		{
			description: `no space inside either bracket, the value in apostrophes`,
			code: `[target='_blank'] { }`,
		},
		{
			description: `no space inside either bracket, the value in quotation marks`,
			code: `[target="_blank"] { }`,
		},
		{
			description: `no space inside either bracket, the whitespace-list operator`,
			code: `[title~=flower] { }`,
		},
		{
			description: `no space inside either bracket, the hyphen-list operator`,
			code: `[title|=flower] { }`,
		},
		{
			description: `no space inside either bracket, the prefix operator`,
			code: `[title^=flower] { }`,
		},
		{
			description: `no space inside either bracket, the suffix operator`,
			code: `[title$=flower] { }`,
		},
		{
			description: `no space inside either bracket, the substring operator, behind a type selector`,
			code: `a[href*=w3schools] { }`,
		},
		{
			description: `no space inside either bracket of either attribute selector`,
			code: `img[alt~=person][src*=lorem] { }`,
		},
		{
			description: `no space inside either bracket, in front of a pseudo-class`,
			code: `[target=_blank]:hover { }`,
		},
		{
			description: `no space inside either bracket, in front of a pseudo-element`,
			code: `[target=_blank]::before { }`,
		},
		{
			description: `no space inside either bracket, behind a type selector`,
			code: `option[data-hidden=true] { }`,
		},
		{
			description: `no space inside either bracket, the attribute standing with no value, behind a type selector`,
			code: `option[dataHidden] { }`,
		},
		{
			description: `no space inside either bracket, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align=right] {} }`,
		},
		{
			description: `no space inside either bracket, in front of a descendant selector`,
			code: `[target=_blank] .foo { }`,
		},
		{
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child(1) { }`,
		},
		{
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class carrying a space inside its opening parenthesis`,
			code: `li[aria-hidden=false]:nth-child( 1) { }`,
		},
		{
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class carrying a space inside its closing parenthesis`,
			code: `li[aria-hidden=false]:nth-child(1 ) { }`,
		},
		{
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[aria-hidden=false]:nth-child( 1 ) { }`,
		},
		{
			description: `no space inside either bracket of either attribute selector, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
		},
		{
			description: `no space inside either bracket, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[target] { content: "[" }`,
		},
		{
			description: `no space inside either bracket, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[target] { content: "]" }`,
		},
		{
			description: `no space inside either bracket, a case flag behind the value`,
			code: `[foo=bar i] { }`,
		},
	],

	reject: [
		{
			// The search took an escaped opening bracket in the value for a bracket, and the fix took the closing bracket away with the run in front of it
			description: `an escaped opening bracket in the value, which is a character of the value and no bracket`,
			code: `[ a=b\\[ ] {}`,
			fixed: `[a=b\\[] {}`,
			warnings: [
				{ line: 1, column: 2, message: messages.rejectedOpening },
				{ line: 1, column: 8, message: messages.rejectedClosing },
			],
		},
		{
			// The search closed no string at the quotation mark behind an escaped backslash, and the closing bracket passed for the string's text
			description: `a space in front of the closing bracket behind a string ending in an escaped backslash`,
			code: `[ a="b\\\\" ] {}`,
			fixed: `[a="b\\\\"] {}`,
			warnings: [
				{ line: 1, column: 2, message: messages.rejectedOpening },
				{ line: 1, column: 10, message: messages.rejectedClosing },
			],
		},
		{
			description: `a space behind an escaped vertical tab in front of the bracket, which the fix takes without touching the escape`,
			code: `[a=b\\\v ] {}`,
			fixed: `[a=b\\\v] {}`,
			line: 1,
			column: 7,
			message: messages.rejectedClosing,
		},
		{
			// Pins the refusal of a write behind a backslash the character it escapes would change behind
			description: `a backslash ending the value in front of a line break and the bracket, which the write would turn into an escaped bracket the file no longer parses, so the warning stands`,
			code: `[a=b\\\n ] {}`,
			fixed: `[a=b\\\n ] {}`,
			line: 2,
			column: 1,
			message: messages.rejectedClosing,
		},
		{
			// Pins the space taken and the tab left: the run the parser files opens on that tab, so the write over it was refused and the warning stood
			description: `a space behind an escaped tab in front of the bracket, which the fix takes without touching the escape`,
			code: `[a=b\\\t ] {}`,
			fixed: `[a=b\\\t] {}`,
			line: 1,
			column: 7,
			message: messages.rejectedClosing,
		},
		{
			// Pins the run read where it stands rather than at the part the parser picked by `insensitive`, which it sets for a literal `i` alone
			description: `a space in front of the bracket behind a case flag the parser reads as no insensitivity mark`,
			code: `[a=b s ] {}`,
			fixed: `[a=b s] {}`,
			line: 1,
			column: 7,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value`,
			code: `[ target] { }`,
			fixed: `[target] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value`,
			code: `[target ] { }`,
			fixed: `[target] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedClosing,
		},
		{
			description: `two spaces inside the opening bracket alone, the attribute standing with no value`,
			code: `[  target] { }`,
			fixed: `[target] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `two spaces inside the closing bracket alone, the attribute standing with no value`,
			code: `[target  ] { }`,
			fixed: `[target] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone`,
			code: `[ target=_blank] { }`,
			fixed: `[target=_blank] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone`,
			code: `[target=_blank ] { }`,
			fixed: `[target=_blank] { }`,
			line: 1,
			column: 15,
			message: messages.rejectedClosing,
		},
		{
			description: `two spaces inside the opening bracket alone`,
			code: `[  target=_blank] { }`,
			fixed: `[target=_blank] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `two spaces inside the closing bracket alone`,
			code: `[target=_blank  ] { }`,
			fixed: `[target=_blank] { }`,
			line: 1,
			column: 16,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the value in apostrophes`,
			code: `[ target='_blank'] { }`,
			fixed: `[target='_blank'] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the value in apostrophes`,
			code: `[target='_blank' ] { }`,
			fixed: `[target='_blank'] { }`,
			line: 1,
			column: 17,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the value in quotation marks`,
			code: `[ target="_blank"] { }`,
			fixed: `[target="_blank"] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the value in quotation marks`,
			code: `[target="_blank" ] { }`,
			fixed: `[target="_blank"] { }`,
			line: 1,
			column: 17,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the substring operator, behind a type selector`,
			code: `a[ href*=w3schools] { }`,
			fixed: `a[href*=w3schools] { }`,
			line: 1,
			column: 3,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the substring operator, behind a type selector`,
			code: `a[href*=w3schools ] { }`,
			fixed: `a[href*=w3schools] { }`,
			line: 1,
			column: 18,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone of the first attribute selector, no space inside either bracket of the second`,
			code: `img[ alt~=person][src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			line: 1,
			column: 5,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone of the first attribute selector, no space inside either bracket of the second`,
			code: `img[alt~=person ][src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			line: 1,
			column: 16,
			message: messages.rejectedClosing,
		},
		{
			description: `no space inside either bracket of the first attribute selector, a space inside the opening bracket alone of the second`,
			code: `img[alt~=person][ src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			line: 1,
			column: 18,
			message: messages.rejectedOpening,
		},
		{
			description: `no space inside either bracket of the first attribute selector, a space inside the closing bracket alone of the second`,
			code: `img[alt~=person][src*=lorem ] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			line: 1,
			column: 28,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, in front of a pseudo-class`,
			code: `[ target=_blank]:hover { }`,
			fixed: `[target=_blank]:hover { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, in front of a pseudo-class`,
			code: `[target=_blank ]:hover { }`,
			fixed: `[target=_blank]:hover { }`,
			line: 1,
			column: 15,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, in front of a pseudo-element`,
			code: `[ target=_blank]::before { }`,
			fixed: `[target=_blank]::before { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, in front of a pseudo-element`,
			code: `[target=_blank ]::before { }`,
			fixed: `[target=_blank]::before { }`,
			line: 1,
			column: 15,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector`,
			code: `option[ data-hidden=true] { }`,
			fixed: `option[data-hidden=true] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector`,
			code: `option[data-hidden=true ] { }`,
			fixed: `option[data-hidden=true] { }`,
			line: 1,
			column: 24,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, behind a type selector`,
			code: `option[ dataHidden] { }`,
			fixed: `option[dataHidden] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, behind a type selector`,
			code: `option[dataHidden ] { }`,
			fixed: `option[dataHidden] { }`,
			line: 1,
			column: 18,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[ align=right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			line: 1,
			column: 44,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align=right ] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			line: 1,
			column: 55,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, in front of a descendant selector`,
			code: `[ target=_blank] .foo { }`,
			fixed: `[target=_blank] .foo { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, in front of a descendant selector`,
			code: `[target=_blank ] .foo { }`,
			fixed: `[target=_blank] .foo { }`,
			line: 1,
			column: 15,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class`,
			code: `li[ aria-hidden=false]:nth-child(1) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1) { }`,
			line: 1,
			column: 4,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false ]:nth-child(1) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1) { }`,
			line: 1,
			column: 21,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[ aria-hidden=false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			line: 1,
			column: 4,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[aria-hidden=false ]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			line: 1,
			column: 21,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone of the first attribute selector, no space inside either bracket of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[ aria-hidden=false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 7,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone of the first attribute selector, no space inside either bracket of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false ] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 24,
			message: messages.rejectedClosing,
		},
		{
			description: `no space inside either bracket of the first attribute selector, a space inside the opening bracket alone of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[ aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 31,
			message: messages.rejectedOpening,
		},
		{
			description: `no space inside either bracket of the first attribute selector, a space inside the closing bracket alone of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden=false ] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 48,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[ target] { content: "[" }`,
			fixed: `[target] { content: "[" }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[target ] { content: "[" }`,
			fixed: `[target] { content: "[" }`,
			line: 1,
			column: 8,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[ target] { content: "]" }`,
			fixed: `[target] { content: "]" }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[target ] { content: "]" }`,
			fixed: `[target] { content: "]" }`,
			line: 1,
			column: 8,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, a case flag behind the value`,
			code: `[ foo=bar i] { }`,
			fixed: `[foo=bar i] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, a case flag behind the value`,
			code: `[foo=bar i ] { }`,
			fixed: `[foo=bar i] { }`,
			line: 1,
			column: 11,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside each bracket of either attribute selector`,
			code: `img[ alt~=person ][ src*=lorem ] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			warnings: [
				{
					line: 1,
					column: 5,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 17,
					message: messages.rejectedClosing,
				},
				{
					line: 1,
					column: 20,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 31,
					message: messages.rejectedClosing,
				},
			],
		},
		{
			description: `a space inside each bracket, a comment opening the brackets, a case flag behind the value`,
			code: `[ /**/foo=bar i ] { }`,
			fixed: `[/**/foo=bar i] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 16,
					message: messages.rejectedClosing,
				},
			],
		},
		{
			description: `a space inside each bracket, a comment closing them, a space in front of it, a case flag behind the value`,
			code: `[ foo=bar i /**/ ] { }`,
			fixed: `[foo=bar i /**/] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 17,
					message: messages.rejectedClosing,
				},
			],
		},
		{
			description: `a space inside each bracket, a comment closing them, a case flag behind the value`,
			code: `[ foo=bar i/**/ ] { }`,
			fixed: `[foo=bar i/**/] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 16,
					message: messages.rejectedClosing,
				},
			],
		},
		{
			description: `a space inside each bracket, a comment closing them`,
			code: `[ foo=bar/**/ ] { }`,
			fixed: `[foo=bar/**/] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 14,
					message: messages.rejectedClosing,
				},
			],
		},
		{
			description: `a space inside each bracket, the attribute standing with no value, a comment closing them`,
			code: `[ foo/**/ ] { }`,
			fixed: `[foo/**/] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 10,
					message: messages.rejectedClosing,
				},
			],
		},
	],
})
