import { messages, ruleName } from "./index.ts"

let testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`always`],

	accept: [
		{
			description: `a selector with no attribute in it`,
			code: `.foo { }`,
		},
		{
			description: `a space inside each bracket, the attribute standing with no value`,
			code: `[ target ] { }`,
		},
		{
			description: `two spaces inside each bracket, the attribute standing with no value`,
			code: `[  target  ] { }`,
		},
		{
			description: `a space inside each bracket`,
			code: `[ target=_blank ] { }`,
		},
		{
			description: `two spaces inside each bracket`,
			code: `[  target=_blank  ] { }`,
		},
		{
			description: `a space inside each bracket, the value in apostrophes`,
			code: `[ target='_blank' ] { }`,
		},
		{
			description: `a space inside each bracket, the value in quotation marks`,
			code: `[ target="_blank" ] { }`,
		},
		{
			description: `a space inside each bracket, the whitespace-list operator`,
			code: `[ title~=flower ] { }`,
		},
		{
			description: `a space inside each bracket, the hyphen-list operator`,
			code: `[ title|=flower ] { }`,
		},
		{
			description: `a space inside each bracket, the prefix operator`,
			code: `[ title^=flower ] { }`,
		},
		{
			description: `a space inside each bracket, the suffix operator`,
			code: `[ title$=flower ] { }`,
		},
		{
			description: `a space inside each bracket, the substring operator, behind a type selector`,
			code: `a[ href*=w3schools ] { }`,
		},
		{
			description: `a space inside each bracket of either attribute selector`,
			code: `img[ alt~=person ][ src*=lorem ] { }`,
		},
		{
			description: `a space inside each bracket, in front of a pseudo-class`,
			code: `[ target=_blank ]:hover { }`,
		},
		{
			description: `a space inside each bracket, in front of a pseudo-element`,
			code: `[ target=_blank ]::before { }`,
		},
		{
			description: `a space inside each bracket, behind a type selector`,
			code: `option[ data-hidden=true ] { }`,
		},
		{
			description: `a space inside each bracket, the attribute standing with no value, behind a type selector`,
			code: `option[ dataHidden ] { }`,
		},
		{
			description: `a space inside each bracket, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[ align=right ] {} }`,
		},
		{
			description: `a space inside each bracket, in front of a descendant selector`,
			code: `[ target=_blank ] .foo { }`,
		},
		{
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class`,
			code: `li[ aria-hidden=false ]:nth-child(1) { }`,
		},
		{
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class carrying a space inside its opening parenthesis`,
			code: `li[ aria-hidden=false ]:nth-child( 1) { }`,
		},
		{
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class carrying a space inside its closing parenthesis`,
			code: `li[ aria-hidden=false ]:nth-child(1 ) { }`,
		},
		{
			description: `a space inside each bracket, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[ aria-hidden=false ]:nth-child( 1 ) { }`,
		},
		{
			description: `a space inside each bracket of either attribute selector, the two selectors joined by a sibling combinator`,
			code: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
		},
		{
			description: `a space inside each bracket, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[ target ] { content: "[" }`,
		},
		{
			description: `a space inside each bracket, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[ target ] { content: "]" }`,
		},
		{
			description: `a space inside each bracket, a case flag behind the value`,
			code: `[ foo=bar i ] { }`,
		},
		{
			description: `a custom property under the root selector`,
			code: `:root { --foo: 1px; }`,
		},
		{
			description: `a custom property under a type selector`,
			code: `html { --foo: 1px; }`,
		},
		{
			description: `a custom property set under the root selector`,
			code: `:root { --custom-property-set: {} }`,
		},
		{
			description: `a custom property set under a type selector`,
			code: `html { --custom-property-set: {} }`,
		},
		{
			description: `an attribute selector the parser cannot read`,
			code: `a[b=#{c}] { }`,
		},
	],

	reject: [
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value`,
			code: `[target ] { }`,
			fixed: `[ target ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value`,
			code: `[ target] { }`,
			fixed: `[ target ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedClosing,
		},
		{
			description: `two spaces inside the closing bracket alone, the attribute standing with no value`,
			code: `[target  ] { }`,
			fixed: `[ target  ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `two spaces inside the opening bracket alone, the attribute standing with no value`,
			code: `[  target] { }`,
			fixed: `[  target ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone`,
			code: `[target=_blank ] { }`,
			fixed: `[ target=_blank ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone`,
			code: `[ target=_blank] { }`,
			fixed: `[ target=_blank ] { }`,
			line: 1,
			column: 15,
			message: messages.expectedClosing,
		},
		{
			description: `two spaces inside the closing bracket alone`,
			code: `[target=_blank  ] { }`,
			fixed: `[ target=_blank  ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `two spaces inside the opening bracket alone`,
			code: `[  target=_blank] { }`,
			fixed: `[  target=_blank ] { }`,
			line: 1,
			column: 16,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the value in apostrophes`,
			code: `[target='_blank' ] { }`,
			fixed: `[ target='_blank' ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the value in apostrophes`,
			code: `[ target='_blank'] { }`,
			fixed: `[ target='_blank' ] { }`,
			line: 1,
			column: 17,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the value in quotation marks`,
			code: `[target="_blank" ] { }`,
			fixed: `[ target="_blank" ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the value in quotation marks`,
			code: `[ target="_blank"] { }`,
			fixed: `[ target="_blank" ] { }`,
			line: 1,
			column: 17,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the substring operator, behind a type selector`,
			code: `a[href*=w3schools ] { }`,
			fixed: `a[ href*=w3schools ] { }`,
			line: 1,
			column: 3,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the substring operator, behind a type selector`,
			code: `a[ href*=w3schools] { }`,
			fixed: `a[ href*=w3schools ] { }`,
			line: 1,
			column: 18,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone of the first attribute selector, a space inside each bracket of the second`,
			code: `img[alt~=person ][ src*=lorem ] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			line: 1,
			column: 5,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone of the first attribute selector, a space inside each bracket of the second`,
			code: `img[ alt~=person][ src*=lorem ] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			line: 1,
			column: 16,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside each bracket of the first attribute selector, a space inside the closing bracket alone of the second`,
			code: `img[ alt~=person ][src*=lorem ] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			line: 1,
			column: 20,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside each bracket of the first attribute selector, a space inside the opening bracket alone of the second`,
			code: `img[ alt~=person ][ src*=lorem] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			line: 1,
			column: 30,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, in front of a pseudo-class`,
			code: `[target=_blank ]:hover { }`,
			fixed: `[ target=_blank ]:hover { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, in front of a pseudo-class`,
			code: `[ target=_blank]:hover { }`,
			fixed: `[ target=_blank ]:hover { }`,
			line: 1,
			column: 15,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, in front of a pseudo-element`,
			code: `[target=_blank ]::before { }`,
			fixed: `[ target=_blank ]::before { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, in front of a pseudo-element`,
			code: `[ target=_blank]::before { }`,
			fixed: `[ target=_blank ]::before { }`,
			line: 1,
			column: 15,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector`,
			code: `option[data-hidden=true ] { }`,
			fixed: `option[ data-hidden=true ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector`,
			code: `option[ data-hidden=true] { }`,
			fixed: `option[ data-hidden=true ] { }`,
			line: 1,
			column: 24,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, behind a type selector`,
			code: `option[dataHidden ] { }`,
			fixed: `option[ dataHidden ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, behind a type selector`,
			code: `option[ dataHidden] { }`,
			fixed: `option[ dataHidden ] { }`,
			line: 1,
			column: 18,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align=right ] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[ align=right ] {} }`,
			line: 1,
			column: 44,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[ align=right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[ align=right ] {} }`,
			line: 1,
			column: 55,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, in front of a descendant selector`,
			code: `[target=_blank ] .foo { }`,
			fixed: `[ target=_blank ] .foo { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, in front of a descendant selector`,
			code: `[ target=_blank] .foo { }`,
			fixed: `[ target=_blank ] .foo { }`,
			line: 1,
			column: 15,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false ]:nth-child(1) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child(1) { }`,
			line: 1,
			column: 4,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class`,
			code: `li[ aria-hidden=false]:nth-child(1) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child(1) { }`,
			line: 1,
			column: 21,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[aria-hidden=false ]:nth-child( 1 ) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child( 1 ) { }`,
			line: 1,
			column: 4,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[ aria-hidden=false]:nth-child( 1 ) { }`,
			fixed: `li[ aria-hidden=false ]:nth-child( 1 ) { }`,
			line: 1,
			column: 21,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone of the first attribute selector, a space inside each bracket of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			line: 1,
			column: 7,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone of the first attribute selector, a space inside each bracket of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[ aria-hidden=false] + li[ aria-hidden=false ] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			line: 1,
			column: 24,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside each bracket of the first attribute selector, a space inside the closing bracket alone of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[ aria-hidden=false ] + li[aria-hidden=false ] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			line: 1,
			column: 33,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside each bracket of the first attribute selector, a space inside the opening bracket alone of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[ aria-hidden=false ] + li[ aria-hidden=false] a { }`,
			fixed: `ul li[ aria-hidden=false ] + li[ aria-hidden=false ] a { }`,
			line: 1,
			column: 50,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[target ] { content: "[" }`,
			fixed: `[ target ] { content: "[" }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[ target] { content: "[" }`,
			fixed: `[ target ] { content: "[" }`,
			line: 1,
			column: 8,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[target ] { content: "]" }`,
			fixed: `[ target ] { content: "]" }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[ target] { content: "]" }`,
			fixed: `[ target ] { content: "]" }`,
			line: 1,
			column: 8,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, a case flag behind the value`,
			code: `[ foo=bar i] { }`,
			fixed: `[ foo=bar i ] { }`,
			line: 1,
			column: 11,
			message: messages.expectedClosing,
		},
		{
			description: `a space inside the closing bracket alone, a case flag behind the value`,
			code: `[foo=bar i ] { }`,
			fixed: `[ foo=bar i ] { }`,
			line: 1,
			column: 2,
			message: messages.expectedOpening,
		},
		{
			description: `no space inside either bracket of either attribute selector`,
			code: `img[alt~=person][src*=lorem] { }`,
			fixed: `img[ alt~=person ][ src*=lorem ] { }`,
			warnings: [
				{
					line: 1,
					column: 5,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 15,
					message: messages.expectedClosing,
				},
				{
					line: 1,
					column: 18,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 27,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `no space inside either bracket, a comment opening the brackets, a case flag behind the value`,
			code: `[/**/foo=bar i] { }`,
			fixed: `[ /**/foo=bar i ] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 14,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `no space inside either bracket, a comment closing them, a space in front of it, a case flag behind the value`,
			code: `[foo=bar i /**/] { }`,
			fixed: `[ foo=bar i /**/ ] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 15,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `no space inside either bracket, a comment closing them, a case flag behind the value`,
			code: `[foo=bar i/**/] { }`,
			fixed: `[ foo=bar i/**/ ] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 14,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `no space inside either bracket, a comment closing them`,
			code: `[foo=bar/**/] { }`,
			fixed: `[ foo=bar/**/ ] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 12,
					message: messages.expectedClosing,
				},
			],
		},
		{
			description: `no space inside either bracket, the attribute standing with no value, a comment closing them`,
			code: `[foo/**/] { }`,
			fixed: `[ foo/**/ ] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.expectedOpening,
				},
				{
					line: 1,
					column: 8,
					message: messages.expectedClosing,
				},
			],
		},
	],
})

testRule({
	ruleName,
	config: [`never`],

	accept: [
		{
			description: `a selector with no attribute in it`,
			code: `.foo { }`,
		},
		{
			description: `no space inside either bracket, the attribute standing with no value`,
			code: `[target] { }`,
		},
		{
			description: `no space inside either bracket`,
			code: `[target=_blank] { }`,
		},
		{
			description: `no space inside either bracket, the value in apostrophes`,
			code: `[target='_blank'] { }`,
		},
		{
			description: `no space inside either bracket, the value in quotation marks`,
			code: `[target="_blank"] { }`,
		},
		{
			description: `no space inside either bracket, the whitespace-list operator`,
			code: `[title~=flower] { }`,
		},
		{
			description: `no space inside either bracket, the hyphen-list operator`,
			code: `[title|=flower] { }`,
		},
		{
			description: `no space inside either bracket, the prefix operator`,
			code: `[title^=flower] { }`,
		},
		{
			description: `no space inside either bracket, the suffix operator`,
			code: `[title$=flower] { }`,
		},
		{
			description: `no space inside either bracket, the substring operator, behind a type selector`,
			code: `a[href*=w3schools] { }`,
		},
		{
			description: `no space inside either bracket of either attribute selector`,
			code: `img[alt~=person][src*=lorem] { }`,
		},
		{
			description: `no space inside either bracket, in front of a pseudo-class`,
			code: `[target=_blank]:hover { }`,
		},
		{
			description: `no space inside either bracket, in front of a pseudo-element`,
			code: `[target=_blank]::before { }`,
		},
		{
			description: `no space inside either bracket, behind a type selector`,
			code: `option[data-hidden=true] { }`,
		},
		{
			description: `no space inside either bracket, the attribute standing with no value, behind a type selector`,
			code: `option[dataHidden] { }`,
		},
		{
			description: `no space inside either bracket, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align=right] {} }`,
		},
		{
			description: `no space inside either bracket, in front of a descendant selector`,
			code: `[target=_blank] .foo { }`,
		},
		{
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child(1) { }`,
		},
		{
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class carrying a space inside its opening parenthesis`,
			code: `li[aria-hidden=false]:nth-child( 1) { }`,
		},
		{
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class carrying a space inside its closing parenthesis`,
			code: `li[aria-hidden=false]:nth-child(1 ) { }`,
		},
		{
			description: `no space inside either bracket, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[aria-hidden=false]:nth-child( 1 ) { }`,
		},
		{
			description: `no space inside either bracket of either attribute selector, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
		},
		{
			description: `no space inside either bracket, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[target] { content: "[" }`,
		},
		{
			description: `no space inside either bracket, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[target] { content: "]" }`,
		},
		{
			description: `no space inside either bracket, a case flag behind the value`,
			code: `[foo=bar i] { }`,
		},
	],

	reject: [
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value`,
			code: `[ target] { }`,
			fixed: `[target] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value`,
			code: `[target ] { }`,
			fixed: `[target] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedClosing,
		},
		{
			description: `two spaces inside the opening bracket alone, the attribute standing with no value`,
			code: `[  target] { }`,
			fixed: `[target] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `two spaces inside the closing bracket alone, the attribute standing with no value`,
			code: `[target  ] { }`,
			fixed: `[target] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone`,
			code: `[ target=_blank] { }`,
			fixed: `[target=_blank] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone`,
			code: `[target=_blank ] { }`,
			fixed: `[target=_blank] { }`,
			line: 1,
			column: 15,
			message: messages.rejectedClosing,
		},
		{
			description: `two spaces inside the opening bracket alone`,
			code: `[  target=_blank] { }`,
			fixed: `[target=_blank] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `two spaces inside the closing bracket alone`,
			code: `[target=_blank  ] { }`,
			fixed: `[target=_blank] { }`,
			line: 1,
			column: 16,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the value in apostrophes`,
			code: `[ target='_blank'] { }`,
			fixed: `[target='_blank'] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the value in apostrophes`,
			code: `[target='_blank' ] { }`,
			fixed: `[target='_blank'] { }`,
			line: 1,
			column: 17,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the value in quotation marks`,
			code: `[ target="_blank"] { }`,
			fixed: `[target="_blank"] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the value in quotation marks`,
			code: `[target="_blank" ] { }`,
			fixed: `[target="_blank"] { }`,
			line: 1,
			column: 17,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the substring operator, behind a type selector`,
			code: `a[ href*=w3schools] { }`,
			fixed: `a[href*=w3schools] { }`,
			line: 1,
			column: 3,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the substring operator, behind a type selector`,
			code: `a[href*=w3schools ] { }`,
			fixed: `a[href*=w3schools] { }`,
			line: 1,
			column: 18,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone of the first attribute selector, no space inside either bracket of the second`,
			code: `img[ alt~=person][src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			line: 1,
			column: 5,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone of the first attribute selector, no space inside either bracket of the second`,
			code: `img[alt~=person ][src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			line: 1,
			column: 16,
			message: messages.rejectedClosing,
		},
		{
			description: `no space inside either bracket of the first attribute selector, a space inside the opening bracket alone of the second`,
			code: `img[alt~=person][ src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			line: 1,
			column: 18,
			message: messages.rejectedOpening,
		},
		{
			description: `no space inside either bracket of the first attribute selector, a space inside the closing bracket alone of the second`,
			code: `img[alt~=person][src*=lorem ] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			line: 1,
			column: 28,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, in front of a pseudo-class`,
			code: `[ target=_blank]:hover { }`,
			fixed: `[target=_blank]:hover { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, in front of a pseudo-class`,
			code: `[target=_blank ]:hover { }`,
			fixed: `[target=_blank]:hover { }`,
			line: 1,
			column: 15,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, in front of a pseudo-element`,
			code: `[ target=_blank]::before { }`,
			fixed: `[target=_blank]::before { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, in front of a pseudo-element`,
			code: `[target=_blank ]::before { }`,
			fixed: `[target=_blank]::before { }`,
			line: 1,
			column: 15,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector`,
			code: `option[ data-hidden=true] { }`,
			fixed: `option[data-hidden=true] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector`,
			code: `option[data-hidden=true ] { }`,
			fixed: `option[data-hidden=true] { }`,
			line: 1,
			column: 24,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, behind a type selector`,
			code: `option[ dataHidden] { }`,
			fixed: `option[dataHidden] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, behind a type selector`,
			code: `option[dataHidden ] { }`,
			fixed: `option[dataHidden] { }`,
			line: 1,
			column: 18,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[ align=right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			line: 1,
			column: 44,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align=right ] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			line: 1,
			column: 55,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, in front of a descendant selector`,
			code: `[ target=_blank] .foo { }`,
			fixed: `[target=_blank] .foo { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, in front of a descendant selector`,
			code: `[target=_blank ] .foo { }`,
			fixed: `[target=_blank] .foo { }`,
			line: 1,
			column: 15,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class`,
			code: `li[ aria-hidden=false]:nth-child(1) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1) { }`,
			line: 1,
			column: 4,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false ]:nth-child(1) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1) { }`,
			line: 1,
			column: 21,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[ aria-hidden=false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			line: 1,
			column: 4,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, behind a type selector, in front of a pseudo-class carrying spaces inside both of its parentheses`,
			code: `li[aria-hidden=false ]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			line: 1,
			column: 21,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone of the first attribute selector, no space inside either bracket of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[ aria-hidden=false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 7,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone of the first attribute selector, no space inside either bracket of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false ] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 24,
			message: messages.rejectedClosing,
		},
		{
			description: `no space inside either bracket of the first attribute selector, a space inside the opening bracket alone of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[ aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 31,
			message: messages.rejectedOpening,
		},
		{
			description: `no space inside either bracket of the first attribute selector, a space inside the closing bracket alone of the second, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden=false ] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 48,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[ target] { content: "[" }`,
			fixed: `[target] { content: "[" }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying an opening bracket in its value`,
			code: `[target ] { content: "[" }`,
			fixed: `[target] { content: "[" }`,
			line: 1,
			column: 8,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[ target] { content: "]" }`,
			fixed: `[target] { content: "]" }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, the attribute standing with no value, the declaration below carrying a closing bracket in its value`,
			code: `[target ] { content: "]" }`,
			fixed: `[target] { content: "]" }`,
			line: 1,
			column: 8,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside the opening bracket alone, a case flag behind the value`,
			code: `[ foo=bar i] { }`,
			fixed: `[foo=bar i] { }`,
			line: 1,
			column: 2,
			message: messages.rejectedOpening,
		},
		{
			description: `a space inside the closing bracket alone, a case flag behind the value`,
			code: `[foo=bar i ] { }`,
			fixed: `[foo=bar i] { }`,
			line: 1,
			column: 11,
			message: messages.rejectedClosing,
		},
		{
			description: `a space inside each bracket of either attribute selector`,
			code: `img[ alt~=person ][ src*=lorem ] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			warnings: [
				{
					line: 1,
					column: 5,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 17,
					message: messages.rejectedClosing,
				},
				{
					line: 1,
					column: 20,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 31,
					message: messages.rejectedClosing,
				},
			],
		},
		{
			description: `a space inside each bracket, a comment opening the brackets, a case flag behind the value`,
			code: `[ /**/foo=bar i ] { }`,
			fixed: `[/**/foo=bar i] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 16,
					message: messages.rejectedClosing,
				},
			],
		},
		{
			description: `a space inside each bracket, a comment closing them, a space in front of it, a case flag behind the value`,
			code: `[ foo=bar i /**/ ] { }`,
			fixed: `[foo=bar i /**/] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 17,
					message: messages.rejectedClosing,
				},
			],
		},
		{
			description: `a space inside each bracket, a comment closing them, a case flag behind the value`,
			code: `[ foo=bar i/**/ ] { }`,
			fixed: `[foo=bar i/**/] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 16,
					message: messages.rejectedClosing,
				},
			],
		},
		{
			description: `a space inside each bracket, a comment closing them`,
			code: `[ foo=bar/**/ ] { }`,
			fixed: `[foo=bar/**/] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 14,
					message: messages.rejectedClosing,
				},
			],
		},
		{
			description: `a space inside each bracket, the attribute standing with no value, a comment closing them`,
			code: `[ foo/**/ ] { }`,
			fixed: `[foo/**/] { }`,
			warnings: [
				{
					line: 1,
					column: 2,
					message: messages.rejectedOpening,
				},
				{
					line: 1,
					column: 10,
					message: messages.rejectedClosing,
				},
			],
		},
	],
})
