/**
 * Every rule of the plugin, and every primary option it accepts.
 *
 * The list is written out rather than read off the source, so that a run of an oracle over an older commit is comparable with a run over a newer one. A rule gaining an option gains a line here in the same commit.
 */
const RULE_OPTIONS = {
	"aspect-ratio-notation": [`ratio`, `number-where-possible`, `as-written`],
	"at-rule-name-case": [`lower`, `upper`],
	"at-rule-name-newline-after": [`always`, `always-multi-line`],
	"at-rule-name-space-after": [`always`, `always-single-line`],
	"at-rule-semicolon-newline-after": [`always`],
	"at-rule-semicolon-space-before": [`always`, `never`],
	"block-closing-brace-empty-line-before": [`always-multi-line`, `never`],
	"block-closing-brace-newline-after": [`always`, `always-single-line`, `never-single-line`, `always-multi-line`, `never-multi-line`],
	"block-closing-brace-newline-before": [`always`, `always-multi-line`, `never-multi-line`],
	"block-closing-brace-space-after": [`always`, `never`, `always-single-line`, `never-single-line`, `always-multi-line`, `never-multi-line`],
	"block-closing-brace-space-before": [`always`, `never`, `always-single-line`, `never-single-line`, `always-multi-line`, `never-multi-line`],
	"block-opening-brace-newline-after": [`always`, `always-multi-line`, `never-multi-line`],
	"block-opening-brace-newline-before": [`always`, `always-single-line`, `never-single-line`, `always-multi-line`, `never-multi-line`],
	"block-opening-brace-space-after": [`always`, `never`, `always-single-line`, `never-single-line`, `always-multi-line`, `never-multi-line`],
	"block-opening-brace-space-before": [`always`, `never`, `always-single-line`, `never-single-line`, `always-multi-line`, `never-multi-line`],
	"color-hex-case": [`lower`, `upper`],
	"declaration-bang-space-after": [`always`, `never`],
	"declaration-bang-space-before": [`always`, `never`],
	"declaration-block-semicolon-newline-after": [`always`, `always-multi-line`, `never-multi-line`],
	"declaration-block-semicolon-newline-before": [`always`, `always-multi-line`, `never-multi-line`],
	"declaration-block-semicolon-space-after": [`always`, `never`, `always-single-line`, `never-single-line`],
	"declaration-block-semicolon-space-before": [`always`, `never`, `always-single-line`, `never-single-line`],
	"declaration-block-trailing-semicolon": [`always`, `never`],
	"declaration-colon-newline-after": [`always`, `always-multi-line`],
	"declaration-colon-space-after": [`always`, `never`, `always-single-line`],
	"declaration-colon-space-before": [`always`, `never`],
	"function-comma-newline-after": [`always`, `always-multi-line`, `never-multi-line`],
	"function-comma-newline-before": [`always`, `always-multi-line`, `never-multi-line`],
	"function-comma-space-after": [`always`, `never`, `always-single-line`, `never-single-line`],
	"function-comma-space-before": [`always`, `never`, `always-single-line`, `never-single-line`],
	"function-max-empty-lines": [0, 1],
	"function-parentheses-newline-inside": [`always`, `always-multi-line`, `never-multi-line`],
	"function-parentheses-space-inside": [`always`, `never`, `always-single-line`, `never-single-line`],
	"function-whitespace-after": [`always`, `never`],
	"indentation": [`tab`, 2],
	"linebreaks": [`unix`, `windows`],
	"max-empty-lines": [1, 2],
	"max-line-length": [20, 40],
	"media-feature-colon-space-after": [`always`, `never`],
	"media-feature-colon-space-before": [`always`, `never`],
	"media-feature-name-case": [`lower`, `upper`],
	"media-feature-parentheses-space-inside": [`always`, `never`],
	"media-feature-range-operator-space-after": [`always`, `never`],
	"media-feature-range-operator-space-before": [`always`, `never`],
	"media-query-list-comma-newline-after": [`always`, `always-multi-line`, `never-multi-line`],
	"media-query-list-comma-newline-before": [`always`, `always-multi-line`, `never-multi-line`],
	"media-query-list-comma-space-after": [`always`, `never`, `always-single-line`, `never-single-line`],
	"media-query-list-comma-space-before": [`always`, `never`, `always-single-line`, `never-single-line`],
	"named-grid-areas-alignment": [true],
	"no-empty-first-line": [true],
	"no-eol-whitespace": [true],
	"no-extra-semicolons": [true],
	"no-missing-end-of-source-newline": [true],
	"no-multiple-whitespaces": [true],
	"number-leading-zero": [`always`, `never`],
	"number-no-trailing-zeros": [true],
	"property-case": [`lower`, `upper`],
	"selector-attribute-brackets-space-inside": [`always`, `never`],
	"selector-attribute-operator-space-after": [`always`, `never`],
	"selector-attribute-operator-space-before": [`always`, `never`],
	"selector-combinator-space-after": [`always`, `never`],
	"selector-combinator-space-before": [`always`, `never`],
	"selector-descendant-combinator-no-non-space": [true],
	"selector-list-comma-newline-after": [`always`, `always-multi-line`, `never-multi-line`],
	"selector-list-comma-newline-before": [`always`, `always-multi-line`, `never-multi-line`],
	"selector-list-comma-space-after": [`always`, `never`, `always-single-line`, `never-single-line`],
	"selector-list-comma-space-before": [`always`, `never`, `always-single-line`, `never-single-line`],
	"selector-max-empty-lines": [0, 1],
	"selector-pseudo-class-case": [`lower`, `upper`],
	"selector-pseudo-class-parentheses-space-inside": [`always`, `never`],
	"selector-pseudo-element-case": [`lower`, `upper`],
	"string-quotes": [`single`, `double`],
	"unicode-bom": [`always`, `never`],
	"unit-case": [`lower`, `upper`],
	"value-list-comma-newline-after": [`always`, `always-multi-line`, `never-multi-line`],
	"value-list-comma-newline-before": [`always`, `always-multi-line`, `never-multi-line`],
	"value-list-comma-space-after": [`always`, `never`, `always-single-line`, `never-single-line`],
	"value-list-comma-space-before": [`always`, `never`, `always-single-line`, `never-single-line`],
	"value-list-max-empty-lines": [0, 1],
}

export { RULE_OPTIONS }
