import { messages, ruleName } from "./index.ts"

let testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`always`],

	accept: [
		{
			description: `a selector with no attribute in it`,
			code: `.foo {}`,
		},
		{
			description: `an attribute selector with no value`,
			code: `[target] {}`,
		},
		{
			description: `an attribute selector with no value, a space inside the opening bracket`,
			code: `[ target] {}`,
		},
		{
			description: `an attribute selector with no value, a space inside the closing bracket`,
			code: `[target ] {}`,
		},
		{
			description: `an attribute selector with no value, spaces inside both brackets`,
			code: `[ target ] {}`,
		},
		{
			description: `a space after the equals operator`,
			code: `[target= _blank] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it`,
			code: `[target = _blank] {}`,
		},
		{
			description: `a space after the equals operator, a space inside the closing bracket`,
			code: `[target= _blank ] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it and a space inside the closing bracket`,
			code: `[target = _blank ] {}`,
		},
		{
			description: `a space after the equals operator, a space inside the opening bracket`,
			code: `[ target= _blank] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it and a space inside the opening bracket`,
			code: `[ target = _blank] {}`,
		},
		{
			description: `a space after the equals operator, spaces inside both brackets`,
			code: `[ target= _blank ] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it and spaces inside both brackets`,
			code: `[ target = _blank ] {}`,
		},
		{
			description: `a space after the equals operator, the value in apostrophes`,
			code: `[target= '_blank'] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it and the value in apostrophes`,
			code: `[target = '_blank'] {}`,
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space opening it`,
			code: `[target= ' _blank'] {}`,
		},
		{
			description: `a space after the equals operator, the value in apostrophes and a space inside the closing bracket`,
			code: `[target= '_blank' ] {}`,
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space closing it`,
			code: `[target= '_blank '] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in apostrophes and a space inside the closing bracket`,
			code: `[target = '_blank' ] {}`,
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space at each end of it`,
			code: `[target= ' _blank '] {}`,
		},
		{
			description: `a space after the equals operator, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target= '_blank'] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target = '_blank'] {}`,
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
			code: `[ target= ' _blank'] {}`,
		},
		{
			description: `a space after the equals operator, the value in apostrophes and spaces inside both brackets`,
			code: `[ target= '_blank' ] {}`,
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
			code: `[ target= '_blank '] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in apostrophes and spaces inside both brackets`,
			code: `[ target = '_blank' ] {}`,
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
			code: `[ target= ' _blank '] {}`,
		},
		{
			description: `a space after the equals operator, the value in quotation marks`,
			code: `[target= "_blank"] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it and the value in quotation marks`,
			code: `[target = "_blank"] {}`,
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space opening it`,
			code: `[target= " _blank"] {}`,
		},
		{
			description: `a space after the equals operator, the value in quotation marks and a space inside the closing bracket`,
			code: `[target= "_blank" ] {}`,
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space closing it`,
			code: `[target= "_blank "] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in quotation marks and a space inside the closing bracket`,
			code: `[target = "_blank" ] {}`,
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space at each end of it`,
			code: `[target= " _blank "] {}`,
		},
		{
			description: `a space after the equals operator, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target= "_blank"] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target = "_blank"] {}`,
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
			code: `[ target= " _blank"] {}`,
		},
		{
			description: `a space after the equals operator, the value in quotation marks and spaces inside both brackets`,
			code: `[ target= "_blank" ] {}`,
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
			code: `[ target= "_blank "] {}`,
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in quotation marks and spaces inside both brackets`,
			code: `[ target = "_blank" ] {}`,
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
			code: `[ target= " _blank "] {}`,
		},
		{
			description: `a space after the whitespace-list operator`,
			code: `[title~= flower] { }`,
		},
		{
			description: `a space after the whitespace-list operator, a space in front of it`,
			code: `[title ~= flower] { }`,
		},
		{
			description: `a space after the hyphen-list operator`,
			code: `[title|= flower] { }`,
		},
		{
			description: `a space after the hyphen-list operator, a space in front of it`,
			code: `[title |= flower] { }`,
		},
		{
			description: `a space after the prefix operator`,
			code: `[title^= flower] { }`,
		},
		{
			description: `a space after the prefix operator, a space in front of it`,
			code: `[title ^= flower] { }`,
		},
		{
			description: `a space after the suffix operator`,
			code: `[title$= flower] { }`,
		},
		{
			description: `a space after the suffix operator, a space in front of it`,
			code: `[title $= flower] { }`,
		},
		{
			description: `a space after the substring operator, behind a type selector`,
			code: `a[href*= w3schools] { }`,
		},
		{
			description: `a space after the substring operator, a space in front of it, behind a type selector`,
			code: `a[href *= w3schools] { }`,
		},
		{
			description: `a space after the operator of each of the two attribute selectors`,
			code: `img[alt~= person][src*= lorem] { }`,
		},
		{
			description: `a space after the operator of each of the two attribute selectors, a space in front of the first's`,
			code: `img[alt ~= person][src*= lorem] { }`,
		},
		{
			description: `a space after the operator of each of the two attribute selectors, a space in front of the second's`,
			code: `img[alt~= person][src *= lorem] { }`,
		},
		{
			description: `a space after the operator of each of the two attribute selectors, a space in front of each of them`,
			code: `img[alt ~= person][src *= lorem] { }`,
		},
		{
			description: `a space after the equals operator, in front of a pseudo-class`,
			code: `[target= _blank]:hover { }`,
		},
		{
			description: `a space after the equals operator, a space in front of it, in front of a pseudo-class`,
			code: `[target = _blank]:hover { }`,
		},
		{
			description: `a space after the equals operator, in front of a pseudo-element`,
			code: `[target= _blank]::before { }`,
		},
		{
			description: `a space after the equals operator, a space in front of it, in front of a pseudo-element`,
			code: `[target = _blank]::before { }`,
		},
		{
			description: `a space after the equals operator, behind a type selector`,
			code: `option[data-hidden= true] { }`,
		},
		{
			description: `a space after the equals operator, a space in front of it, behind a type selector`,
			code: `option[data-hidden = true] { }`,
		},
		{
			description: `an attribute selector with no value, behind a type selector`,
			code: `option[dataHidden] { }`,
		},
		{
			description: `a space after the equals operator, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align= right] {} }`,
		},
		{
			description: `a space after the equals operator, a space in front of it, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align = right] {} }`,
		},
		{
			description: `a space after the equals operator, in front of a descendant selector`,
			code: `[target= _blank] .foo { }`,
		},
		{
			description: `a space after the equals operator, a space in front of it, in front of a descendant selector`,
			code: `[target = _blank] .foo { }`,
		},
		{
			description: `a space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child(1) { }`,
		},
		{
			description: `a space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child( 1) { }`,
		},
		{
			description: `a space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child(1 ) { }`,
		},
		{
			description: `a space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child( 1 ) { }`,
		},
		{
			description: `a space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child(1) { }`,
		},
		{
			description: `a space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child( 1) { }`,
		},
		{
			description: `a space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child(1 ) { }`,
		},
		{
			description: `a space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child( 1 ) { }`,
		},
		{
			description: `a space after the operator of each of the two attribute selectors, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
		},
		{
			description: `a space after the operator of each of the two attribute selectors, a space in front of the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden= false] a { }`,
		},
		{
			description: `a space after the operator of each of the two attribute selectors, a space in front of the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden = false] a { }`,
		},
		{
			description: `a space after the operator of each of the two attribute selectors, a space in front of each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
		},
		{
			description: `an attribute selector with no value, in a rule that carries a declaration`,
			code: `[target] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, a space inside the closing bracket, in a rule that carries a declaration`,
			code: `[target ] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, a space inside the opening bracket, in a rule that carries a declaration`,
			code: `[ target] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, spaces inside both brackets, in a rule that carries a declaration`,
			code: `[ target ] { content: " " }`,
		},
		{
			description: `a custom property under the root selector`,
			code: `:root { --foo: 1px; }`,
		},
		{
			description: `a custom property under a type selector`,
			code: `html { --foo: 1px; }`,
		},
		{
			description: `a custom property set under the root selector`,
			code: `:root { --custom-property-set: {} }`,
		},
		{
			description: `a custom property set under a type selector`,
			code: `html { --custom-property-set: {} }`,
		},
		{
			description: `no space after the equals operator, behind a type selector`,
			code: `a[b=#{c}] { }`,
		},
	],

	reject: [
		{
			description: `no space after the equals operator`,
			code: `[target=_blank] { }`,
			fixed: `[target= _blank] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it`,
			code: `[target =_blank] { }`,
			fixed: `[target = _blank] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space inside the closing bracket`,
			code: `[target=_blank ] { }`,
			fixed: `[target= _blank ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it and a space inside the closing bracket`,
			code: `[target =_blank ] { }`,
			fixed: `[target = _blank ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space inside the opening bracket`,
			code: `[ target=_blank] { }`,
			fixed: `[ target= _blank] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it and a space inside the opening bracket`,
			code: `[ target =_blank] { }`,
			fixed: `[ target = _blank] { }`,
			line: 1,
			column: 10,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, spaces inside both brackets`,
			code: `[ target=_blank ] { }`,
			fixed: `[ target= _blank ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it and spaces inside both brackets`,
			code: `[ target =_blank ] { }`,
			fixed: `[ target = _blank ] { }`,
			line: 1,
			column: 10,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in apostrophes`,
			code: `[target='_blank'] { }`,
			fixed: `[target= '_blank'] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it and the value in apostrophes`,
			code: `[target ='_blank'] { }`,
			fixed: `[target = '_blank'] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space opening it`,
			code: `[target=' _blank'] { }`,
			fixed: `[target= ' _blank'] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in apostrophes and a space inside the closing bracket`,
			code: `[target='_blank' ] { }`,
			fixed: `[target= '_blank' ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space closing it`,
			code: `[target='_blank '] { }`,
			fixed: `[target= '_blank '] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in apostrophes and a space inside the closing bracket`,
			code: `[target ='_blank' ] { }`,
			fixed: `[target = '_blank' ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space at each end of it`,
			code: `[target=' _blank '] { }`,
			fixed: `[target= ' _blank '] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target='_blank'] { }`,
			fixed: `[ target= '_blank'] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target ='_blank'] { }`,
			fixed: `[ target = '_blank'] { }`,
			line: 1,
			column: 10,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
			code: `[ target=' _blank'] { }`,
			fixed: `[ target= ' _blank'] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in apostrophes and spaces inside both brackets`,
			code: `[ target='_blank' ] { }`,
			fixed: `[ target= '_blank' ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
			code: `[ target='_blank '] { }`,
			fixed: `[ target= '_blank '] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in apostrophes and spaces inside both brackets`,
			code: `[ target ='_blank' ] { }`,
			fixed: `[ target = '_blank' ] { }`,
			line: 1,
			column: 10,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
			code: `[ target=' _blank '] { }`,
			fixed: `[ target= ' _blank '] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in quotation marks`,
			code: `[target="_blank"] { }`,
			fixed: `[target= "_blank"] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it and the value in quotation marks`,
			code: `[target ="_blank"] { }`,
			fixed: `[target = "_blank"] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space opening it`,
			code: `[target=" _blank"] { }`,
			fixed: `[target= " _blank"] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in quotation marks and a space inside the closing bracket`,
			code: `[target="_blank" ] { }`,
			fixed: `[target= "_blank" ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space closing it`,
			code: `[target="_blank "] { }`,
			fixed: `[target= "_blank "] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in quotation marks and a space inside the closing bracket`,
			code: `[target ="_blank" ] { }`,
			fixed: `[target = "_blank" ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space at each end of it`,
			code: `[target=" _blank "] { }`,
			fixed: `[target= " _blank "] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target="_blank"] { }`,
			fixed: `[ target= "_blank"] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target ="_blank"] { }`,
			fixed: `[ target = "_blank"] { }`,
			line: 1,
			column: 10,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
			code: `[ target=" _blank"] { }`,
			fixed: `[ target= " _blank"] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in quotation marks and spaces inside both brackets`,
			code: `[ target="_blank" ] { }`,
			fixed: `[ target= "_blank" ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
			code: `[ target="_blank "] { }`,
			fixed: `[ target= "_blank "] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in quotation marks and spaces inside both brackets`,
			code: `[ target ="_blank" ] { }`,
			fixed: `[ target = "_blank" ] { }`,
			line: 1,
			column: 10,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
			code: `[ target=" _blank "] { }`,
			fixed: `[ target= " _blank "] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the whitespace-list operator`,
			code: `[title~=flower] { }`,
			fixed: `[title~= flower] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`~=`),
		},
		{
			description: `no space after the whitespace-list operator, a space in front of it`,
			code: `[title ~=flower] { }`,
			fixed: `[title ~= flower] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`~=`),
		},
		{
			description: `no space after the hyphen-list operator`,
			code: `[title|=flower] { }`,
			fixed: `[title|= flower] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`|=`),
		},
		{
			description: `no space after the hyphen-list operator, a space in front of it`,
			code: `[title |=flower] { }`,
			fixed: `[title |= flower] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`|=`),
		},
		{
			description: `no space after the prefix operator`,
			code: `[title^=flower] { }`,
			fixed: `[title^= flower] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`^=`),
		},
		{
			description: `no space after the prefix operator, a space in front of it`,
			code: `[title ^=flower] { }`,
			fixed: `[title ^= flower] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`^=`),
		},
		{
			description: `no space after the suffix operator`,
			code: `[title$=flower] { }`,
			fixed: `[title$= flower] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`$=`),
		},
		{
			description: `no space after the suffix operator, a space in front of it`,
			code: `[title $=flower] { }`,
			fixed: `[title $= flower] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`$=`),
		},
		{
			description: `no space after the substring operator, behind a type selector`,
			code: `a[href*=w3schools] { }`,
			fixed: `a[href*= w3schools] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`*=`),
		},
		{
			description: `no space after the substring operator, a space in front of it, behind a type selector`,
			code: `a[href *=w3schools] { }`,
			fixed: `a[href *= w3schools] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`*=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's`,
			code: `img[alt~=person][src*= lorem] { }`,
			fixed: `img[alt~= person][src*= lorem] { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`~=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, a space in front of the first's`,
			code: `img[alt ~=person][src*= lorem] { }`,
			fixed: `img[alt ~= person][src*= lorem] { }`,
			line: 1,
			column: 10,
			message: messages.expectedAfter(`~=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, a space in front of the second's`,
			code: `img[alt~= person][src *=lorem] { }`,
			fixed: `img[alt~= person][src *= lorem] { }`,
			line: 1,
			column: 24,
			message: messages.expectedAfter(`*=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, a space in front of each of them`,
			code: `img[alt ~= person][src *=lorem] { }`,
			fixed: `img[alt ~= person][src *= lorem] { }`,
			line: 1,
			column: 25,
			message: messages.expectedAfter(`*=`),
		},
		{
			description: `no space after the equals operator, in front of a pseudo-class`,
			code: `[target=_blank]:hover { }`,
			fixed: `[target= _blank]:hover { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, in front of a pseudo-class`,
			code: `[target =_blank]:hover { }`,
			fixed: `[target = _blank]:hover { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, in front of a pseudo-element`,
			code: `[target=_blank]::before { }`,
			fixed: `[target= _blank]::before { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, in front of a pseudo-element`,
			code: `[target =_blank]::before { }`,
			fixed: `[target = _blank]::before { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, behind a type selector`,
			code: `option[data-hidden=true] { }`,
			fixed: `option[data-hidden= true] { }`,
			line: 1,
			column: 19,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, behind a type selector`,
			code: `option[data-hidden =true] { }`,
			fixed: `option[data-hidden = true] { }`,
			line: 1,
			column: 20,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align= right] {} }`,
			line: 1,
			column: 49,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align =right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align = right] {} }`,
			line: 1,
			column: 50,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, in front of a descendant selector`,
			code: `[target=_blank] .foo { }`,
			fixed: `[target= _blank] .foo { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, in front of a descendant selector`,
			code: `[target =_blank] .foo { }`,
			fixed: `[target = _blank] .foo { }`,
			line: 1,
			column: 9,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child(1) { }`,
			fixed: `li[aria-hidden= false]:nth-child(1) { }`,
			line: 1,
			column: 15,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden= false]:nth-child( 1) { }`,
			line: 1,
			column: 15,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden= false]:nth-child(1 ) { }`,
			line: 1,
			column: 15,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden= false]:nth-child( 1 ) { }`,
			line: 1,
			column: 15,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child(1) { }`,
			fixed: `li[aria-hidden = false]:nth-child(1) { }`,
			line: 1,
			column: 16,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden = false]:nth-child( 1) { }`,
			line: 1,
			column: 16,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden = false]:nth-child(1 ) { }`,
			line: 1,
			column: 16,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden = false]:nth-child( 1 ) { }`,
			line: 1,
			column: 16,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			line: 1,
			column: 18,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			line: 1,
			column: 43,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, a space in front of the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden= false] a { }`,
			line: 1,
			column: 19,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, a space in front of the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden= false] a { }`,
			line: 1,
			column: 44,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, a space in front of the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden = false] a { }`,
			line: 1,
			column: 18,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, a space in front of the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden = false] a { }`,
			line: 1,
			column: 44,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, a space in front of each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			line: 1,
			column: 19,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, a space in front of each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			line: 1,
			column: 45,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `no space after the operator of either attribute selector, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			warnings: [
				{
					line: 1,
					column: 18,
					message: messages.expectedAfter(`=`),
				},
				{
					line: 1,
					column: 42,
					message: messages.expectedAfter(`=`),
				},
			],
		},
		{
			description: `no space after the equals operator`,
			code: `[target=/**/"_blank"] { }`,
			fixed: `[target= /**/"_blank"] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
		{
			description: `a comment standing between the operator and the space the option asks for`,
			code: `[target=/**/ "_blank"] { }`,
			fixed: `[target= /**/ "_blank"] { }`,
			line: 1,
			column: 8,
			message: messages.expectedAfter(`=`),
		},
	],
})

testRule({
	ruleName,
	config: [`never`],

	accept: [
		{
			description: `a selector with no attribute in it`,
			code: `.foo { }`,
		},
		{
			description: `an attribute selector with no value`,
			code: `[target] { }`,
		},
		{
			description: `an attribute selector with no value, a space inside the opening bracket`,
			code: `[ target] { }`,
		},
		{
			description: `an attribute selector with no value, a space inside the closing bracket`,
			code: `[target ] { }`,
		},
		{
			description: `an attribute selector with no value, spaces inside both brackets`,
			code: `[ target ] { }`,
		},
		{
			description: `no space after the equals operator`,
			code: `[target=_blank] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it`,
			code: `[target =_blank] { }`,
		},
		{
			description: `no space after the equals operator, a space inside the closing bracket`,
			code: `[target=_blank ] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it and a space inside the closing bracket`,
			code: `[target =_blank ] { }`,
		},
		{
			description: `no space after the equals operator, a space inside the opening bracket`,
			code: `[ target=_blank] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it and a space inside the opening bracket`,
			code: `[ target =_blank] { }`,
		},
		{
			description: `no space after the equals operator, spaces inside both brackets`,
			code: `[ target=_blank ] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it and spaces inside both brackets`,
			code: `[ target =_blank ] { }`,
		},
		{
			description: `no space after the equals operator, the value in apostrophes`,
			code: `[target='_blank'] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it and the value in apostrophes`,
			code: `[target ='_blank'] { }`,
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space opening it`,
			code: `[target=' _blank'] { }`,
		},
		{
			description: `no space after the equals operator, the value in apostrophes and a space inside the closing bracket`,
			code: `[target='_blank' ] { }`,
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space closing it`,
			code: `[target='_blank '] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in apostrophes and a space inside the closing bracket`,
			code: `[target ='_blank' ] { }`,
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space at each end of it`,
			code: `[target=' _blank '] { }`,
		},
		{
			description: `no space after the equals operator, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target='_blank'] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target ='_blank'] { }`,
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
			code: `[ target=' _blank'] { }`,
		},
		{
			description: `no space after the equals operator, the value in apostrophes and spaces inside both brackets`,
			code: `[ target='_blank' ] { }`,
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
			code: `[ target='_blank '] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in apostrophes and spaces inside both brackets`,
			code: `[ target ='_blank' ] { }`,
		},
		{
			description: `no space after the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
			code: `[ target=' _blank '] { }`,
		},
		{
			description: `no space after the equals operator, the value in quotation marks`,
			code: `[target="_blank"] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it and the value in quotation marks`,
			code: `[target ="_blank"] { }`,
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space opening it`,
			code: `[target=" _blank"] { }`,
		},
		{
			description: `no space after the equals operator, the value in quotation marks and a space inside the closing bracket`,
			code: `[target="_blank" ] { }`,
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space closing it`,
			code: `[target="_blank "] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in quotation marks and a space inside the closing bracket`,
			code: `[target ="_blank" ] { }`,
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space at each end of it`,
			code: `[target=" _blank "] { }`,
		},
		{
			description: `no space after the equals operator, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target="_blank"] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target ="_blank"] { }`,
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
			code: `[ target=" _blank"] { }`,
		},
		{
			description: `no space after the equals operator, the value in quotation marks and spaces inside both brackets`,
			code: `[ target="_blank" ] { }`,
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
			code: `[ target="_blank "] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, the value in quotation marks and spaces inside both brackets`,
			code: `[ target ="_blank" ] { }`,
		},
		{
			description: `no space after the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
			code: `[ target=" _blank "] { }`,
		},
		{
			description: `no space after the whitespace-list operator`,
			code: `[title~=flower] { }`,
		},
		{
			description: `no space after the whitespace-list operator, a space in front of it`,
			code: `[title ~=flower] { }`,
		},
		{
			description: `no space after the hyphen-list operator`,
			code: `[title|=flower] { }`,
		},
		{
			description: `no space after the hyphen-list operator, a space in front of it`,
			code: `[title |=flower] { }`,
		},
		{
			description: `no space after the prefix operator`,
			code: `[title^=flower] { }`,
		},
		{
			description: `no space after the prefix operator, a space in front of it`,
			code: `[title ^=flower] { }`,
		},
		{
			description: `no space after the suffix operator`,
			code: `[title$=flower] { }`,
		},
		{
			description: `no space after the suffix operator, a space in front of it`,
			code: `[title $=flower] { }`,
		},
		{
			description: `no space after the substring operator, behind a type selector`,
			code: `a[href*=w3schools] { }`,
		},
		{
			description: `no space after the substring operator, a space in front of it, behind a type selector`,
			code: `a[href *=w3schools] { }`,
		},
		{
			description: `no space after the operator of either attribute selector`,
			code: `img[alt~=person][src*=lorem] { }`,
		},
		{
			description: `no space after the operator of either attribute selector, a space in front of the first's`,
			code: `img[alt ~=person][src*=lorem] { }`,
		},
		{
			description: `no space after the operator of either attribute selector, a space in front of the second's`,
			code: `img[alt~=person][src *=lorem] { }`,
		},
		{
			description: `no space after the operator of either attribute selector, a space in front of each of them`,
			code: `img[alt ~=person][src *=lorem] { }`,
		},
		{
			description: `no space after the equals operator, in front of a pseudo-class`,
			code: `[target=_blank]:hover { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, in front of a pseudo-class`,
			code: `[target =_blank]:hover { }`,
		},
		{
			description: `no space after the equals operator, in front of a pseudo-element`,
			code: `[target=_blank]::before { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, in front of a pseudo-element`,
			code: `[target =_blank]::before { }`,
		},
		{
			description: `no space after the equals operator, behind a type selector`,
			code: `option[data-hidden=true] { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, behind a type selector`,
			code: `option[data-hidden =true] { }`,
		},
		{
			description: `an attribute selector with no value, behind a type selector`,
			code: `option[dataHidden] { }`,
		},
		{
			description: `no space after the equals operator, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align=right] {} }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align =right] {} }`,
		},
		{
			description: `no space after the equals operator, in front of a descendant selector`,
			code: `[target=_blank] .foo { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, in front of a descendant selector`,
			code: `[target =_blank] .foo { }`,
		},
		{
			description: `no space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child(1) { }`,
		},
		{
			description: `no space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child( 1) { }`,
		},
		{
			description: `no space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child(1 ) { }`,
		},
		{
			description: `no space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child( 1 ) { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child(1) { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child( 1) { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child(1 ) { }`,
		},
		{
			description: `no space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child( 1 ) { }`,
		},
		{
			description: `no space after the operator of either attribute selector, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
		},
		{
			description: `no space after the operator of either attribute selector, a space in front of the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden=false] a { }`,
		},
		{
			description: `no space after the operator of either attribute selector, a space in front of the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden =false] a { }`,
		},
		{
			description: `no space after the operator of either attribute selector, a space in front of each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden =false] a { }`,
		},
		{
			description: `an attribute selector with no value, in a rule that carries a declaration`,
			code: `[target] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, a space inside the closing bracket, in a rule that carries a declaration`,
			code: `[target ] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, a space inside the opening bracket, in a rule that carries a declaration`,
			code: `[ target] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, spaces inside both brackets, in a rule that carries a declaration`,
			code: `[ target ] { content: " " }`,
		},
	],

	reject: [
		{
			description: `a space after the equals operator`,
			code: `[target= _blank] { }`,
			fixed: `[target=_blank] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it`,
			code: `[target = _blank] { }`,
			fixed: `[target =_blank] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space inside the closing bracket`,
			code: `[target= _blank ] { }`,
			fixed: `[target=_blank ] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it and a space inside the closing bracket`,
			code: `[target = _blank ] { }`,
			fixed: `[target =_blank ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space inside the opening bracket`,
			code: `[ target= _blank] { }`,
			fixed: `[ target=_blank] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it and a space inside the opening bracket`,
			code: `[ target = _blank] { }`,
			fixed: `[ target =_blank] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, spaces inside both brackets`,
			code: `[ target= _blank ] { }`,
			fixed: `[ target=_blank ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it and spaces inside both brackets`,
			code: `[ target = _blank ] { }`,
			fixed: `[ target =_blank ] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in apostrophes`,
			code: `[target= '_blank'] { }`,
			fixed: `[target='_blank'] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it and the value in apostrophes`,
			code: `[target = '_blank'] { }`,
			fixed: `[target ='_blank'] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space opening it`,
			code: `[target= ' _blank'] { }`,
			fixed: `[target=' _blank'] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in apostrophes and a space inside the closing bracket`,
			code: `[target= '_blank' ] { }`,
			fixed: `[target='_blank' ] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space closing it`,
			code: `[target= '_blank '] { }`,
			fixed: `[target='_blank '] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in apostrophes and a space inside the closing bracket`,
			code: `[target = '_blank' ] { }`,
			fixed: `[target ='_blank' ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space at each end of it`,
			code: `[target= ' _blank '] { }`,
			fixed: `[target=' _blank '] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target= '_blank'] { }`,
			fixed: `[ target='_blank'] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target = '_blank'] { }`,
			fixed: `[ target ='_blank'] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
			code: `[ target= ' _blank'] { }`,
			fixed: `[ target=' _blank'] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in apostrophes and spaces inside both brackets`,
			code: `[ target= '_blank' ] { }`,
			fixed: `[ target='_blank' ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
			code: `[ target= '_blank '] { }`,
			fixed: `[ target='_blank '] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in apostrophes and spaces inside both brackets`,
			code: `[ target = '_blank' ] { }`,
			fixed: `[ target ='_blank' ] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
			code: `[ target= ' _blank '] { }`,
			fixed: `[ target=' _blank '] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in quotation marks`,
			code: `[target= "_blank"] { }`,
			fixed: `[target="_blank"] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it and the value in quotation marks`,
			code: `[target = "_blank"] { }`,
			fixed: `[target ="_blank"] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space opening it`,
			code: `[target= " _blank"] { }`,
			fixed: `[target=" _blank"] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in quotation marks and a space inside the closing bracket`,
			code: `[target= "_blank" ] { }`,
			fixed: `[target="_blank" ] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space closing it`,
			code: `[target= "_blank "] { }`,
			fixed: `[target="_blank "] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in quotation marks and a space inside the closing bracket`,
			code: `[target = "_blank" ] { }`,
			fixed: `[target ="_blank" ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space at each end of it`,
			code: `[target= " _blank "] { }`,
			fixed: `[target=" _blank "] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target= "_blank"] { }`,
			fixed: `[ target="_blank"] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target = "_blank"] { }`,
			fixed: `[ target ="_blank"] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
			code: `[ target= " _blank"] { }`,
			fixed: `[ target=" _blank"] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in quotation marks and spaces inside both brackets`,
			code: `[ target= "_blank" ] { }`,
			fixed: `[ target="_blank" ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
			code: `[ target= "_blank "] { }`,
			fixed: `[ target="_blank "] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, the value in quotation marks and spaces inside both brackets`,
			code: `[ target = "_blank" ] { }`,
			fixed: `[ target ="_blank" ] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
			code: `[ target= " _blank "] { }`,
			fixed: `[ target=" _blank "] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the whitespace-list operator`,
			code: `[title~= flower] { }`,
			fixed: `[title~=flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`~=`),
		},
		{
			description: `a space after the whitespace-list operator, a space in front of it`,
			code: `[title ~= flower] { }`,
			fixed: `[title ~=flower] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`~=`),
		},
		{
			description: `a space after the hyphen-list operator`,
			code: `[title|= flower] { }`,
			fixed: `[title|=flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`|=`),
		},
		{
			description: `a space after the hyphen-list operator, a space in front of it`,
			code: `[title |= flower] { }`,
			fixed: `[title |=flower] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`|=`),
		},
		{
			description: `a space after the prefix operator`,
			code: `[title^= flower] { }`,
			fixed: `[title^=flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`^=`),
		},
		{
			description: `a space after the prefix operator, a space in front of it`,
			code: `[title ^= flower] { }`,
			fixed: `[title ^=flower] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`^=`),
		},
		{
			description: `a space after the suffix operator`,
			code: `[title$= flower] { }`,
			fixed: `[title$=flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`$=`),
		},
		{
			description: `a space after the suffix operator, a space in front of it`,
			code: `[title $= flower] { }`,
			fixed: `[title $=flower] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`$=`),
		},
		{
			description: `a space after the substring operator, behind a type selector`,
			code: `a[href*= w3schools] { }`,
			fixed: `a[href*=w3schools] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`*=`),
		},
		{
			description: `a space after the substring operator, a space in front of it, behind a type selector`,
			code: `a[href *= w3schools] { }`,
			fixed: `a[href *=w3schools] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`*=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's`,
			code: `img[alt~= person][src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`~=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, a space in front of the first's`,
			code: `img[alt ~= person][src*=lorem] { }`,
			fixed: `img[alt ~=person][src*=lorem] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedAfter(`~=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, a space in front of the second's`,
			code: `img[alt~=person][src *= lorem] { }`,
			fixed: `img[alt~=person][src *=lorem] { }`,
			line: 1,
			column: 23,
			message: messages.rejectedAfter(`*=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, a space in front of each of them`,
			code: `img[alt ~=person][src *= lorem] { }`,
			fixed: `img[alt ~=person][src *=lorem] { }`,
			line: 1,
			column: 24,
			message: messages.rejectedAfter(`*=`),
		},
		{
			description: `a space after the equals operator, in front of a pseudo-class`,
			code: `[target= _blank]:hover { }`,
			fixed: `[target=_blank]:hover { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, in front of a pseudo-class`,
			code: `[target = _blank]:hover { }`,
			fixed: `[target =_blank]:hover { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, in front of a pseudo-element`,
			code: `[target= _blank]::before { }`,
			fixed: `[target=_blank]::before { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, in front of a pseudo-element`,
			code: `[target = _blank]::before { }`,
			fixed: `[target =_blank]::before { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, behind a type selector`,
			code: `option[data-hidden= true] { }`,
			fixed: `option[data-hidden=true] { }`,
			line: 1,
			column: 19,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, behind a type selector`,
			code: `option[data-hidden = true] { }`,
			fixed: `option[data-hidden =true] { }`,
			line: 1,
			column: 20,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align= right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			line: 1,
			column: 49,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align = right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align =right] {} }`,
			line: 1,
			column: 50,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, in front of a descendant selector`,
			code: `[target= _blank] .foo { }`,
			fixed: `[target=_blank] .foo { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, in front of a descendant selector`,
			code: `[target = _blank] .foo { }`,
			fixed: `[target =_blank] .foo { }`,
			line: 1,
			column: 9,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child(1) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1) { }`,
			line: 1,
			column: 15,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1) { }`,
			line: 1,
			column: 15,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1 ) { }`,
			line: 1,
			column: 15,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			line: 1,
			column: 15,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child(1) { }`,
			fixed: `li[aria-hidden =false]:nth-child(1) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden =false]:nth-child( 1) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden =false]:nth-child(1 ) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the equals operator, a space in front of it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden =false]:nth-child( 1 ) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 18,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 42,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, a space in front of the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 19,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, a space in front of the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 43,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, a space in front of the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden =false] a { }`,
			line: 1,
			column: 18,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, a space in front of the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden =false] a { }`,
			line: 1,
			column: 43,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the operator of the first attribute selector and none after the second's, a space in front of each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden =false] a { }`,
			line: 1,
			column: 19,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the operator of the second attribute selector and none after the first's, a space in front of each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden =false] a { }`,
			line: 1,
			column: 44,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a space after the operator of each of the two attribute selectors, a space in front of each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden =false] a { }`,
			warnings: [
				{
					line: 1,
					column: 19,
					message: messages.rejectedAfter(`=`),
				},
				{
					line: 1,
					column: 45,
					message: messages.rejectedAfter(`=`),
				},
			],
		},
		{
			description: `a space after the equals operator`,
			code: `[target= /**/"_blank"] { }`,
			fixed: `[target=/**/"_blank"] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
		{
			description: `a comment standing behind the space the option forbids`,
			code: `[target= /**/ "_blank"] { }`,
			fixed: `[target=/**/ "_blank"] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedAfter(`=`),
		},
	],
})

testRule({
	ruleName,
	config: [`always`],
	customSyntax: `postcss-scss`,

	reject: [
		{
			// https://github.com/stylelint-stylistic/stylelint-stylistic/issues/193
			description: `a selector carrying an inline comment, whose fix reaches the copy the file spells, reported in the file's own coordinates`,
			code: `.a // c\n[t='y'] {}`,
			fixed: `.a // c\n[t= 'y'] {}`,
			line: 2,
			column: 3,
			message: messages.expectedAfter(`=`),
		},
	],
})
