import { messages, ruleName } from "./index.ts"

let testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`always`],

	accept: [
		{
			// The selector parser files the parts of such an attribute so that it prints them back in another order, and the checker passes it over
			description: `two escaped tabs behind the operator, whose parts the selector parser prints back in another order`,
			code: `[a=\\\t\\\tb] {}`,
		},
		{
			description: `a selector with no attribute in it`,
			code: `.foo { }`,
		},
		{
			description: `an attribute selector with no value`,
			code: `[target] { }`,
		},
		{
			description: `an attribute selector with no value, a space inside the opening bracket`,
			code: `[ target] { }`,
		},
		{
			description: `an attribute selector with no value, a space inside the closing bracket`,
			code: `[target ] { }`,
		},
		{
			description: `an attribute selector with no value, spaces inside both brackets`,
			code: `[ target ] { }`,
		},
		{
			description: `a space in front of the equals operator`,
			code: `[target =_blank] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it`,
			code: `[target = _blank] { }`,
		},
		{
			description: `a space in front of the equals operator, a space inside the closing bracket`,
			code: `[target =_blank ] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it and a space inside the closing bracket`,
			code: `[target = _blank ] { }`,
		},
		{
			description: `a space in front of the equals operator, a space inside the opening bracket`,
			code: `[ target =_blank] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it and a space inside the opening bracket`,
			code: `[ target = _blank] { }`,
		},
		{
			description: `a space in front of the equals operator, spaces inside both brackets`,
			code: `[ target =_blank ] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it and spaces inside both brackets`,
			code: `[ target = _blank ] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes`,
			code: `[target ='_blank'] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it and the value in apostrophes`,
			code: `[target = '_blank'] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space opening it`,
			code: `[target =' _blank'] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes and a space inside the closing bracket`,
			code: `[target ='_blank' ] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space closing it`,
			code: `[target ='_blank '] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and a space inside the closing bracket`,
			code: `[target = '_blank' ] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space at each end of it`,
			code: `[target =' _blank '] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target ='_blank'] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target = '_blank'] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
			code: `[ target =' _blank'] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes and spaces inside both brackets`,
			code: `[ target ='_blank' ] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
			code: `[ target ='_blank '] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and spaces inside both brackets`,
			code: `[ target = '_blank' ] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
			code: `[ target =' _blank '] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks`,
			code: `[target ="_blank"] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it and the value in quotation marks`,
			code: `[target = "_blank"] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space opening it`,
			code: `[target =" _blank"] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks and a space inside the closing bracket`,
			code: `[target ="_blank" ] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space closing it`,
			code: `[target ="_blank "] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and a space inside the closing bracket`,
			code: `[target = "_blank" ] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space at each end of it`,
			code: `[target =" _blank "] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target ="_blank"] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target = "_blank"] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
			code: `[ target =" _blank"] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks and spaces inside both brackets`,
			code: `[ target ="_blank" ] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
			code: `[ target ="_blank "] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and spaces inside both brackets`,
			code: `[ target = "_blank" ] { }`,
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
			code: `[ target =" _blank "] { }`,
		},
		{
			description: `a space in front of the whitespace-list operator`,
			code: `[title ~=flower] { }`,
		},
		{
			description: `a space in front of the whitespace-list operator, a space after it`,
			code: `[title ~= flower] { }`,
		},
		{
			description: `a space in front of the hyphen-list operator`,
			code: `[title |=flower] { }`,
		},
		{
			description: `a space in front of the hyphen-list operator, a space after it`,
			code: `[title |= flower] { }`,
		},
		{
			description: `a space in front of the prefix operator`,
			code: `[title ^=flower] { }`,
		},
		{
			description: `a space in front of the prefix operator, a space after it`,
			code: `[title ^= flower] { }`,
		},
		{
			description: `a space in front of the suffix operator`,
			code: `[title $=flower] { }`,
		},
		{
			description: `a space in front of the suffix operator, a space after it`,
			code: `[title $= flower] { }`,
		},
		{
			description: `a space in front of the substring operator, behind a type selector`,
			code: `a[href *=w3schools] { }`,
		},
		{
			description: `a space in front of the substring operator, a space after it, behind a type selector`,
			code: `a[href *= w3schools] { }`,
		},
		{
			description: `a space in front of the operator of each of the two attribute selectors`,
			code: `img[alt ~=person][src *=lorem] { }`,
		},
		{
			description: `a space in front of the operator of each of the two attribute selectors, a space after the first's`,
			code: `img[alt ~= person][src *=lorem] { }`,
		},
		{
			description: `a space in front of the operator of each of the two attribute selectors, a space after the second's`,
			code: `img[alt ~=person][src *= lorem] { }`,
		},
		{
			description: `a space in front of the operator of each of the two attribute selectors, a space after each of them`,
			code: `img[alt ~= person][src *= lorem] { }`,
		},
		{
			description: `a space in front of the equals operator, in front of a pseudo-class`,
			code: `[target =_blank]:hover { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, in front of a pseudo-class`,
			code: `[target = _blank]:hover { }`,
		},
		{
			description: `a space in front of the equals operator, in front of a pseudo-element`,
			code: `[target =_blank]::before { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, in front of a pseudo-element`,
			code: `[target = _blank]::before { }`,
		},
		{
			description: `a space in front of the equals operator, behind a type selector`,
			code: `option[data-hidden =true] { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, behind a type selector`,
			code: `option[data-hidden = true] { }`,
		},
		{
			description: `an attribute selector with no value, behind a type selector`,
			code: `option[dataHidden] { }`,
		},
		{
			description: `a space in front of the equals operator, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align =right] {} }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align = right] {} }`,
		},
		{
			description: `a space in front of the equals operator, in front of a descendant selector`,
			code: `[target =_blank] .foo { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, in front of a descendant selector`,
			code: `[target = _blank] .foo { }`,
		},
		{
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child(1) { }`,
		},
		{
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child( 1) { }`,
		},
		{
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child(1 ) { }`,
		},
		{
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child( 1 ) { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child(1) { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child( 1) { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child(1 ) { }`,
		},
		{
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child( 1 ) { }`,
		},
		{
			description: `a space in front of the operator of each of the two attribute selectors, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden =false] a { }`,
		},
		{
			description: `a space in front of the operator of each of the two attribute selectors, a space after the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden =false] a { }`,
		},
		{
			description: `a space in front of the operator of each of the two attribute selectors, a space after the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden = false] a { }`,
		},
		{
			description: `a space in front of the operator of each of the two attribute selectors, a space after each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
		},
		{
			description: `an attribute selector with no value, in a rule that carries a declaration`,
			code: `[target] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, a space inside the closing bracket, in a rule that carries a declaration`,
			code: `[target ] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, a space inside the opening bracket, in a rule that carries a declaration`,
			code: `[ target] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, spaces inside both brackets, in a rule that carries a declaration`,
			code: `[ target ] { content: " " }`,
		},
		{
			description: `a custom property under the root selector`,
			code: `:root { --foo: 1px; }`,
		},
		{
			description: `a custom property under a type selector`,
			code: `html { --foo: 1px; }`,
		},
		{
			description: `a custom property set under the root selector`,
			code: `:root { --custom-property-set: {} }`,
		},
		{
			description: `a custom property set under a type selector`,
			code: `html { --custom-property-set: {} }`,
		},
		{
			description: `an attribute selector the parser cannot read`,
			code: `a[b=#{c}] { }`,
		},
	],

	reject: [
		{
			// The selector parser reads a backslash in front of a tab as no escape, and the fix wrote over the tab
			description: `an escaped tab in front of the operator, which is a character of the name and no space`,
			code: `[a\\\t=b] {}`,
			fixed: `[a\\\t =b] {}`,
			line: 1,
			column: 5,
			message: messages.expectedBefore(`=`),
		},
		{
			// Pins the refusal of a write behind a backslash the character it escapes would change behind
			description: `a backslash ending the attribute in front of a line break and the operator, where the space would stand behind the backslash as its escaped character, so the warning stands`,
			code: `[a\\\n=b] {}`,
			fixed: `[a\\\n=b] {}`,
			line: 2,
			column: 1,
			message: messages.expectedBefore(`=`),
		},
		{
			// The run in front of the delimiter is read over the copy with its escapes masked
			description: `an escaped space in front of the operator, which is a character of the attribute's name and no space`,
			code: `[a\\ =b] {}`,
			fixed: `[a\\  =b] {}`,
			line: 1,
			column: 5,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator`,
			code: `[target=_blank] { }`,
			fixed: `[target =_blank] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it`,
			code: `[target= _blank] { }`,
			fixed: `[target = _blank] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space inside the closing bracket`,
			code: `[target=_blank ] { }`,
			fixed: `[target =_blank ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it and a space inside the closing bracket`,
			code: `[target= _blank ] { }`,
			fixed: `[target = _blank ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space inside the opening bracket`,
			code: `[ target=_blank] { }`,
			fixed: `[ target =_blank] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it and a space inside the opening bracket`,
			code: `[ target= _blank] { }`,
			fixed: `[ target = _blank] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, spaces inside both brackets`,
			code: `[ target=_blank ] { }`,
			fixed: `[ target =_blank ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it and spaces inside both brackets`,
			code: `[ target= _blank ] { }`,
			fixed: `[ target = _blank ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes`,
			code: `[target='_blank'] { }`,
			fixed: `[target ='_blank'] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it and the value in apostrophes`,
			code: `[target= '_blank'] { }`,
			fixed: `[target = '_blank'] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space opening it`,
			code: `[target=' _blank'] { }`,
			fixed: `[target =' _blank'] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes and a space inside the closing bracket`,
			code: `[target='_blank' ] { }`,
			fixed: `[target ='_blank' ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space closing it`,
			code: `[target='_blank '] { }`,
			fixed: `[target ='_blank '] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and a space inside the closing bracket`,
			code: `[target= '_blank' ] { }`,
			fixed: `[target = '_blank' ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space at each end of it`,
			code: `[target=' _blank '] { }`,
			fixed: `[target =' _blank '] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target='_blank'] { }`,
			fixed: `[ target ='_blank'] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target= '_blank'] { }`,
			fixed: `[ target = '_blank'] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
			code: `[ target=' _blank'] { }`,
			fixed: `[ target =' _blank'] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes and spaces inside both brackets`,
			code: `[ target='_blank' ] { }`,
			fixed: `[ target ='_blank' ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
			code: `[ target='_blank '] { }`,
			fixed: `[ target ='_blank '] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and spaces inside both brackets`,
			code: `[ target= '_blank' ] { }`,
			fixed: `[ target = '_blank' ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
			code: `[ target=' _blank '] { }`,
			fixed: `[ target =' _blank '] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks`,
			code: `[target="_blank"] { }`,
			fixed: `[target ="_blank"] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it and the value in quotation marks`,
			code: `[target= "_blank"] { }`,
			fixed: `[target = "_blank"] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space opening it`,
			code: `[target=" _blank"] { }`,
			fixed: `[target =" _blank"] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks and a space inside the closing bracket`,
			code: `[target="_blank" ] { }`,
			fixed: `[target ="_blank" ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space closing it`,
			code: `[target="_blank "] { }`,
			fixed: `[target ="_blank "] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and a space inside the closing bracket`,
			code: `[target= "_blank" ] { }`,
			fixed: `[target = "_blank" ] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space at each end of it`,
			code: `[target=" _blank "] { }`,
			fixed: `[target =" _blank "] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target="_blank"] { }`,
			fixed: `[ target ="_blank"] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target= "_blank"] { }`,
			fixed: `[ target = "_blank"] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
			code: `[ target=" _blank"] { }`,
			fixed: `[ target =" _blank"] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks and spaces inside both brackets`,
			code: `[ target="_blank" ] { }`,
			fixed: `[ target ="_blank" ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
			code: `[ target="_blank "] { }`,
			fixed: `[ target ="_blank "] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and spaces inside both brackets`,
			code: `[ target= "_blank" ] { }`,
			fixed: `[ target = "_blank" ] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
			code: `[ target=" _blank "] { }`,
			fixed: `[ target =" _blank "] { }`,
			line: 1,
			column: 9,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the whitespace-list operator`,
			code: `[title~=flower] { }`,
			fixed: `[title ~=flower] { }`,
			line: 1,
			column: 7,
			message: messages.expectedBefore(`~=`),
		},
		{
			description: `no space in front of the whitespace-list operator, a space after it`,
			code: `[title~= flower] { }`,
			fixed: `[title ~= flower] { }`,
			line: 1,
			column: 7,
			message: messages.expectedBefore(`~=`),
		},
		{
			description: `no space in front of the hyphen-list operator`,
			code: `[title|=flower] { }`,
			fixed: `[title |=flower] { }`,
			line: 1,
			column: 7,
			message: messages.expectedBefore(`|=`),
		},
		{
			description: `no space in front of the hyphen-list operator, a space after it`,
			code: `[title|= flower] { }`,
			fixed: `[title |= flower] { }`,
			line: 1,
			column: 7,
			message: messages.expectedBefore(`|=`),
		},
		{
			description: `no space in front of the prefix operator`,
			code: `[title^=flower] { }`,
			fixed: `[title ^=flower] { }`,
			line: 1,
			column: 7,
			message: messages.expectedBefore(`^=`),
		},
		{
			description: `no space in front of the prefix operator, a space after it`,
			code: `[title^= flower] { }`,
			fixed: `[title ^= flower] { }`,
			line: 1,
			column: 7,
			message: messages.expectedBefore(`^=`),
		},
		{
			description: `no space in front of the suffix operator`,
			code: `[title$=flower] { }`,
			fixed: `[title $=flower] { }`,
			line: 1,
			column: 7,
			message: messages.expectedBefore(`$=`),
		},
		{
			description: `no space in front of the suffix operator, a space after it`,
			code: `[title$= flower] { }`,
			fixed: `[title $= flower] { }`,
			line: 1,
			column: 7,
			message: messages.expectedBefore(`$=`),
		},
		{
			description: `no space in front of the substring operator, behind a type selector`,
			code: `a[href*=w3schools] { }`,
			fixed: `a[href *=w3schools] { }`,
			line: 1,
			column: 7,
			message: messages.expectedBefore(`*=`),
		},
		{
			description: `no space in front of the substring operator, a space after it, behind a type selector`,
			code: `a[href*= w3schools] { }`,
			fixed: `a[href *= w3schools] { }`,
			line: 1,
			column: 7,
			message: messages.expectedBefore(`*=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's`,
			code: `img[alt~=person][src *=lorem] { }`,
			fixed: `img[alt ~=person][src *=lorem] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`~=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the first's`,
			code: `img[alt~= person][src *=lorem] { }`,
			fixed: `img[alt ~= person][src *=lorem] { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`~=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the second's`,
			code: `img[alt ~=person][src*= lorem] { }`,
			fixed: `img[alt ~=person][src *= lorem] { }`,
			line: 1,
			column: 22,
			message: messages.expectedBefore(`*=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after each of them`,
			code: `img[alt ~= person][src*= lorem] { }`,
			fixed: `img[alt ~= person][src *= lorem] { }`,
			line: 1,
			column: 23,
			message: messages.expectedBefore(`*=`),
		},
		{
			description: `no space in front of the equals operator, in front of a pseudo-class`,
			code: `[target=_blank]:hover { }`,
			fixed: `[target =_blank]:hover { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, in front of a pseudo-class`,
			code: `[target= _blank]:hover { }`,
			fixed: `[target = _blank]:hover { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, in front of a pseudo-element`,
			code: `[target=_blank]::before { }`,
			fixed: `[target =_blank]::before { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, in front of a pseudo-element`,
			code: `[target= _blank]::before { }`,
			fixed: `[target = _blank]::before { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, behind a type selector`,
			code: `option[data-hidden=true] { }`,
			fixed: `option[data-hidden =true] { }`,
			line: 1,
			column: 19,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, behind a type selector`,
			code: `option[data-hidden= true] { }`,
			fixed: `option[data-hidden = true] { }`,
			line: 1,
			column: 19,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align =right] {} }`,
			line: 1,
			column: 49,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align= right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align = right] {} }`,
			line: 1,
			column: 49,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, in front of a descendant selector`,
			code: `[target=_blank] .foo { }`,
			fixed: `[target =_blank] .foo { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, in front of a descendant selector`,
			code: `[target= _blank] .foo { }`,
			fixed: `[target = _blank] .foo { }`,
			line: 1,
			column: 8,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child(1) { }`,
			fixed: `li[aria-hidden =false]:nth-child(1) { }`,
			line: 1,
			column: 15,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden =false]:nth-child( 1) { }`,
			line: 1,
			column: 15,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden =false]:nth-child(1 ) { }`,
			line: 1,
			column: 15,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden =false]:nth-child( 1 ) { }`,
			line: 1,
			column: 15,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child(1) { }`,
			fixed: `li[aria-hidden = false]:nth-child(1) { }`,
			line: 1,
			column: 15,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden = false]:nth-child( 1) { }`,
			line: 1,
			column: 15,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden = false]:nth-child(1 ) { }`,
			line: 1,
			column: 15,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden = false]:nth-child( 1 ) { }`,
			line: 1,
			column: 15,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden =false] a { }`,
			line: 1,
			column: 18,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden =false] a { }`,
			line: 1,
			column: 43,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden =false] a { }`,
			line: 1,
			column: 18,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden =false] a { }`,
			line: 1,
			column: 44,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden = false] a { }`,
			line: 1,
			column: 18,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden = false] a { }`,
			line: 1,
			column: 43,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			line: 1,
			column: 18,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			line: 1,
			column: 44,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `no space in front of the operator of either attribute selector, a space after each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			warnings: [
				{
					line: 1,
					column: 18,
					message: messages.expectedBefore(`=`),
				},
				{
					line: 1,
					column: 43,
					message: messages.expectedBefore(`=`),
				},
			],
		},
		{
			description: `a comment standing where the space the option asks for would go`,
			code: `[target/**/="_blank"] { }`,
			fixed: `[target/**/ ="_blank"] { }`,
			line: 1,
			column: 12,
			message: messages.expectedBefore(`=`),
		},
		{
			description: `a comment standing between the space and the operator`,
			code: `[target /**/="_blank"] { }`,
			fixed: `[target /**/ ="_blank"] { }`,
			line: 1,
			column: 13,
			message: messages.expectedBefore(`=`),
		},
	],
})

testRule({
	ruleName,
	config: [`never`],

	accept: [
		{
			// The run in front of the delimiter is read over the copy with its escapes masked
			description: `an escaped space in front of the operator, which is a character of the attribute's name and no whitespace`,
			code: `[a\\ =b] {}`,
		},
		{
			description: `a selector with no attribute in it`,
			code: `.foo { }`,
		},
		{
			description: `an attribute selector with no value`,
			code: `[target] { }`,
		},
		{
			description: `an attribute selector with no value, a space inside the opening bracket`,
			code: `[ target] { }`,
		},
		{
			description: `an attribute selector with no value, a space inside the closing bracket`,
			code: `[target ] { }`,
		},
		{
			description: `an attribute selector with no value, spaces inside both brackets`,
			code: `[ target ] { }`,
		},
		{
			description: `no space in front of the equals operator`,
			code: `[target=_blank] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it`,
			code: `[target= _blank] { }`,
		},
		{
			description: `no space in front of the equals operator, a space inside the closing bracket`,
			code: `[target=_blank ] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it and a space inside the closing bracket`,
			code: `[target= _blank ] { }`,
		},
		{
			description: `no space in front of the equals operator, a space inside the opening bracket`,
			code: `[ target=_blank] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it and a space inside the opening bracket`,
			code: `[ target= _blank] { }`,
		},
		{
			description: `no space in front of the equals operator, spaces inside both brackets`,
			code: `[ target=_blank ] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it and spaces inside both brackets`,
			code: `[ target= _blank ] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes`,
			code: `[target='_blank'] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it and the value in apostrophes`,
			code: `[target= '_blank'] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space opening it`,
			code: `[target=' _blank'] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes and a space inside the closing bracket`,
			code: `[target='_blank' ] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space closing it`,
			code: `[target='_blank '] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and a space inside the closing bracket`,
			code: `[target= '_blank' ] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space at each end of it`,
			code: `[target=' _blank '] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target='_blank'] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target= '_blank'] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
			code: `[ target=' _blank'] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes and spaces inside both brackets`,
			code: `[ target='_blank' ] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
			code: `[ target='_blank '] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and spaces inside both brackets`,
			code: `[ target= '_blank' ] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
			code: `[ target=' _blank '] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks`,
			code: `[target="_blank"] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it and the value in quotation marks`,
			code: `[target= "_blank"] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space opening it`,
			code: `[target=" _blank"] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks and a space inside the closing bracket`,
			code: `[target="_blank" ] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space closing it`,
			code: `[target="_blank "] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and a space inside the closing bracket`,
			code: `[target= "_blank" ] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space at each end of it`,
			code: `[target=" _blank "] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target="_blank"] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target= "_blank"] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
			code: `[ target=" _blank"] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks and spaces inside both brackets`,
			code: `[ target="_blank" ] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
			code: `[ target="_blank "] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and spaces inside both brackets`,
			code: `[ target= "_blank" ] { }`,
		},
		{
			description: `no space in front of the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
			code: `[ target=" _blank "] { }`,
		},
		{
			description: `no space in front of the whitespace-list operator`,
			code: `[title~=flower] { }`,
		},
		{
			description: `no space in front of the whitespace-list operator, a space after it`,
			code: `[title~= flower] { }`,
		},
		{
			description: `no space in front of the hyphen-list operator`,
			code: `[title|=flower] { }`,
		},
		{
			description: `no space in front of the hyphen-list operator, a space after it`,
			code: `[title|= flower] { }`,
		},
		{
			description: `no space in front of the prefix operator`,
			code: `[title^=flower] { }`,
		},
		{
			description: `no space in front of the prefix operator, a space after it`,
			code: `[title^= flower] { }`,
		},
		{
			description: `no space in front of the suffix operator`,
			code: `[title$=flower] { }`,
		},
		{
			description: `no space in front of the suffix operator, a space after it`,
			code: `[title$= flower] { }`,
		},
		{
			description: `no space in front of the substring operator, behind a type selector`,
			code: `a[href*=w3schools] { }`,
		},
		{
			description: `no space in front of the substring operator, a space after it, behind a type selector`,
			code: `a[href*= w3schools] { }`,
		},
		{
			description: `no space in front of the operator of either attribute selector`,
			code: `img[alt~=person][src*=lorem] { }`,
		},
		{
			description: `no space in front of the operator of either attribute selector, a space after the first's`,
			code: `img[alt~= person][src*=lorem] { }`,
		},
		{
			description: `no space in front of the operator of either attribute selector, a space after the second's`,
			code: `img[alt~=person][src*= lorem] { }`,
		},
		{
			description: `no space in front of the operator of either attribute selector, a space after each of them`,
			code: `img[alt~= person][src*= lorem] { }`,
		},
		{
			description: `no space in front of the equals operator, in front of a pseudo-class`,
			code: `[target=_blank]:hover { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, in front of a pseudo-class`,
			code: `[target= _blank]:hover { }`,
		},
		{
			description: `no space in front of the equals operator, in front of a pseudo-element`,
			code: `[target=_blank]::before { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, in front of a pseudo-element`,
			code: `[target= _blank]::before { }`,
		},
		{
			description: `no space in front of the equals operator, behind a type selector`,
			code: `option[data-hidden=true] { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, behind a type selector`,
			code: `option[data-hidden= true] { }`,
		},
		{
			description: `an attribute selector with no value, behind a type selector`,
			code: `option[dataHidden] { }`,
		},
		{
			description: `no space in front of the equals operator, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align=right] {} }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align= right] {} }`,
		},
		{
			description: `no space in front of the equals operator, in front of a descendant selector`,
			code: `[target=_blank] .foo { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, in front of a descendant selector`,
			code: `[target= _blank] .foo { }`,
		},
		{
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child(1) { }`,
		},
		{
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child( 1) { }`,
		},
		{
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child(1 ) { }`,
		},
		{
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden=false]:nth-child( 1 ) { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child(1) { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child( 1) { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child(1 ) { }`,
		},
		{
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden= false]:nth-child( 1 ) { }`,
		},
		{
			description: `no space in front of the operator of either attribute selector, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
		},
		{
			description: `no space in front of the operator of either attribute selector, a space after the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden=false] a { }`,
		},
		{
			description: `no space in front of the operator of either attribute selector, a space after the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden= false] a { }`,
		},
		{
			description: `no space in front of the operator of either attribute selector, a space after each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
		},
		{
			description: `an attribute selector with no value, in a rule that carries a declaration`,
			code: `[target] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, a space inside the closing bracket, in a rule that carries a declaration`,
			code: `[target ] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, a space inside the opening bracket, in a rule that carries a declaration`,
			code: `[ target] { content: " " }`,
		},
		{
			description: `an attribute selector with no value, spaces inside both brackets, in a rule that carries a declaration`,
			code: `[ target ] { content: " " }`,
		},
	],

	reject: [
		{
			// The selector parser reads a backslash in front of a tab as no escape, and the fix wrote over the tab
			description: `a space in front of the operator behind an escaped tab, which is a character of the name`,
			code: `[a\\\t =b] {}`,
			fixed: `[a\\\t=b] {}`,
			line: 1,
			column: 6,
			message: messages.rejectedBefore(`=`),
		},
		{
			// Pins the refusal of a write behind a backslash the character it escapes would change behind
			description: `a backslash ending the attribute in front of a line break and the operator, which the write would turn into an escaped operator, so the warning stands`,
			code: `[a\\\n=b] {}`,
			fixed: `[a\\\n=b] {}`,
			line: 2,
			column: 1,
			message: messages.rejectedBefore(`=`),
		},
		{
			// The parser hands an attribute opening a selector of a list the whitespace in front of it, and its print opens on that whitespace
			description: `a space in front of the operator of an attribute standing behind a space inside the parentheses of a negation`,
			code: `a:not( [a =b] ) {}`,
			fixed: `a:not( [a=b] ) {}`,
			line: 1,
			column: 11,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `the same attributes in a list, one behind a line break and one behind a comma`,
			code: `a:is(\n\t[a =b], [c =d]\n) {}`,
			fixed: `a:is(\n\t[a=b], [c=d]\n) {}`,
			warnings: [
				{
					line: 2,
					column: 5,
					message: messages.rejectedBefore(`=`),
				},
				{
					line: 2,
					column: 13,
					message: messages.rejectedBefore(`=`),
				},
			],
		},
		{
			description: `a space in front of the equals operator`,
			code: `[target =_blank] { }`,
			fixed: `[target=_blank] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it`,
			code: `[target = _blank] { }`,
			fixed: `[target= _blank] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space inside the closing bracket`,
			code: `[target =_blank ] { }`,
			fixed: `[target=_blank ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it and a space inside the closing bracket`,
			code: `[target = _blank ] { }`,
			fixed: `[target= _blank ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space inside the opening bracket`,
			code: `[ target =_blank] { }`,
			fixed: `[ target=_blank] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it and a space inside the opening bracket`,
			code: `[ target = _blank] { }`,
			fixed: `[ target= _blank] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, spaces inside both brackets`,
			code: `[ target =_blank ] { }`,
			fixed: `[ target=_blank ] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it and spaces inside both brackets`,
			code: `[ target = _blank ] { }`,
			fixed: `[ target= _blank ] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes`,
			code: `[target ='_blank'] { }`,
			fixed: `[target='_blank'] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it and the value in apostrophes`,
			code: `[target = '_blank'] { }`,
			fixed: `[target= '_blank'] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space opening it`,
			code: `[target =' _blank'] { }`,
			fixed: `[target=' _blank'] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes and a space inside the closing bracket`,
			code: `[target ='_blank' ] { }`,
			fixed: `[target='_blank' ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space closing it`,
			code: `[target ='_blank '] { }`,
			fixed: `[target='_blank '] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and a space inside the closing bracket`,
			code: `[target = '_blank' ] { }`,
			fixed: `[target= '_blank' ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space at each end of it`,
			code: `[target =' _blank '] { }`,
			fixed: `[target=' _blank '] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target ='_blank'] { }`,
			fixed: `[ target='_blank'] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and a space inside the opening bracket`,
			code: `[ target = '_blank'] { }`,
			fixed: `[ target= '_blank'] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
			code: `[ target =' _blank'] { }`,
			fixed: `[ target=' _blank'] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes and spaces inside both brackets`,
			code: `[ target ='_blank' ] { }`,
			fixed: `[ target='_blank' ] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
			code: `[ target ='_blank '] { }`,
			fixed: `[ target='_blank '] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and spaces inside both brackets`,
			code: `[ target = '_blank' ] { }`,
			fixed: `[ target= '_blank' ] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
			code: `[ target =' _blank '] { }`,
			fixed: `[ target=' _blank '] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks`,
			code: `[target ="_blank"] { }`,
			fixed: `[target="_blank"] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it and the value in quotation marks`,
			code: `[target = "_blank"] { }`,
			fixed: `[target= "_blank"] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space opening it`,
			code: `[target =" _blank"] { }`,
			fixed: `[target=" _blank"] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks and a space inside the closing bracket`,
			code: `[target ="_blank" ] { }`,
			fixed: `[target="_blank" ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space closing it`,
			code: `[target ="_blank "] { }`,
			fixed: `[target="_blank "] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and a space inside the closing bracket`,
			code: `[target = "_blank" ] { }`,
			fixed: `[target= "_blank" ] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space at each end of it`,
			code: `[target =" _blank "] { }`,
			fixed: `[target=" _blank "] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target ="_blank"] { }`,
			fixed: `[ target="_blank"] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and a space inside the opening bracket`,
			code: `[ target = "_blank"] { }`,
			fixed: `[ target= "_blank"] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
			code: `[ target =" _blank"] { }`,
			fixed: `[ target=" _blank"] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks and spaces inside both brackets`,
			code: `[ target ="_blank" ] { }`,
			fixed: `[ target="_blank" ] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
			code: `[ target ="_blank "] { }`,
			fixed: `[ target="_blank "] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and spaces inside both brackets`,
			code: `[ target = "_blank" ] { }`,
			fixed: `[ target= "_blank" ] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
			code: `[ target =" _blank "] { }`,
			fixed: `[ target=" _blank "] { }`,
			line: 1,
			column: 10,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the whitespace-list operator`,
			code: `[title ~=flower] { }`,
			fixed: `[title~=flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedBefore(`~=`),
		},
		{
			description: `a space in front of the whitespace-list operator, a space after it`,
			code: `[title ~= flower] { }`,
			fixed: `[title~= flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedBefore(`~=`),
		},
		{
			description: `a space in front of the hyphen-list operator`,
			code: `[title |=flower] { }`,
			fixed: `[title|=flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedBefore(`|=`),
		},
		{
			description: `a space in front of the hyphen-list operator, a space after it`,
			code: `[title |= flower] { }`,
			fixed: `[title|= flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedBefore(`|=`),
		},
		{
			description: `a space in front of the prefix operator`,
			code: `[title ^=flower] { }`,
			fixed: `[title^=flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedBefore(`^=`),
		},
		{
			description: `a space in front of the prefix operator, a space after it`,
			code: `[title ^= flower] { }`,
			fixed: `[title^= flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedBefore(`^=`),
		},
		{
			description: `a space in front of the suffix operator`,
			code: `[title $=flower] { }`,
			fixed: `[title$=flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedBefore(`$=`),
		},
		{
			description: `a space in front of the suffix operator, a space after it`,
			code: `[title $= flower] { }`,
			fixed: `[title$= flower] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedBefore(`$=`),
		},
		{
			description: `a space in front of the substring operator, behind a type selector`,
			code: `a[href *=w3schools] { }`,
			fixed: `a[href*=w3schools] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedBefore(`*=`),
		},
		{
			description: `a space in front of the substring operator, a space after it, behind a type selector`,
			code: `a[href *= w3schools] { }`,
			fixed: `a[href*= w3schools] { }`,
			line: 1,
			column: 8,
			message: messages.rejectedBefore(`*=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's`,
			code: `img[alt ~=person][src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`~=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the first's`,
			code: `img[alt ~= person][src*=lorem] { }`,
			fixed: `img[alt~= person][src*=lorem] { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`~=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the second's`,
			code: `img[alt~=person][src *= lorem] { }`,
			fixed: `img[alt~=person][src*= lorem] { }`,
			line: 1,
			column: 22,
			message: messages.rejectedBefore(`*=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after each of them`,
			code: `img[alt~= person][src *= lorem] { }`,
			fixed: `img[alt~= person][src*= lorem] { }`,
			line: 1,
			column: 23,
			message: messages.rejectedBefore(`*=`),
		},
		{
			description: `a space in front of the equals operator, in front of a pseudo-class`,
			code: `[target =_blank]:hover { }`,
			fixed: `[target=_blank]:hover { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, in front of a pseudo-class`,
			code: `[target = _blank]:hover { }`,
			fixed: `[target= _blank]:hover { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, in front of a pseudo-element`,
			code: `[target =_blank]::before { }`,
			fixed: `[target=_blank]::before { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, in front of a pseudo-element`,
			code: `[target = _blank]::before { }`,
			fixed: `[target= _blank]::before { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, behind a type selector`,
			code: `option[data-hidden =true] { }`,
			fixed: `option[data-hidden=true] { }`,
			line: 1,
			column: 20,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, behind a type selector`,
			code: `option[data-hidden = true] { }`,
			fixed: `option[data-hidden= true] { }`,
			line: 1,
			column: 20,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align =right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			line: 1,
			column: 50,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, inside a media query`,
			code: `@media screen and (max-width: 480px) { img[align = right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align= right] {} }`,
			line: 1,
			column: 50,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, in front of a descendant selector`,
			code: `[target =_blank] .foo { }`,
			fixed: `[target=_blank] .foo { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, in front of a descendant selector`,
			code: `[target = _blank] .foo { }`,
			fixed: `[target= _blank] .foo { }`,
			line: 1,
			column: 9,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child(1) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1 ) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden =false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child(1) { }`,
			fixed: `li[aria-hidden= false]:nth-child(1) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden= false]:nth-child( 1) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden= false]:nth-child(1 ) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			code: `li[aria-hidden = false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden= false]:nth-child( 1 ) { }`,
			line: 1,
			column: 16,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 19,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 43,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 19,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the first's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden=false] a { }`,
			line: 1,
			column: 44,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden =false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden= false] a { }`,
			line: 1,
			column: 19,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the second's, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden=false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden= false] a { }`,
			line: 1,
			column: 43,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			line: 1,
			column: 19,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden= false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			line: 1,
			column: 44,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a space in front of the operator of each of the two attribute selectors, a space after each of them, the two selectors joined by a sibling combinator`,
			code: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			warnings: [
				{
					line: 1,
					column: 19,
					message: messages.rejectedBefore(`=`),
				},
				{
					line: 1,
					column: 45,
					message: messages.rejectedBefore(`=`),
				},
			],
		},
		{
			description: `a comment standing in front of the space the option forbids`,
			code: `[target/**/ ="_blank"] { }`,
			fixed: `[target/**/="_blank"] { }`,
			line: 1,
			column: 13,
			message: messages.rejectedBefore(`=`),
		},
		{
			description: `a comment standing between two spaces, one of them the space the option forbids`,
			code: `[target /**/ ="_blank"] { }`,
			fixed: `[target /**/="_blank"] { }`,
			line: 1,
			column: 14,
			message: messages.rejectedBefore(`=`),
		},
	],
})
