import { messages, ruleName } from "./index.js"

const testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`always`],

	accept: [
		{
			code: `.foo { }`,
			description: `a selector with no attribute in it`,
		},
		{
			code: `[target] { }`,
			description: `an attribute selector with no value`,
		},
		{
			code: `[ target] { }`,
			description: `an attribute selector with no value, a space inside the opening bracket`,
		},
		{
			code: `[target ] { }`,
			description: `an attribute selector with no value, a space inside the closing bracket`,
		},
		{
			code: `[ target ] { }`,
			description: `an attribute selector with no value, spaces inside both brackets`,
		},
		{
			code: `[target =_blank] { }`,
			description: `a space in front of the equals operator`,
		},
		{
			code: `[target = _blank] { }`,
			description: `a space in front of the equals operator, a space after it`,
		},
		{
			code: `[target =_blank ] { }`,
			description: `a space in front of the equals operator, a space inside the closing bracket`,
		},
		{
			code: `[target = _blank ] { }`,
			description: `a space in front of the equals operator, a space after it and a space inside the closing bracket`,
		},
		{
			code: `[ target =_blank] { }`,
			description: `a space in front of the equals operator, a space inside the opening bracket`,
		},
		{
			code: `[ target = _blank] { }`,
			description: `a space in front of the equals operator, a space after it and a space inside the opening bracket`,
		},
		{
			code: `[ target =_blank ] { }`,
			description: `a space in front of the equals operator, spaces inside both brackets`,
		},
		{
			code: `[ target = _blank ] { }`,
			description: `a space in front of the equals operator, a space after it and spaces inside both brackets`,
		},
		{
			code: `[target ='_blank'] { }`,
			description: `a space in front of the equals operator, the value in apostrophes`,
		},
		{
			code: `[target = '_blank'] { }`,
			description: `a space in front of the equals operator, a space after it and the value in apostrophes`,
		},
		{
			code: `[target =' _blank'] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space opening it`,
		},
		{
			code: `[target ='_blank' ] { }`,
			description: `a space in front of the equals operator, the value in apostrophes and a space inside the closing bracket`,
		},
		{
			code: `[target ='_blank '] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space closing it`,
		},
		{
			code: `[target = '_blank' ] { }`,
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and a space inside the closing bracket`,
		},
		{
			code: `[target =' _blank '] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space at each end of it`,
		},
		{
			code: `[ target ='_blank'] { }`,
			description: `a space in front of the equals operator, the value in apostrophes and a space inside the opening bracket`,
		},
		{
			code: `[ target = '_blank'] { }`,
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and a space inside the opening bracket`,
		},
		{
			code: `[ target =' _blank'] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
		},
		{
			code: `[ target ='_blank' ] { }`,
			description: `a space in front of the equals operator, the value in apostrophes and spaces inside both brackets`,
		},
		{
			code: `[ target ='_blank '] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
		},
		{
			code: `[ target = '_blank' ] { }`,
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and spaces inside both brackets`,
		},
		{
			code: `[ target =' _blank '] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
		},
		{
			code: `[target ="_blank"] { }`,
			description: `a space in front of the equals operator, the value in quotation marks`,
		},
		{
			code: `[target = "_blank"] { }`,
			description: `a space in front of the equals operator, a space after it and the value in quotation marks`,
		},
		{
			code: `[target =" _blank"] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space opening it`,
		},
		{
			code: `[target ="_blank" ] { }`,
			description: `a space in front of the equals operator, the value in quotation marks and a space inside the closing bracket`,
		},
		{
			code: `[target ="_blank "] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space closing it`,
		},
		{
			code: `[target = "_blank" ] { }`,
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and a space inside the closing bracket`,
		},
		{
			code: `[target =" _blank "] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space at each end of it`,
		},
		{
			code: `[ target ="_blank"] { }`,
			description: `a space in front of the equals operator, the value in quotation marks and a space inside the opening bracket`,
		},
		{
			code: `[ target = "_blank"] { }`,
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and a space inside the opening bracket`,
		},
		{
			code: `[ target =" _blank"] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
		},
		{
			code: `[ target ="_blank" ] { }`,
			description: `a space in front of the equals operator, the value in quotation marks and spaces inside both brackets`,
		},
		{
			code: `[ target ="_blank "] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
		},
		{
			code: `[ target = "_blank" ] { }`,
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and spaces inside both brackets`,
		},
		{
			code: `[ target =" _blank "] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
		},
		{
			code: `[title ~=flower] { }`,
			description: `a space in front of the whitespace-list operator`,
		},
		{
			code: `[title ~= flower] { }`,
			description: `a space in front of the whitespace-list operator, a space after it`,
		},
		{
			code: `[title |=flower] { }`,
			description: `a space in front of the hyphen-list operator`,
		},
		{
			code: `[title |= flower] { }`,
			description: `a space in front of the hyphen-list operator, a space after it`,
		},
		{
			code: `[title ^=flower] { }`,
			description: `a space in front of the prefix operator`,
		},
		{
			code: `[title ^= flower] { }`,
			description: `a space in front of the prefix operator, a space after it`,
		},
		{
			code: `[title $=flower] { }`,
			description: `a space in front of the suffix operator`,
		},
		{
			code: `[title $= flower] { }`,
			description: `a space in front of the suffix operator, a space after it`,
		},
		{
			code: `a[href *=w3schools] { }`,
			description: `a space in front of the substring operator, behind a type selector`,
		},
		{
			code: `a[href *= w3schools] { }`,
			description: `a space in front of the substring operator, a space after it, behind a type selector`,
		},
		{
			code: `img[alt ~=person][src *=lorem] { }`,
			description: `a space in front of the operator of each of the two attribute selectors`,
		},
		{
			code: `img[alt ~= person][src *=lorem] { }`,
			description: `a space in front of the operator of each of the two attribute selectors, a space after the first's`,
		},
		{
			code: `img[alt ~=person][src *= lorem] { }`,
			description: `a space in front of the operator of each of the two attribute selectors, a space after the second's`,
		},
		{
			code: `img[alt ~= person][src *= lorem] { }`,
			description: `a space in front of the operator of each of the two attribute selectors, a space after each of them`,
		},
		{
			code: `[target =_blank]:hover { }`,
			description: `a space in front of the equals operator, in front of a pseudo-class`,
		},
		{
			code: `[target = _blank]:hover { }`,
			description: `a space in front of the equals operator, a space after it, in front of a pseudo-class`,
		},
		{
			code: `[target =_blank]::before { }`,
			description: `a space in front of the equals operator, in front of a pseudo-element`,
		},
		{
			code: `[target = _blank]::before { }`,
			description: `a space in front of the equals operator, a space after it, in front of a pseudo-element`,
		},
		{
			code: `option[data-hidden =true] { }`,
			description: `a space in front of the equals operator, behind a type selector`,
		},
		{
			code: `option[data-hidden = true] { }`,
			description: `a space in front of the equals operator, a space after it, behind a type selector`,
		},
		{
			code: `option[dataHidden] { }`,
			description: `an attribute selector with no value, behind a type selector`,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align =right] {} }`,
			description: `a space in front of the equals operator, inside a media query`,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align = right] {} }`,
			description: `a space in front of the equals operator, a space after it, inside a media query`,
		},
		{
			code: `[target =_blank] .foo { }`,
			description: `a space in front of the equals operator, in front of a descendant selector`,
		},
		{
			code: `[target = _blank] .foo { }`,
			description: `a space in front of the equals operator, a space after it, in front of a descendant selector`,
		},
		{
			code: `li[aria-hidden =false]:nth-child(1) { }`,
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden =false]:nth-child( 1) { }`,
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden =false]:nth-child(1 ) { }`,
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden =false]:nth-child( 1 ) { }`,
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden = false]:nth-child(1) { }`,
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden = false]:nth-child( 1) { }`,
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden = false]:nth-child(1 ) { }`,
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden = false]:nth-child( 1 ) { }`,
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `ul li[aria-hidden =false] + li[aria-hidden =false] a { }`,
			description: `a space in front of the operator of each of the two attribute selectors, the two selectors joined by a sibling combinator`,
		},
		{
			code: `ul li[aria-hidden = false] + li[aria-hidden =false] a { }`,
			description: `a space in front of the operator of each of the two attribute selectors, a space after the first's, the two selectors joined by a sibling combinator`,
		},
		{
			code: `ul li[aria-hidden =false] + li[aria-hidden = false] a { }`,
			description: `a space in front of the operator of each of the two attribute selectors, a space after the second's, the two selectors joined by a sibling combinator`,
		},
		{
			code: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			description: `a space in front of the operator of each of the two attribute selectors, a space after each of them, the two selectors joined by a sibling combinator`,
		},
		{
			code: `[target] { content: " " }`,
			description: `an attribute selector with no value, in a rule that carries a declaration`,
		},
		{
			code: `[target ] { content: " " }`,
			description: `an attribute selector with no value, a space inside the closing bracket, in a rule that carries a declaration`,
		},
		{
			code: `[ target] { content: " " }`,
			description: `an attribute selector with no value, a space inside the opening bracket, in a rule that carries a declaration`,
		},
		{
			code: `[ target ] { content: " " }`,
			description: `an attribute selector with no value, spaces inside both brackets, in a rule that carries a declaration`,
		},
		{
			code: `:root { --foo: 1px; }`,
			description: `a custom property under the root selector`,
		},
		{
			code: `html { --foo: 1px; }`,
			description: `a custom property under a type selector`,
		},
		{
			code: `:root { --custom-property-set: {} }`,
			description: `a custom property set under the root selector`,
		},
		{
			code: `html { --custom-property-set: {} }`,
			description: `a custom property set under a type selector`,
		},
		{
			code: `a[b=#{c}] { }`,
			description: `an attribute selector the parser cannot read`,
		},
	],

	reject: [
		{
			code: `[target=_blank] { }`,
			fixed: `[target =_blank] { }`,
			description: `no space in front of the equals operator`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target= _blank] { }`,
			fixed: `[target = _blank] { }`,
			description: `no space in front of the equals operator, a space after it`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target=_blank ] { }`,
			fixed: `[target =_blank ] { }`,
			description: `no space in front of the equals operator, a space inside the closing bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target= _blank ] { }`,
			fixed: `[target = _blank ] { }`,
			description: `no space in front of the equals operator, a space after it and a space inside the closing bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[ target=_blank] { }`,
			fixed: `[ target =_blank] { }`,
			description: `no space in front of the equals operator, a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target= _blank] { }`,
			fixed: `[ target = _blank] { }`,
			description: `no space in front of the equals operator, a space after it and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target=_blank ] { }`,
			fixed: `[ target =_blank ] { }`,
			description: `no space in front of the equals operator, spaces inside both brackets`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target= _blank ] { }`,
			fixed: `[ target = _blank ] { }`,
			description: `no space in front of the equals operator, a space after it and spaces inside both brackets`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target='_blank'] { }`,
			fixed: `[target ='_blank'] { }`,
			description: `no space in front of the equals operator, the value in apostrophes`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target= '_blank'] { }`,
			fixed: `[target = '_blank'] { }`,
			description: `no space in front of the equals operator, a space after it and the value in apostrophes`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target=' _blank'] { }`,
			fixed: `[target =' _blank'] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space opening it`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target='_blank' ] { }`,
			fixed: `[target ='_blank' ] { }`,
			description: `no space in front of the equals operator, the value in apostrophes and a space inside the closing bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target='_blank '] { }`,
			fixed: `[target ='_blank '] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space closing it`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target= '_blank' ] { }`,
			fixed: `[target = '_blank' ] { }`,
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and a space inside the closing bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target=' _blank '] { }`,
			fixed: `[target =' _blank '] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space at each end of it`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[ target='_blank'] { }`,
			fixed: `[ target ='_blank'] { }`,
			description: `no space in front of the equals operator, the value in apostrophes and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target= '_blank'] { }`,
			fixed: `[ target = '_blank'] { }`,
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target=' _blank'] { }`,
			fixed: `[ target =' _blank'] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target='_blank' ] { }`,
			fixed: `[ target ='_blank' ] { }`,
			description: `no space in front of the equals operator, the value in apostrophes and spaces inside both brackets`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target='_blank '] { }`,
			fixed: `[ target ='_blank '] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target= '_blank' ] { }`,
			fixed: `[ target = '_blank' ] { }`,
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and spaces inside both brackets`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target=' _blank '] { }`,
			fixed: `[ target =' _blank '] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target="_blank"] { }`,
			fixed: `[target ="_blank"] { }`,
			description: `no space in front of the equals operator, the value in quotation marks`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target= "_blank"] { }`,
			fixed: `[target = "_blank"] { }`,
			description: `no space in front of the equals operator, a space after it and the value in quotation marks`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target=" _blank"] { }`,
			fixed: `[target =" _blank"] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space opening it`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target="_blank" ] { }`,
			fixed: `[target ="_blank" ] { }`,
			description: `no space in front of the equals operator, the value in quotation marks and a space inside the closing bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target="_blank "] { }`,
			fixed: `[target ="_blank "] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space closing it`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target= "_blank" ] { }`,
			fixed: `[target = "_blank" ] { }`,
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and a space inside the closing bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target=" _blank "] { }`,
			fixed: `[target =" _blank "] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space at each end of it`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[ target="_blank"] { }`,
			fixed: `[ target ="_blank"] { }`,
			description: `no space in front of the equals operator, the value in quotation marks and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target= "_blank"] { }`,
			fixed: `[ target = "_blank"] { }`,
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target=" _blank"] { }`,
			fixed: `[ target =" _blank"] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target="_blank" ] { }`,
			fixed: `[ target ="_blank" ] { }`,
			description: `no space in front of the equals operator, the value in quotation marks and spaces inside both brackets`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target="_blank "] { }`,
			fixed: `[ target ="_blank "] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target= "_blank" ] { }`,
			fixed: `[ target = "_blank" ] { }`,
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and spaces inside both brackets`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target=" _blank "] { }`,
			fixed: `[ target =" _blank "] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[title~=flower] { }`,
			fixed: `[title ~=flower] { }`,
			description: `no space in front of the whitespace-list operator`,
			message: messages.expectedBefore(`~=`),
			line: 1,
			column: 7,
		},
		{
			code: `[title~= flower] { }`,
			fixed: `[title ~= flower] { }`,
			description: `no space in front of the whitespace-list operator, a space after it`,
			message: messages.expectedBefore(`~=`),
			line: 1,
			column: 7,
		},
		{
			code: `[title|=flower] { }`,
			fixed: `[title |=flower] { }`,
			description: `no space in front of the hyphen-list operator`,
			message: messages.expectedBefore(`|=`),
			line: 1,
			column: 7,
		},
		{
			code: `[title|= flower] { }`,
			fixed: `[title |= flower] { }`,
			description: `no space in front of the hyphen-list operator, a space after it`,
			message: messages.expectedBefore(`|=`),
			line: 1,
			column: 7,
		},
		{
			code: `[title^=flower] { }`,
			fixed: `[title ^=flower] { }`,
			description: `no space in front of the prefix operator`,
			message: messages.expectedBefore(`^=`),
			line: 1,
			column: 7,
		},
		{
			code: `[title^= flower] { }`,
			fixed: `[title ^= flower] { }`,
			description: `no space in front of the prefix operator, a space after it`,
			message: messages.expectedBefore(`^=`),
			line: 1,
			column: 7,
		},
		{
			code: `[title$=flower] { }`,
			fixed: `[title $=flower] { }`,
			description: `no space in front of the suffix operator`,
			message: messages.expectedBefore(`$=`),
			line: 1,
			column: 7,
		},
		{
			code: `[title$= flower] { }`,
			fixed: `[title $= flower] { }`,
			description: `no space in front of the suffix operator, a space after it`,
			message: messages.expectedBefore(`$=`),
			line: 1,
			column: 7,
		},
		{
			code: `a[href*=w3schools] { }`,
			fixed: `a[href *=w3schools] { }`,
			description: `no space in front of the substring operator, behind a type selector`,
			message: messages.expectedBefore(`*=`),
			line: 1,
			column: 7,
		},
		{
			code: `a[href*= w3schools] { }`,
			fixed: `a[href *= w3schools] { }`,
			description: `no space in front of the substring operator, a space after it, behind a type selector`,
			message: messages.expectedBefore(`*=`),
			line: 1,
			column: 7,
		},
		{
			code: `img[alt~=person][src *=lorem] { }`,
			fixed: `img[alt ~=person][src *=lorem] { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's`,
			message: messages.expectedBefore(`~=`),
			line: 1,
			column: 8,
		},
		{
			code: `img[alt~= person][src *=lorem] { }`,
			fixed: `img[alt ~= person][src *=lorem] { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the first's`,
			message: messages.expectedBefore(`~=`),
			line: 1,
			column: 8,
		},
		{
			code: `img[alt ~=person][src*= lorem] { }`,
			fixed: `img[alt ~=person][src *= lorem] { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the second's`,
			message: messages.expectedBefore(`*=`),
			line: 1,
			column: 22,
		},
		{
			code: `img[alt ~= person][src*= lorem] { }`,
			fixed: `img[alt ~= person][src *= lorem] { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after each of them`,
			message: messages.expectedBefore(`*=`),
			line: 1,
			column: 23,
		},
		{
			code: `[target=_blank]:hover { }`,
			fixed: `[target =_blank]:hover { }`,
			description: `no space in front of the equals operator, in front of a pseudo-class`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target= _blank]:hover { }`,
			fixed: `[target = _blank]:hover { }`,
			description: `no space in front of the equals operator, a space after it, in front of a pseudo-class`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target=_blank]::before { }`,
			fixed: `[target =_blank]::before { }`,
			description: `no space in front of the equals operator, in front of a pseudo-element`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target= _blank]::before { }`,
			fixed: `[target = _blank]::before { }`,
			description: `no space in front of the equals operator, a space after it, in front of a pseudo-element`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `option[data-hidden=true] { }`,
			fixed: `option[data-hidden =true] { }`,
			description: `no space in front of the equals operator, behind a type selector`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 19,
		},
		{
			code: `option[data-hidden= true] { }`,
			fixed: `option[data-hidden = true] { }`,
			description: `no space in front of the equals operator, a space after it, behind a type selector`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 19,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align =right] {} }`,
			description: `no space in front of the equals operator, inside a media query`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 49,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align= right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align = right] {} }`,
			description: `no space in front of the equals operator, a space after it, inside a media query`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 49,
		},
		{
			code: `[target=_blank] .foo { }`,
			fixed: `[target =_blank] .foo { }`,
			description: `no space in front of the equals operator, in front of a descendant selector`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `[target= _blank] .foo { }`,
			fixed: `[target = _blank] .foo { }`,
			description: `no space in front of the equals operator, a space after it, in front of a descendant selector`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 8,
		},
		{
			code: `li[aria-hidden=false]:nth-child(1) { }`,
			fixed: `li[aria-hidden =false]:nth-child(1) { }`,
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 15,
		},
		{
			code: `li[aria-hidden=false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden =false]:nth-child( 1) { }`,
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 15,
		},
		{
			code: `li[aria-hidden=false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden =false]:nth-child(1 ) { }`,
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 15,
		},
		{
			code: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden =false]:nth-child( 1 ) { }`,
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 15,
		},
		{
			code: `li[aria-hidden= false]:nth-child(1) { }`,
			fixed: `li[aria-hidden = false]:nth-child(1) { }`,
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 15,
		},
		{
			code: `li[aria-hidden= false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden = false]:nth-child( 1) { }`,
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 15,
		},
		{
			code: `li[aria-hidden= false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden = false]:nth-child(1 ) { }`,
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 15,
		},
		{
			code: `li[aria-hidden= false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden = false]:nth-child( 1 ) { }`,
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 15,
		},
		{
			code: `ul li[aria-hidden=false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden =false] a { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, the two selectors joined by a sibling combinator`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 18,
		},
		{
			code: `ul li[aria-hidden =false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden =false] a { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, the two selectors joined by a sibling combinator`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 43,
		},
		{
			code: `ul li[aria-hidden= false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden =false] a { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the first's, the two selectors joined by a sibling combinator`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 18,
		},
		{
			code: `ul li[aria-hidden = false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden =false] a { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the first's, the two selectors joined by a sibling combinator`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 44,
		},
		{
			code: `ul li[aria-hidden=false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden = false] a { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the second's, the two selectors joined by a sibling combinator`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 18,
		},
		{
			code: `ul li[aria-hidden =false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden =false] + li[aria-hidden = false] a { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the second's, the two selectors joined by a sibling combinator`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 43,
		},
		{
			code: `ul li[aria-hidden= false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after each of them, the two selectors joined by a sibling combinator`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 18,
		},
		{
			code: `ul li[aria-hidden = false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after each of them, the two selectors joined by a sibling combinator`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 44,
		},
		{
			code: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			description: `no space in front of the operator of either attribute selector, a space after each of them, the two selectors joined by a sibling combinator`,
			warnings: [
				{
					message: messages.expectedBefore(`=`),
					line: 1,
					column: 18,
				},
				{
					message: messages.expectedBefore(`=`),
					line: 1,
					column: 43,
				},
			],
		},
		{
			code: `[target/**/="_blank"] { }`,
			fixed: `[target/**/ ="_blank"] { }`,
			description: `a comment standing where the space the option asks for would go`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 12,
		},
		{
			code: `[target /**/="_blank"] { }`,
			fixed: `[target /**/ ="_blank"] { }`,
			description: `a comment standing between the space and the operator`,
			message: messages.expectedBefore(`=`),
			line: 1,
			column: 13,
		},
	],
})

testRule({
	ruleName,
	config: [`never`],

	accept: [
		{
			code: `.foo { }`,
			description: `a selector with no attribute in it`,
		},
		{
			code: `[target] { }`,
			description: `an attribute selector with no value`,
		},
		{
			code: `[ target] { }`,
			description: `an attribute selector with no value, a space inside the opening bracket`,
		},
		{
			code: `[target ] { }`,
			description: `an attribute selector with no value, a space inside the closing bracket`,
		},
		{
			code: `[ target ] { }`,
			description: `an attribute selector with no value, spaces inside both brackets`,
		},
		{
			code: `[target=_blank] { }`,
			description: `no space in front of the equals operator`,
		},
		{
			code: `[target= _blank] { }`,
			description: `no space in front of the equals operator, a space after it`,
		},
		{
			code: `[target=_blank ] { }`,
			description: `no space in front of the equals operator, a space inside the closing bracket`,
		},
		{
			code: `[target= _blank ] { }`,
			description: `no space in front of the equals operator, a space after it and a space inside the closing bracket`,
		},
		{
			code: `[ target=_blank] { }`,
			description: `no space in front of the equals operator, a space inside the opening bracket`,
		},
		{
			code: `[ target= _blank] { }`,
			description: `no space in front of the equals operator, a space after it and a space inside the opening bracket`,
		},
		{
			code: `[ target=_blank ] { }`,
			description: `no space in front of the equals operator, spaces inside both brackets`,
		},
		{
			code: `[ target= _blank ] { }`,
			description: `no space in front of the equals operator, a space after it and spaces inside both brackets`,
		},
		{
			code: `[target='_blank'] { }`,
			description: `no space in front of the equals operator, the value in apostrophes`,
		},
		{
			code: `[target= '_blank'] { }`,
			description: `no space in front of the equals operator, a space after it and the value in apostrophes`,
		},
		{
			code: `[target=' _blank'] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space opening it`,
		},
		{
			code: `[target='_blank' ] { }`,
			description: `no space in front of the equals operator, the value in apostrophes and a space inside the closing bracket`,
		},
		{
			code: `[target='_blank '] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space closing it`,
		},
		{
			code: `[target= '_blank' ] { }`,
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and a space inside the closing bracket`,
		},
		{
			code: `[target=' _blank '] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space at each end of it`,
		},
		{
			code: `[ target='_blank'] { }`,
			description: `no space in front of the equals operator, the value in apostrophes and a space inside the opening bracket`,
		},
		{
			code: `[ target= '_blank'] { }`,
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and a space inside the opening bracket`,
		},
		{
			code: `[ target=' _blank'] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
		},
		{
			code: `[ target='_blank' ] { }`,
			description: `no space in front of the equals operator, the value in apostrophes and spaces inside both brackets`,
		},
		{
			code: `[ target='_blank '] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
		},
		{
			code: `[ target= '_blank' ] { }`,
			description: `no space in front of the equals operator, a space after it, the value in apostrophes and spaces inside both brackets`,
		},
		{
			code: `[ target=' _blank '] { }`,
			description: `no space in front of the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
		},
		{
			code: `[target="_blank"] { }`,
			description: `no space in front of the equals operator, the value in quotation marks`,
		},
		{
			code: `[target= "_blank"] { }`,
			description: `no space in front of the equals operator, a space after it and the value in quotation marks`,
		},
		{
			code: `[target=" _blank"] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space opening it`,
		},
		{
			code: `[target="_blank" ] { }`,
			description: `no space in front of the equals operator, the value in quotation marks and a space inside the closing bracket`,
		},
		{
			code: `[target="_blank "] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space closing it`,
		},
		{
			code: `[target= "_blank" ] { }`,
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and a space inside the closing bracket`,
		},
		{
			code: `[target=" _blank "] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space at each end of it`,
		},
		{
			code: `[ target="_blank"] { }`,
			description: `no space in front of the equals operator, the value in quotation marks and a space inside the opening bracket`,
		},
		{
			code: `[ target= "_blank"] { }`,
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and a space inside the opening bracket`,
		},
		{
			code: `[ target=" _blank"] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
		},
		{
			code: `[ target="_blank" ] { }`,
			description: `no space in front of the equals operator, the value in quotation marks and spaces inside both brackets`,
		},
		{
			code: `[ target="_blank "] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
		},
		{
			code: `[ target= "_blank" ] { }`,
			description: `no space in front of the equals operator, a space after it, the value in quotation marks and spaces inside both brackets`,
		},
		{
			code: `[ target=" _blank "] { }`,
			description: `no space in front of the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
		},
		{
			code: `[title~=flower] { }`,
			description: `no space in front of the whitespace-list operator`,
		},
		{
			code: `[title~= flower] { }`,
			description: `no space in front of the whitespace-list operator, a space after it`,
		},
		{
			code: `[title|=flower] { }`,
			description: `no space in front of the hyphen-list operator`,
		},
		{
			code: `[title|= flower] { }`,
			description: `no space in front of the hyphen-list operator, a space after it`,
		},
		{
			code: `[title^=flower] { }`,
			description: `no space in front of the prefix operator`,
		},
		{
			code: `[title^= flower] { }`,
			description: `no space in front of the prefix operator, a space after it`,
		},
		{
			code: `[title$=flower] { }`,
			description: `no space in front of the suffix operator`,
		},
		{
			code: `[title$= flower] { }`,
			description: `no space in front of the suffix operator, a space after it`,
		},
		{
			code: `a[href*=w3schools] { }`,
			description: `no space in front of the substring operator, behind a type selector`,
		},
		{
			code: `a[href*= w3schools] { }`,
			description: `no space in front of the substring operator, a space after it, behind a type selector`,
		},
		{
			code: `img[alt~=person][src*=lorem] { }`,
			description: `no space in front of the operator of either attribute selector`,
		},
		{
			code: `img[alt~= person][src*=lorem] { }`,
			description: `no space in front of the operator of either attribute selector, a space after the first's`,
		},
		{
			code: `img[alt~=person][src*= lorem] { }`,
			description: `no space in front of the operator of either attribute selector, a space after the second's`,
		},
		{
			code: `img[alt~= person][src*= lorem] { }`,
			description: `no space in front of the operator of either attribute selector, a space after each of them`,
		},
		{
			code: `[target=_blank]:hover { }`,
			description: `no space in front of the equals operator, in front of a pseudo-class`,
		},
		{
			code: `[target= _blank]:hover { }`,
			description: `no space in front of the equals operator, a space after it, in front of a pseudo-class`,
		},
		{
			code: `[target=_blank]::before { }`,
			description: `no space in front of the equals operator, in front of a pseudo-element`,
		},
		{
			code: `[target= _blank]::before { }`,
			description: `no space in front of the equals operator, a space after it, in front of a pseudo-element`,
		},
		{
			code: `option[data-hidden=true] { }`,
			description: `no space in front of the equals operator, behind a type selector`,
		},
		{
			code: `option[data-hidden= true] { }`,
			description: `no space in front of the equals operator, a space after it, behind a type selector`,
		},
		{
			code: `option[dataHidden] { }`,
			description: `an attribute selector with no value, behind a type selector`,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			description: `no space in front of the equals operator, inside a media query`,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align= right] {} }`,
			description: `no space in front of the equals operator, a space after it, inside a media query`,
		},
		{
			code: `[target=_blank] .foo { }`,
			description: `no space in front of the equals operator, in front of a descendant selector`,
		},
		{
			code: `[target= _blank] .foo { }`,
			description: `no space in front of the equals operator, a space after it, in front of a descendant selector`,
		},
		{
			code: `li[aria-hidden=false]:nth-child(1) { }`,
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden=false]:nth-child( 1) { }`,
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden=false]:nth-child(1 ) { }`,
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			description: `no space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden= false]:nth-child(1) { }`,
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden= false]:nth-child( 1) { }`,
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden= false]:nth-child(1 ) { }`,
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `li[aria-hidden= false]:nth-child( 1 ) { }`,
			description: `no space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
		},
		{
			code: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			description: `no space in front of the operator of either attribute selector, the two selectors joined by a sibling combinator`,
		},
		{
			code: `ul li[aria-hidden= false] + li[aria-hidden=false] a { }`,
			description: `no space in front of the operator of either attribute selector, a space after the first's, the two selectors joined by a sibling combinator`,
		},
		{
			code: `ul li[aria-hidden=false] + li[aria-hidden= false] a { }`,
			description: `no space in front of the operator of either attribute selector, a space after the second's, the two selectors joined by a sibling combinator`,
		},
		{
			code: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			description: `no space in front of the operator of either attribute selector, a space after each of them, the two selectors joined by a sibling combinator`,
		},
		{
			code: `[target] { content: " " }`,
			description: `an attribute selector with no value, in a rule that carries a declaration`,
		},
		{
			code: `[target ] { content: " " }`,
			description: `an attribute selector with no value, a space inside the closing bracket, in a rule that carries a declaration`,
		},
		{
			code: `[ target] { content: " " }`,
			description: `an attribute selector with no value, a space inside the opening bracket, in a rule that carries a declaration`,
		},
		{
			code: `[ target ] { content: " " }`,
			description: `an attribute selector with no value, spaces inside both brackets, in a rule that carries a declaration`,
		},
	],

	reject: [
		{
			code: `[target =_blank] { }`,
			fixed: `[target=_blank] { }`,
			description: `a space in front of the equals operator`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target = _blank] { }`,
			fixed: `[target= _blank] { }`,
			description: `a space in front of the equals operator, a space after it`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target =_blank ] { }`,
			fixed: `[target=_blank ] { }`,
			description: `a space in front of the equals operator, a space inside the closing bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target = _blank ] { }`,
			fixed: `[target= _blank ] { }`,
			description: `a space in front of the equals operator, a space after it and a space inside the closing bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target =_blank] { }`,
			fixed: `[ target=_blank] { }`,
			description: `a space in front of the equals operator, a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target = _blank] { }`,
			fixed: `[ target= _blank] { }`,
			description: `a space in front of the equals operator, a space after it and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target =_blank ] { }`,
			fixed: `[ target=_blank ] { }`,
			description: `a space in front of the equals operator, spaces inside both brackets`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target = _blank ] { }`,
			fixed: `[ target= _blank ] { }`,
			description: `a space in front of the equals operator, a space after it and spaces inside both brackets`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[target ='_blank'] { }`,
			fixed: `[target='_blank'] { }`,
			description: `a space in front of the equals operator, the value in apostrophes`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target = '_blank'] { }`,
			fixed: `[target= '_blank'] { }`,
			description: `a space in front of the equals operator, a space after it and the value in apostrophes`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target =' _blank'] { }`,
			fixed: `[target=' _blank'] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space opening it`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target ='_blank' ] { }`,
			fixed: `[target='_blank' ] { }`,
			description: `a space in front of the equals operator, the value in apostrophes and a space inside the closing bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target ='_blank '] { }`,
			fixed: `[target='_blank '] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space closing it`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target = '_blank' ] { }`,
			fixed: `[target= '_blank' ] { }`,
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and a space inside the closing bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target =' _blank '] { }`,
			fixed: `[target=' _blank '] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space at each end of it`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target ='_blank'] { }`,
			fixed: `[ target='_blank'] { }`,
			description: `a space in front of the equals operator, the value in apostrophes and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target = '_blank'] { }`,
			fixed: `[ target= '_blank'] { }`,
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target =' _blank'] { }`,
			fixed: `[ target=' _blank'] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space opening it and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target ='_blank' ] { }`,
			fixed: `[ target='_blank' ] { }`,
			description: `a space in front of the equals operator, the value in apostrophes and spaces inside both brackets`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target ='_blank '] { }`,
			fixed: `[ target='_blank '] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space closing it and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target = '_blank' ] { }`,
			fixed: `[ target= '_blank' ] { }`,
			description: `a space in front of the equals operator, a space after it, the value in apostrophes and spaces inside both brackets`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target =' _blank '] { }`,
			fixed: `[ target=' _blank '] { }`,
			description: `a space in front of the equals operator, the value in apostrophes with a space at each end of it and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[target ="_blank"] { }`,
			fixed: `[target="_blank"] { }`,
			description: `a space in front of the equals operator, the value in quotation marks`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target = "_blank"] { }`,
			fixed: `[target= "_blank"] { }`,
			description: `a space in front of the equals operator, a space after it and the value in quotation marks`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target =" _blank"] { }`,
			fixed: `[target=" _blank"] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space opening it`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target ="_blank" ] { }`,
			fixed: `[target="_blank" ] { }`,
			description: `a space in front of the equals operator, the value in quotation marks and a space inside the closing bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target ="_blank "] { }`,
			fixed: `[target="_blank "] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space closing it`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target = "_blank" ] { }`,
			fixed: `[target= "_blank" ] { }`,
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and a space inside the closing bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target =" _blank "] { }`,
			fixed: `[target=" _blank "] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space at each end of it`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[ target ="_blank"] { }`,
			fixed: `[ target="_blank"] { }`,
			description: `a space in front of the equals operator, the value in quotation marks and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target = "_blank"] { }`,
			fixed: `[ target= "_blank"] { }`,
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target =" _blank"] { }`,
			fixed: `[ target=" _blank"] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space opening it and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target ="_blank" ] { }`,
			fixed: `[ target="_blank" ] { }`,
			description: `a space in front of the equals operator, the value in quotation marks and spaces inside both brackets`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target ="_blank "] { }`,
			fixed: `[ target="_blank "] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space closing it and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target = "_blank" ] { }`,
			fixed: `[ target= "_blank" ] { }`,
			description: `a space in front of the equals operator, a space after it, the value in quotation marks and spaces inside both brackets`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[ target =" _blank "] { }`,
			fixed: `[ target=" _blank "] { }`,
			description: `a space in front of the equals operator, the value in quotation marks with a space at each end of it and a space inside the opening bracket`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 10,
		},
		{
			code: `[title ~=flower] { }`,
			fixed: `[title~=flower] { }`,
			description: `a space in front of the whitespace-list operator`,
			message: messages.rejectedBefore(`~=`),
			line: 1,
			column: 8,
		},
		{
			code: `[title ~= flower] { }`,
			fixed: `[title~= flower] { }`,
			description: `a space in front of the whitespace-list operator, a space after it`,
			message: messages.rejectedBefore(`~=`),
			line: 1,
			column: 8,
		},
		{
			code: `[title |=flower] { }`,
			fixed: `[title|=flower] { }`,
			description: `a space in front of the hyphen-list operator`,
			message: messages.rejectedBefore(`|=`),
			line: 1,
			column: 8,
		},
		{
			code: `[title |= flower] { }`,
			fixed: `[title|= flower] { }`,
			description: `a space in front of the hyphen-list operator, a space after it`,
			message: messages.rejectedBefore(`|=`),
			line: 1,
			column: 8,
		},
		{
			code: `[title ^=flower] { }`,
			fixed: `[title^=flower] { }`,
			description: `a space in front of the prefix operator`,
			message: messages.rejectedBefore(`^=`),
			line: 1,
			column: 8,
		},
		{
			code: `[title ^= flower] { }`,
			fixed: `[title^= flower] { }`,
			description: `a space in front of the prefix operator, a space after it`,
			message: messages.rejectedBefore(`^=`),
			line: 1,
			column: 8,
		},
		{
			code: `[title $=flower] { }`,
			fixed: `[title$=flower] { }`,
			description: `a space in front of the suffix operator`,
			message: messages.rejectedBefore(`$=`),
			line: 1,
			column: 8,
		},
		{
			code: `[title $= flower] { }`,
			fixed: `[title$= flower] { }`,
			description: `a space in front of the suffix operator, a space after it`,
			message: messages.rejectedBefore(`$=`),
			line: 1,
			column: 8,
		},
		{
			code: `a[href *=w3schools] { }`,
			fixed: `a[href*=w3schools] { }`,
			description: `a space in front of the substring operator, behind a type selector`,
			message: messages.rejectedBefore(`*=`),
			line: 1,
			column: 8,
		},
		{
			code: `a[href *= w3schools] { }`,
			fixed: `a[href*= w3schools] { }`,
			description: `a space in front of the substring operator, a space after it, behind a type selector`,
			message: messages.rejectedBefore(`*=`),
			line: 1,
			column: 8,
		},
		{
			code: `img[alt ~=person][src*=lorem] { }`,
			fixed: `img[alt~=person][src*=lorem] { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's`,
			message: messages.rejectedBefore(`~=`),
			line: 1,
			column: 9,
		},
		{
			code: `img[alt ~= person][src*=lorem] { }`,
			fixed: `img[alt~= person][src*=lorem] { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the first's`,
			message: messages.rejectedBefore(`~=`),
			line: 1,
			column: 9,
		},
		{
			code: `img[alt~=person][src *= lorem] { }`,
			fixed: `img[alt~=person][src*= lorem] { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the second's`,
			message: messages.rejectedBefore(`*=`),
			line: 1,
			column: 22,
		},
		{
			code: `img[alt~= person][src *= lorem] { }`,
			fixed: `img[alt~= person][src*= lorem] { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after each of them`,
			message: messages.rejectedBefore(`*=`),
			line: 1,
			column: 23,
		},
		{
			code: `[target =_blank]:hover { }`,
			fixed: `[target=_blank]:hover { }`,
			description: `a space in front of the equals operator, in front of a pseudo-class`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target = _blank]:hover { }`,
			fixed: `[target= _blank]:hover { }`,
			description: `a space in front of the equals operator, a space after it, in front of a pseudo-class`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target =_blank]::before { }`,
			fixed: `[target=_blank]::before { }`,
			description: `a space in front of the equals operator, in front of a pseudo-element`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target = _blank]::before { }`,
			fixed: `[target= _blank]::before { }`,
			description: `a space in front of the equals operator, a space after it, in front of a pseudo-element`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `option[data-hidden =true] { }`,
			fixed: `option[data-hidden=true] { }`,
			description: `a space in front of the equals operator, behind a type selector`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 20,
		},
		{
			code: `option[data-hidden = true] { }`,
			fixed: `option[data-hidden= true] { }`,
			description: `a space in front of the equals operator, a space after it, behind a type selector`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 20,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align =right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align=right] {} }`,
			description: `a space in front of the equals operator, inside a media query`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 50,
		},
		{
			code: `@media screen and (max-width: 480px) { img[align = right] {} }`,
			fixed: `@media screen and (max-width: 480px) { img[align= right] {} }`,
			description: `a space in front of the equals operator, a space after it, inside a media query`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 50,
		},
		{
			code: `[target =_blank] .foo { }`,
			fixed: `[target=_blank] .foo { }`,
			description: `a space in front of the equals operator, in front of a descendant selector`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `[target = _blank] .foo { }`,
			fixed: `[target= _blank] .foo { }`,
			description: `a space in front of the equals operator, a space after it, in front of a descendant selector`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 9,
		},
		{
			code: `li[aria-hidden =false]:nth-child(1) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1) { }`,
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 16,
		},
		{
			code: `li[aria-hidden =false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1) { }`,
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 16,
		},
		{
			code: `li[aria-hidden =false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child(1 ) { }`,
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 16,
		},
		{
			code: `li[aria-hidden =false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden=false]:nth-child( 1 ) { }`,
			description: `a space in front of the equals operator, behind a type selector, in front of a pseudo-class`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 16,
		},
		{
			code: `li[aria-hidden = false]:nth-child(1) { }`,
			fixed: `li[aria-hidden= false]:nth-child(1) { }`,
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 16,
		},
		{
			code: `li[aria-hidden = false]:nth-child( 1) { }`,
			fixed: `li[aria-hidden= false]:nth-child( 1) { }`,
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 16,
		},
		{
			code: `li[aria-hidden = false]:nth-child(1 ) { }`,
			fixed: `li[aria-hidden= false]:nth-child(1 ) { }`,
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 16,
		},
		{
			code: `li[aria-hidden = false]:nth-child( 1 ) { }`,
			fixed: `li[aria-hidden= false]:nth-child( 1 ) { }`,
			description: `a space in front of the equals operator, a space after it, behind a type selector, in front of a pseudo-class`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 16,
		},
		{
			code: `ul li[aria-hidden =false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, the two selectors joined by a sibling combinator`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 19,
		},
		{
			code: `ul li[aria-hidden=false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden=false] a { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, the two selectors joined by a sibling combinator`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 43,
		},
		{
			code: `ul li[aria-hidden = false] + li[aria-hidden=false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden=false] a { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the first's, the two selectors joined by a sibling combinator`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 19,
		},
		{
			code: `ul li[aria-hidden= false] + li[aria-hidden =false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden=false] a { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the first's, the two selectors joined by a sibling combinator`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 44,
		},
		{
			code: `ul li[aria-hidden =false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden= false] a { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after the second's, the two selectors joined by a sibling combinator`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 19,
		},
		{
			code: `ul li[aria-hidden=false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden=false] + li[aria-hidden= false] a { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after the second's, the two selectors joined by a sibling combinator`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 43,
		},
		{
			code: `ul li[aria-hidden = false] + li[aria-hidden= false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			description: `a space in front of the operator of the first attribute selector and none in front of the second's, a space after each of them, the two selectors joined by a sibling combinator`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 19,
		},
		{
			code: `ul li[aria-hidden= false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			description: `a space in front of the operator of the second attribute selector and none in front of the first's, a space after each of them, the two selectors joined by a sibling combinator`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 44,
		},
		{
			code: `ul li[aria-hidden = false] + li[aria-hidden = false] a { }`,
			fixed: `ul li[aria-hidden= false] + li[aria-hidden= false] a { }`,
			description: `a space in front of the operator of each of the two attribute selectors, a space after each of them, the two selectors joined by a sibling combinator`,
			warnings: [
				{
					message: messages.rejectedBefore(`=`),
					line: 1,
					column: 19,
				},
				{
					message: messages.rejectedBefore(`=`),
					line: 1,
					column: 45,
				},
			],
		},
		{
			code: `[target/**/ ="_blank"] { }`,
			fixed: `[target/**/="_blank"] { }`,
			description: `a comment standing in front of the space the option forbids`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 13,
		},
		{
			code: `[target /**/ ="_blank"] { }`,
			fixed: `[target /**/="_blank"] { }`,
			description: `a comment standing between two spaces, one of them the space the option forbids`,
			message: messages.rejectedBefore(`=`),
			line: 1,
			column: 14,
		},
	],
})

testRule({
	ruleName,
	config: [`never`],
	customSyntax: `postcss-scss`,

	reject: [
		{
			// https://github.com/stylelint-stylistic/stylelint-stylistic/issues/193
			code: `.a // c\n[t ='y'] {}`,
			fixed: `.a // c\n[t='y'] {}`,
			description: `a selector carrying an inline comment, whose fix reaches the copy the file spells, reported in the file's own coordinates`,
			message: messages.rejectedBefore(`=`),
			line: 2,
			column: 4,
		},
	],
})
