import { messages, ruleName } from "./index.js"

const testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`always`],

	accept: [
		{
			code: `a { --a: ; }`,
			description: `a custom property whose value is a single space`,
		},
		{
			code: `a { --a: ; color: red; }`,
			description: `the same custom property with a declaration behind it`,
		},
		{
			code: `a { color: pink }`,
			description: `a space behind the colon`,
		},
		{
			code: `a { color : pink }`,
			description: `spaces on both sides of the colon`,
		},
		{
			code: `a { color\n: pink }`,
			description: `a break in front of the colon and a space behind it`,
		},
		{
			code: `a { color\r\n: pink }`,
			description: `the same break spelled with a carriage return`,
		},
		{
			code: `$map:(key:value)`,
			description: `an SCSS map written on one line, whose inner colon opens no declaration`,
		},
		{
			code: `$list:('value1', 'value2')`,
			description: `an SCSS list written on one line`,
		},
		{
			code: `a { background: url(data:application/font-woff;...); }`,
			description: `a data URI, whose own colon opens no declaration either`,
		},
		{
			// https://github.com/stylelint-stylistic/stylelint-stylistic/issues/92
			code: `a { color/* https://foo.bar/ */: pink; }`,
			description: `comment with an URL, space after the declaration's own colon`,
		},
		{
			code: `a { --a: /*comment*/; }`,
			description: `a custom property holding nothing but a comment`,
		},
		{
			code: `a { --a: /*comment*/ }`,
			description: `the same custom property with no semicolon behind it`,
		},
		{
			code: `a { --a: /*comment*/ !important; }`,
			description: `the same comment with a flag behind it`,
		},
		{
			code: `a { --a: red /*comment*/; }`,
			description: `a value and a comment behind the colon`,
		},
		{
			code: `a { --a : /*comment*/ !important; }`,
			description: `the same comment and flag, with a space in front of the colon`,
		},
		{
			code: `a { --a\t: /*comment*/; }`,
			description: `the same comment behind a colon that stands behind a tab`,
		},
	],

	reject: [
		{
			code: `a { --a:; }`,
			fixed: `a { --a: ; }`,
			description: `a custom property with no value at all`,
			message: messages.expectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a:  ; }`,
			fixed: `a { --a: ; }`,
			description: `a custom property whose value is two spaces`,
			message: messages.expectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a {\n\t--a:;\n}`,
			fixed: `a {\n\t--a: ;\n}`,
			description: `the same empty custom property in a block broken across lines`,
			message: messages.expectedAfter(),
			line: 2,
			column: 6,
		},
		{
			code: `a {\n\t--a:  ;\n}`,
			fixed: `a {\n\t--a: ;\n}`,
			description: `the same two spaces in a block broken across lines`,
			message: messages.expectedAfter(),
			line: 2,
			column: 6,
		},
		{
			code: `a {\n\t--a:\n\t;\n}`,
			fixed: `a {\n\t--a: ;\n}`,
			description: `a custom property whose value is a break`,
			message: messages.expectedAfter(),
			line: 2,
			column: 6,
		},
		{
			code: `a { color :pink; }`,
			fixed: `a { color : pink; }`,
			description: `a value abutting the colon`,
			message: messages.expectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :  pink; }`,
			fixed: `a { color : pink; }`,
			description: `two spaces behind the colon`,
			message: messages.expectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :\tpink; }`,
			fixed: `a { color : pink; }`,
			description: `a tab behind the colon`,
			message: messages.expectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :\npink; }`,
			fixed: `a { color : pink; }`,
			description: `a break behind the colon`,
			message: messages.expectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :\r\npink; }`,
			fixed: `a { color : pink; }`,
			description: `the same break spelled with a carriage return`,
			message: messages.expectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color:pink; }`,
			fixed: `a { color: pink; }`,
			description: `a value abutting a colon that abuts the property too`,
			message: messages.expectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color/*comment*/:/*comment*/pink; }`,
			fixed: `a { color/*comment*/: /*comment*/pink; }`,
			description: `comments on both sides of the colon, neither spaced`,
			message: messages.expectedAfter(),
			line: 1,
			column: 11,
		},
		{
			// https://github.com/stylelint-stylistic/stylelint-stylistic/issues/92
			code: `a { color/* https://foo.bar/ */:pink; }`,
			fixed: `a { color/* https://foo.bar/ */: pink; }`,
			description: `a comment holding an address, whose double slash opens none of its own`,
			message: messages.expectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color/* a:b */:pink; }`,
			fixed: `a { color/* a:b */: pink; }`,
			description: `a comment holding a colon, which opens no declaration`,
			message: messages.expectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { --a:/*comment*/; }`,
			fixed: `a { --a: /*comment*/; }`,
			description: `a comment abutting the colon of a custom property`,
			message: messages.expectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a:/*comment*/ !important; }`,
			fixed: `a { --a: /*comment*/ !important; }`,
			description: `the same comment with a flag behind it`,
			message: messages.expectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a:  /*comment*/; }`,
			fixed: `a { --a: /*comment*/; }`,
			description: `the same comment behind two spaces`,
			message: messages.expectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a:\t/*comment*/ !important; }`,
			fixed: `a { --a: /*comment*/ !important; }`,
			description: `the same comment behind a tab, with a flag behind it`,
			message: messages.expectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a :/*comment*/ !important; }`,
			fixed: `a { --a : /*comment*/ !important; }`,
			description: `the same comment abutting a colon that stands behind a space`,
			message: messages.expectedAfter(),
			line: 1,
			column: 9,
		},
	],
})

testRule({
	ruleName,
	config: [`never`],

	accept: [
		{
			code: `a { --a:; color:red; }`,
			description: `a custom property with no value at all`,
		},
		{
			code: `a { color:pink }`,
			description: `a value abutting the colon`,
		},
		{
			code: `a { color :pink }`,
			description: `a space in front of the colon and none behind it`,
		},
		{
			code: `a { color\n:pink }`,
			description: `a break in front of the colon and nothing behind it`,
		},
		{
			code: `a { color\r\n:pink }`,
			description: `the same break spelled with a carriage return`,
		},
		{
			code: `$map: (key: value)`,
			description: `an SCSS map, whose inner colon opens no declaration`,
		},
		{
			// https://github.com/stylelint-stylistic/stylelint-stylistic/issues/92
			code: `a { color/* https://foo.bar/ */:pink; }`,
			description: `comment with an URL, no space after the declaration's own colon`,
		},
		{
			code: `a { --a:/*comment*/; }`,
			description: `a comment abutting the colon of a custom property`,
		},
		{
			code: `a { --a:/*comment*/ }`,
			description: `the same comment with no semicolon behind it`,
		},
		{
			code: `a { --a:/*comment*/ !important; }`,
			description: `the same comment with a flag behind it`,
		},
		{
			code: `a { --a:red /*comment*/; }`,
			description: `a value and a comment, the value abutting the colon`,
		},
		{
			code: `a { --a :/*comment*/ !important; }`,
			description: `the same comment abutting a colon that stands behind a space`,
		},
	],

	reject: [
		{
			code: `a { --a: ; color:red; }`,
			fixed: `a { --a:; color:red; }`,
			description: `a custom property whose value is a single space`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { color : pink; }`,
			fixed: `a { color :pink; }`,
			description: `a space behind the colon`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color:  pink; }`,
			fixed: `a { color:pink; }`,
			description: `two spaces behind the colon`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :\tpink; }`,
			fixed: `a { color :pink; }`,
			description: `a tab behind the colon`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :\npink; }`,
			fixed: `a { color :pink; }`,
			description: `a break behind the colon`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :\r\npink; }`,
			fixed: `a { color :pink; }`,
			description: `the same break spelled with a carriage return`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color/*comment*/ : /*comment*/pink; }`,
			fixed: `a { color/*comment*/ :/*comment*/pink; }`,
			description: `comments on both sides of the colon, each spaced`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 11,
		},
		{
			// https://github.com/stylelint-stylistic/stylelint-stylistic/issues/92
			code: `a { color/* https://foo.bar/ */: pink; }`,
			fixed: `a { color/* https://foo.bar/ */:pink; }`,
			description: `a comment holding an address, with a space behind the colon`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color/* a:b */: pink; }`,
			fixed: `a { color/* a:b */:pink; }`,
			description: `a comment holding a colon, with a space behind the real one`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 11,
		},
		{
			code: `a { --a: /*comment*/; }`,
			fixed: `a { --a:/*comment*/; }`,
			description: `a comment behind a space, in a custom property`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a: /*comment*/ }`,
			fixed: `a { --a:/*comment*/ }`,
			description: `the same comment with no semicolon behind it`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a: /*comment*/ !important; }`,
			fixed: `a { --a:/*comment*/ !important; }`,
			description: `the same comment with a flag behind it`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a: red /*comment*/; }`,
			fixed: `a { --a:red /*comment*/; }`,
			description: `a value and a comment behind the colon`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a: 10px/*comment*/ !important; }`,
			fixed: `a { --a:10px/*comment*/ !important; }`,
			description: `a value, a comment and a flag behind the colon`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a : /*comment*/; }`,
			fixed: `a { --a :/*comment*/; }`,
			description: `the same comment behind a colon that stands behind a space`,
			message: messages.rejectedAfter(),
			line: 1,
			column: 9,
		},
	],
})

testRule({
	ruleName,
	config: [`always-single-line`],

	accept: [
		{
			code: `a { --a: ; color: red; }`,
			description: `a custom property whose value is a single space, with a declaration behind it`,
		},
		{
			code: `a { --a: ; }`,
			description: `the same custom property alone in its block`,
		},
		{
			code: `a { color: pink }`,
			description: `a space behind the colon of a single-line declaration`,
		},
		{
			code: `a { transition: color 1s,\n\twidth 2s; }`,
			description: `a value broken across lines, with the space behind the colon`,
		},
		{
			code: `a { transition:color 1s,\n\twidth 2s; }`,
			description: `the same value abutting the colon, which this option passes over`,
		},
		{
			code: `a { transition:color 1s,\r\n\twidth 2s; }`,
			description: `the same value spelled with a carriage return`,
		},
		{
			code: `a { transition:\tcolor 1s,\n\twidth 2s; }`,
			description: `the same value behind a tab`,
		},
		{
			code: `a { --a: /*comment*/; }`,
			description: `a comment behind a space, in a custom property`,
		},
		{
			code: `a { --a: /*comment*/ !important; }`,
			description: `the same comment with a flag behind it`,
		},
		{
			code: `a { --a: red /*comment*/; }`,
			description: `a value and a comment behind the colon`,
		},
		{
			code: `a { --a : /*comment*/ !important; }`,
			description: `the same comment and flag, with a space in front of the colon`,
		},
		{
			code: `a { --a\t: /*comment*/; }`,
			description: `the same comment behind a colon that stands behind a tab`,
		},
	],

	reject: [
		{
			code: `a { --a:; }`,
			fixed: `a { --a: ; }`,
			description: `a custom property with no value at all`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a:  ; }`,
			fixed: `a { --a: ; }`,
			description: `a custom property whose value is two spaces`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a:  ; color: red; }`,
			fixed: `a { --a: ; color: red; }`,
			description: `the same custom property with a declaration behind it`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 9,
		},
		{
			code: `a { color :pink; }`,
			fixed: `a { color : pink; }`,
			description: `a value abutting the colon of a single-line declaration`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :  pink; }`,
			fixed: `a { color : pink; }`,
			description: `two spaces behind the colon`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :\tpink; }`,
			fixed: `a { color : pink; }`,
			description: `a tab behind the colon`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :\npink; }`,
			fixed: `a { color : pink; }`,
			description: `a break behind the colon, which does not make the declaration multi-line`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color :\r\npink; }`,
			fixed: `a { color : pink; }`,
			description: `the same break spelled with a carriage return`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color:pink; }`,
			fixed: `a { color: pink; }`,
			description: `a value abutting a colon that abuts the property too`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 11,
		},
		{
			code: `a { color/*comment*/:/*comment*/pink; }`,
			fixed: `a { color/*comment*/: /*comment*/pink; }`,
			description: `comments on both sides of the colon, neither spaced`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 11,
		},
		{
			code: `a { --a:/*comment*/; }`,
			fixed: `a { --a: /*comment*/; }`,
			description: `a comment abutting the colon of a custom property`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a:/*comment*/ }`,
			fixed: `a { --a: /*comment*/ }`,
			description: `the same comment with no semicolon behind it`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a:/*comment*/ !important; }`,
			fixed: `a { --a: /*comment*/ !important; }`,
			description: `the same comment with a flag behind it`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a:  /*comment*/; }`,
			fixed: `a { --a: /*comment*/; }`,
			description: `the same comment behind two spaces`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a:\t/*comment*/ !important; }`,
			fixed: `a { --a: /*comment*/ !important; }`,
			description: `the same comment behind a tab, with a flag behind it`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 9,
		},
		{
			code: `a { --a :/*comment*/ !important; }`,
			fixed: `a { --a : /*comment*/ !important; }`,
			description: `the same comment abutting a colon that stands behind a space`,
			message: messages.expectedAfterSingleLine(),
			line: 1,
			column: 9,
		},
	],
})
