import { messages, ruleName } from "./index.js"

const testRule = createTestRule({ ruleName })

testRule({
	ruleName,
	config: [`unix`],

	accept: [
		{
			code: `a {}\nb {}`,
			description: `a single line feed between two rules`,
		},
		{
			code: `a {}\n\nb{}`,
			description: `two line feeds between two rules`,
		},
		{
			code: `/** horse */\n\nb{}`,
			description: `two line feeds after a comment`,
		},
		{
			code: `a{}\n\n/** horse */\n\nb{}`,
			description: `line feeds around a comment standing between two rules`,
		},
		{
			code: `\n\na {}\n\nb{}\n\n\n\n\n\n`,
			description: `line feeds opening and closing the stylesheet`,
		},
		{
			code: `a { border: 1px\n solid \nred; }`,
			description: `line feeds between the parts of a value`,
		},
		{
			code: `.foo\n .bar { }`,
			description: `a line feed between two selectors`,
		},
		{
			code: `a {\n}`,
			description: `a line feed after the opening brace`,
		},
		{
			code: `a {}\n b {}`,
			description: `a line feed after the closing brace`,
		},
	],

	reject: [
		{
			code: `a {}\r\nb {}`,
			fixed: `a {}\nb {}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break between two rules`,
			line: 1,
			column: 5,
		},
		{
			code: `a {}\n\r\nb{}`,
			fixed: `a {}\n\nb{}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break on a blank line`,
			line: 2,
			column: 1,
		},
		{
			code: `/** horse */\r\n\nb{}`,
			fixed: `/** horse */\n\nb{}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break after a comment`,
			line: 1,
			column: 13,
		},
		{
			code: `a{}\n\n/** horse */\r\n\nb{}`,
			fixed: `a{}\n\n/** horse */\n\nb{}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break after a comment on the third line`,
			line: 3,
			column: 13,
		},
		{
			code: `\n\na {}\r\n\nb{}`,
			fixed: `\n\na {}\n\nb{}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break after a rule on the third line`,
			line: 3,
			column: 5,
		},

		{
			code: `/* This is a\r\ncomment*/\na {}`,
			fixed: `/* This is a\ncomment*/\na {}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break inside a comment`,
			line: 1,
			column: 13,
		},
		{
			code: `/*    This is a\r\ncomment*/\na {}`,
			fixed: `/*    This is a\ncomment*/\na {}`,
			message: messages.expected(`unix`),
			description: `the same break inside a comment that opens with spaces`,
			line: 1,
			column: 16,
		},
		{
			code: `/*This is a\r\ncomment*/\na {}`,
			fixed: `/*This is a\ncomment*/\na {}`,
			message: messages.expected(`unix`),
			description: `the same break inside a comment that opens with none`,
			line: 1,
			column: 12,
		},
		{
			code: `\n\n/* This is\na\r\ncomment*/\na {}`,
			fixed: `\n\n/* This is\na\ncomment*/\na {}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break inside a comment on the fourth line`,
			line: 4,
			column: 2,
		},
		{
			code: `/* This is\na comment*/\r\na {}`,
			fixed: `/* This is\na comment*/\na {}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break closing a comment written over two lines`,
			line: 2,
			column: 12,
		},
		{
			code: `\r\n\n\n\n\n/* This is\na comment*/`,
			fixed: `\n\n\n\n\n/* This is\na comment*/`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break opening the stylesheet, in front of a comment`,
			line: 1,
			column: 1,
		},
		{
			code: `\n\r\n\n\n\n/* This is\na comment*/`,
			fixed: `\n\n\n\n\n/* This is\na comment*/`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break among the blank lines that open the stylesheet`,
			line: 2,
			column: 1,
		},
		{
			code: `\r\n\n\n\n\n\n\n\n\n\n\na {}`,
			fixed: `\n\n\n\n\n\n\n\n\n\n\na {}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break opening the stylesheet, in front of a rule`,
			line: 1,
			column: 1,
		},
		{
			code: `\n\n\n\n\n\n\n\r\n\n\n\na {}`,
			fixed: `\n\n\n\n\n\n\n\n\n\n\na {}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break among the blank lines in front of a rule`,
			line: 8,
			column: 1,
		},
		{
			code: `a {}\n\n\r\n\n\n`,
			fixed: `a {}\n\n\n\n\n`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break among the blank lines that close the stylesheet`,
			line: 3,
			column: 1,
		},
		{
			code: `a {}\n\n\r\n`,
			fixed: `a {}\n\n\n`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break on the last line`,
			line: 3,
			column: 1,
		},
		{
			code: `.foo\r\n .bar {}`,
			fixed: `.foo\n .bar {}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break between two selectors`,
			line: 1,
			column: 5,
		},
		{
			code: `\n\n\n.foo\r\n .bar {}`,
			fixed: `\n\n\n.foo\n .bar {}`,
			message: messages.expected(`unix`),
			description: `the same break between selectors on the fourth line`,
			line: 4,
			column: 5,
		},
		{
			code: `\n\n\n.foo\n .bar\r\n .baz {}`,
			fixed: `\n\n\n.foo\n .bar\n .baz {}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break between the second and the third selector`,
			line: 5,
			column: 6,
		},
		{
			code: `a { border: 1px\r\n solid red; }`,
			fixed: `a { border: 1px\n solid red; }`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break between the parts of a value`,
			line: 1,
			column: 16,
		},
		{
			code: `\n\n\na { border: 1px\r\n solid red; }`,
			fixed: `\n\n\na { border: 1px\n solid red; }`,
			message: messages.expected(`unix`),
			description: `the same break in a value on the fourth line`,
			line: 4,
			column: 16,
		},
		{
			code: `\n\n\na { border: 1px\n solid \r\nred; }`,
			fixed: `\n\n\na { border: 1px\n solid \nred; }`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break in front of the last part of a value`,
			line: 5,
			column: 8,
		},
		{
			code: `\n\na {\r\n}`,
			fixed: `\n\na {\n}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break after the opening brace`,
			line: 3,
			column: 4,
		},
		{
			code: `\n\na {\n}\r\nb {\n}`,
			fixed: `\n\na {\n}\nb {\n}`,
			message: messages.expected(`unix`),
			description: `a carriage-return line break after the closing brace`,
			line: 4,
			column: 2,
		},
		{
			code: `\r\na {color:red;}`,
			fixed: `\na {color:red;}`,
			description: `a carriage-return line break opening the stylesheet`,
			message: messages.expected(`unix`),
			line: 1,
			column: 1,
		},
	],
})

testRule({
	ruleName,
	config: [`windows`],

	accept: [
		{
			code: `a {}\r\nb {}`,
			description: `a single carriage-return line break between two rules`,
		},
		{
			code: `a {}\r\n\r\nb{}`,
			description: `two carriage-return line breaks between two rules`,
		},
		{
			code: `/** horse */\r\n\r\nb{}`,
			description: `two carriage-return line breaks after a comment`,
		},
		{
			code: `a{}\r\n\r\n/** horse */\r\n\r\nb{}`,
			description: `carriage-return line breaks around a comment standing between two rules`,
		},
		{
			code: `\r\n\r\na {}\r\n\r\nb{}\r\n\r\n\r\n\r\n\r\n\r\n`,
			description: `carriage-return line breaks opening and closing the stylesheet`,
		},
		{
			code: `a { border: 1px\r\n solid \r\nred; }`,
			description: `carriage-return line breaks between the parts of a value`,
		},
		{
			code: `.foo\r\n .bar { }`,
			description: `a carriage-return line break between two selectors`,
		},
		{
			code: `a {\r\n}`,
			description: `a carriage-return line break after the opening brace`,
		},
		{
			code: `a {}\r\n b {}`,
			description: `a carriage-return line break after the closing brace`,
		},
	],
	reject: [
		{
			code: `a {}\nb {}`,
			fixed: `a {}\r\nb {}`,
			message: messages.expected(`windows`),
			description: `a bare line feed between two rules`,
			line: 1,
			column: 5,
		},
		{
			code: `a {}\r\n\nb{}`,
			fixed: `a {}\r\n\r\nb{}`,
			message: messages.expected(`windows`),
			description: `a bare line feed on a blank line`,
			line: 2,
			column: 1,
		},
		{
			code: `/** horse */\n\r\nb{}`,
			fixed: `/** horse */\r\n\r\nb{}`,
			message: messages.expected(`windows`),
			description: `a bare line feed after a comment`,
			line: 1,
			column: 13,
		},
		{
			code: `a{}\r\n\r\n/** horse */\n\r\nb{}`,
			fixed: `a{}\r\n\r\n/** horse */\r\n\r\nb{}`,
			message: messages.expected(`windows`),
			description: `a bare line feed after a comment on the third line`,
			line: 3,
			column: 13,
		},
		{
			code: `\r\n\r\na {}\n\r\nb{}`,
			fixed: `\r\n\r\na {}\r\n\r\nb{}`,
			message: messages.expected(`windows`),
			description: `a bare line feed after a rule on the third line`,
			line: 3,
			column: 5,
		},

		{
			code: `/* This is a\ncomment*/\r\na {}`,
			fixed: `/* This is a\r\ncomment*/\r\na {}`,
			message: messages.expected(`windows`),
			description: `a bare line feed inside a comment`,
			line: 1,
			column: 13,
		},
		{
			code: `/*    This is a\ncomment*/\r\na {}`,
			fixed: `/*    This is a\r\ncomment*/\r\na {}`,
			message: messages.expected(`windows`),
			description: `the same break inside a comment that opens with spaces`,
			line: 1,
			column: 16,
		},
		{
			code: `/*This is a\ncomment*/\r\na {}`,
			fixed: `/*This is a\r\ncomment*/\r\na {}`,
			message: messages.expected(`windows`),
			description: `the same break inside a comment that opens with none`,
			line: 1,
			column: 12,
		},
		{
			code: `\r\n\r\n/* This is\r\na\ncomment*/\r\na {}`,
			fixed: `\r\n\r\n/* This is\r\na\r\ncomment*/\r\na {}`,
			message: messages.expected(`windows`),
			description: `a bare line feed inside a comment on the fourth line`,
			line: 4,
			column: 2,
		},
		{
			code: `/* This is\r\na comment*/\na {}`,
			fixed: `/* This is\r\na comment*/\r\na {}`,
			message: messages.expected(`windows`),
			description: `a bare line feed closing a comment written over two lines`,
			line: 2,
			column: 12,
		},
		{
			code: `\n\r\n\r\n\r\n\r\n/* This is\r\na comment*/`,
			fixed: `\r\n\r\n\r\n\r\n\r\n/* This is\r\na comment*/`,
			message: messages.expected(`windows`),
			description: `a bare line feed opening the stylesheet, in front of a comment`,
			line: 1,
			column: 1,
		},
		{
			code: `\r\n\n\r\n\r\n\r\n/* This is\r\na comment*/`,
			fixed: `\r\n\r\n\r\n\r\n\r\n/* This is\r\na comment*/`,
			message: messages.expected(`windows`),
			description: `a bare line feed among the blank lines that open the stylesheet`,
			line: 2,
			column: 1,
		},
		{
			code: `\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\na {}`,
			fixed: `\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\na {}`,
			message: messages.expected(`windows`),
			description: `a bare line feed opening the stylesheet, in front of a rule`,
			line: 1,
			column: 1,
		},
		{
			code: `\r\n\r\n\r\n\r\n\r\n\r\n\r\n\n\r\n\r\n\r\na {}`,
			fixed: `\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\na {}`,
			message: messages.expected(`windows`),
			description: `a bare line feed among the blank lines in front of a rule`,
			line: 8,
			column: 1,
		},
		{
			code: `a {}\r\n\r\n\n\r\n\r\n`,
			fixed: `a {}\r\n\r\n\r\n\r\n\r\n`,
			message: messages.expected(`windows`),
			description: `a bare line feed among the blank lines that close the stylesheet`,
			line: 3,
			column: 1,
		},
		{
			code: `a {}\r\n\r\n\n`,
			fixed: `a {}\r\n\r\n\r\n`,
			message: messages.expected(`windows`),
			description: `a bare line feed on the last line`,
			line: 3,
			column: 1,
		},
		{
			code: `.foo\n .bar {}`,
			fixed: `.foo\r\n .bar {}`,
			message: messages.expected(`windows`),
			description: `a bare line feed between two selectors`,
			line: 1,
			column: 5,
		},
		{
			code: `\r\n\r\n\r\n.foo\n .bar {}`,
			fixed: `\r\n\r\n\r\n.foo\r\n .bar {}`,
			message: messages.expected(`windows`),
			description: `the same break between selectors on the fourth line`,
			line: 4,
			column: 5,
		},
		{
			code: `\r\n\r\n\r\n.foo\r\n .bar\n .baz {}`,
			fixed: `\r\n\r\n\r\n.foo\r\n .bar\r\n .baz {}`,
			message: messages.expected(`windows`),
			description: `a bare line feed between the second and the third selector`,
			line: 5,
			column: 6,
		},
		{
			code: `a { border: 1px\n solid red; }`,
			fixed: `a { border: 1px\r\n solid red; }`,
			message: messages.expected(`windows`),
			description: `a bare line feed between the parts of a value`,
			line: 1,
			column: 16,
		},
		{
			code: `\r\n\r\n\r\na { border: 1px\n solid red; }`,
			fixed: `\r\n\r\n\r\na { border: 1px\r\n solid red; }`,
			message: messages.expected(`windows`),
			description: `the same break in a value on the fourth line`,
			line: 4,
			column: 16,
		},
		{
			code: `\r\n\r\n\r\na { border: 1px\r\n solid \nred; }`,
			fixed: `\r\n\r\n\r\na { border: 1px\r\n solid \r\nred; }`,
			message: messages.expected(`windows`),
			description: `a bare line feed in front of the last part of a value`,
			line: 5,
			column: 8,
		},
		{
			code: `\r\n\r\na {\n}`,
			fixed: `\r\n\r\na {\r\n}`,
			message: messages.expected(`windows`),
			description: `a bare line feed after the opening brace`,
			line: 3,
			column: 4,
		},
		{
			code: `\r\n\r\na {\r\n}\nb {\r\n}`,
			fixed: `\r\n\r\na {\r\n}\r\nb {\r\n}`,
			message: messages.expected(`windows`),
			description: `a bare line feed after the closing brace`,
			line: 4,
			column: 2,
		},
	],
})
