import valueParser from "postcss-value-parser"
import { expect, it } from "vitest"

import { getDimension } from "./index.js"

it(`getDimension`, () => {
	expect(getDimension().number).toBe(null)
	expect(getDimension().unit).toBe(null)
	expect(getDimension({}).number).toBe(null)
	expect(getDimension({}).unit).toBe(null)

	// testing Dimension.unit
	expect(getDimension(valueParser(`1.1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`1.1000s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`1.1S`).nodes[0]).unit).toBe(`S`)
	expect(getDimension(valueParser(`+1.1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`+1.1000s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`-1.1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`-1.1000s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`1.1e10s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`+1.1e10s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`-1.1e10s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`1.1e+10s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`1.1e-10s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`+1.1e+10s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`+1.1e-10s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`-1.1e-10s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`-1.1e+10s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`1pX`).nodes[0]).unit).toBe(`pX`)
	expect(getDimension(valueParser(`1PX`).nodes[0]).unit).toBe(`PX`)
	expect(getDimension(valueParser(`+1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`-1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`1e1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`+1e1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`-1e1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`1e-1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`1e+1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`+1e+1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`+1e-1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`-1e-1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`-1e+1px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`.1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`+.1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`-.1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`+.1000s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`-.1000s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`.1e1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`+.1e1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`-.1e1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`.1e-1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`.1e+1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`+.1e+1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`+.1e-1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`-.1e-1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`-.1e+1s`).nodes[0]).unit).toBe(`s`)
	expect(getDimension(valueParser(`100%`).nodes[0]).unit).toBe(`%`)
	expect(getDimension(valueParser(`100`).nodes[0]).unit).toBe(``)
	expect(getDimension(valueParser(`0\\0`).nodes[0]).unit).toBe(``)
	expect(getDimension(valueParser(`10px\\9`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`6e-2px`).nodes[0]).unit).toBe(`px`)
	expect(getDimension(valueParser(`.0`).nodes[0]).unit).toBe(``)
	expect(getDimension(valueParser(`+.0`).nodes[0]).unit).toBe(``)
	expect(getDimension(valueParser(`-.0`).nodes[0]).unit).toBe(``)
	expect(getDimension(valueParser(`.0e1`).nodes[0]).unit).toBe(``)
	expect(getDimension(valueParser(`+.0e1`).nodes[0]).unit).toBe(``)
	expect(getDimension(valueParser(`-.0e1`).nodes[0]).unit).toBe(``)

	// testing Dimension.number
	expect(getDimension(valueParser(`1.1s`).nodes[0]).number).toBe(`1.1`)
	expect(getDimension(valueParser(`1.1000s`).nodes[0]).number).toBe(`1.1000`)
	expect(getDimension(valueParser(`1.1S`).nodes[0]).number).toBe(`1.1`)
	expect(getDimension(valueParser(`+1.1s`).nodes[0]).number).toBe(`+1.1`)
	expect(getDimension(valueParser(`+1.1000s`).nodes[0]).number).toBe(`+1.1000`)
	expect(getDimension(valueParser(`-1.1s`).nodes[0]).number).toBe(`-1.1`)
	expect(getDimension(valueParser(`-1.1000s`).nodes[0]).number).toBe(`-1.1000`)
	expect(getDimension(valueParser(`1.1e10s`).nodes[0]).number).toBe(`1.1e10`)
	expect(getDimension(valueParser(`+1.1e10s`).nodes[0]).number).toBe(`+1.1e10`)
	expect(getDimension(valueParser(`-1.1e10s`).nodes[0]).number).toBe(`-1.1e10`)
	expect(getDimension(valueParser(`1.1e+10s`).nodes[0]).number).toBe(`1.1e+10`)
	expect(getDimension(valueParser(`1.1e-10s`).nodes[0]).number).toBe(`1.1e-10`)
	expect(getDimension(valueParser(`+1.1e+10s`).nodes[0]).number).toBe(`+1.1e+10`)
	expect(getDimension(valueParser(`+1.1e-10s`).nodes[0]).number).toBe(`+1.1e-10`)
	expect(getDimension(valueParser(`-1.1e-10s`).nodes[0]).number).toBe(`-1.1e-10`)
	expect(getDimension(valueParser(`-1.1e+10s`).nodes[0]).number).toBe(`-1.1e+10`)
	expect(getDimension(valueParser(`1px`).nodes[0]).number).toBe(`1`)
	expect(getDimension(valueParser(`1pX`).nodes[0]).number).toBe(`1`)
	expect(getDimension(valueParser(`1PX`).nodes[0]).number).toBe(`1`)
	expect(getDimension(valueParser(`+1px`).nodes[0]).number).toBe(`+1`)
	expect(getDimension(valueParser(`-1px`).nodes[0]).number).toBe(`-1`)
	expect(getDimension(valueParser(`1e1px`).nodes[0]).number).toBe(`1e1`)
	expect(getDimension(valueParser(`+1e1px`).nodes[0]).number).toBe(`+1e1`)
	expect(getDimension(valueParser(`-1e1px`).nodes[0]).number).toBe(`-1e1`)
	expect(getDimension(valueParser(`1e-1px`).nodes[0]).number).toBe(`1e-1`)
	expect(getDimension(valueParser(`1e+1px`).nodes[0]).number).toBe(`1e+1`)
	expect(getDimension(valueParser(`+1e+1px`).nodes[0]).number).toBe(`+1e+1`)
	expect(getDimension(valueParser(`+1e-1px`).nodes[0]).number).toBe(`+1e-1`)
	expect(getDimension(valueParser(`-1e-1px`).nodes[0]).number).toBe(`-1e-1`)
	expect(getDimension(valueParser(`-1e+1px`).nodes[0]).number).toBe(`-1e+1`)
	expect(getDimension(valueParser(`.1s`).nodes[0]).number).toBe(`.1`)
	expect(getDimension(valueParser(`+.1s`).nodes[0]).number).toBe(`+.1`)
	expect(getDimension(valueParser(`-.1s`).nodes[0]).number).toBe(`-.1`)
	expect(getDimension(valueParser(`+.1000s`).nodes[0]).number).toBe(`+.1000`)
	expect(getDimension(valueParser(`-.1000s`).nodes[0]).number).toBe(`-.1000`)
	expect(getDimension(valueParser(`.1e1s`).nodes[0]).number).toBe(`.1e1`)
	expect(getDimension(valueParser(`+.1e1s`).nodes[0]).number).toBe(`+.1e1`)
	expect(getDimension(valueParser(`-.1e1s`).nodes[0]).number).toBe(`-.1e1`)
	expect(getDimension(valueParser(`.1e-1s`).nodes[0]).number).toBe(`.1e-1`)
	expect(getDimension(valueParser(`.1e+1s`).nodes[0]).number).toBe(`.1e+1`)
	expect(getDimension(valueParser(`+.1e+1s`).nodes[0]).number).toBe(`+.1e+1`)
	expect(getDimension(valueParser(`+.1e-1s`).nodes[0]).number).toBe(`+.1e-1`)
	expect(getDimension(valueParser(`-.1e-1s`).nodes[0]).number).toBe(`-.1e-1`)
	expect(getDimension(valueParser(`-.1e+1s`).nodes[0]).number).toBe(`-.1e+1`)
	expect(getDimension(valueParser(`100%`).nodes[0]).number).toBe(`100`)
	expect(getDimension(valueParser(`100`).nodes[0]).number).toBe(`100`)
	expect(getDimension(valueParser(`0\\0`).nodes[0]).number).toBe(`0`)
	expect(getDimension(valueParser(`10px\\9`).nodes[0]).number).toBe(`10`)
	expect(getDimension(valueParser(`6e-2px`).nodes[0]).number).toBe(`6e-2`)
	expect(getDimension(valueParser(`.0`).nodes[0]).number).toBe(`.0`)
	expect(getDimension(valueParser(`+.0`).nodes[0]).number).toBe(`+.0`)
	expect(getDimension(valueParser(`-.0`).nodes[0]).number).toBe(`-.0`)
	expect(getDimension(valueParser(`.0e1`).nodes[0]).number).toBe(`.0e1`)
	expect(getDimension(valueParser(`+.0e1`).nodes[0]).number).toBe(`+.0e1`)
	expect(getDimension(valueParser(`-.0e1`).nodes[0]).number).toBe(`-.0e1`)

	// testing invalid inputs
	expect(getDimension(valueParser(`#fff`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`#000`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`#zzzzzz`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`#F`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`#PX`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`"100"`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`"100px"`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(` `).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`/`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`+`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`word`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`px`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`url()`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`url()px`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`$variable`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`\${$variable}`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`\${$variable}px`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`\${$variable}px`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`@variable`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`e1`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`wordPX`).nodes[0]).unit).toBe(null)
	expect(getDimension(valueParser(`..0`).nodes[0]).unit).toBe(null)

	expect(getDimension(valueParser(`#fff`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`#000`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`#zzzzzz`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`#F`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`#PX`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`"100"`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`"100px"`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(` `).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`/`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`+`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`word`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`px`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`url()`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`url()px`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`$variable`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`\${$variable}`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`\${$variable}px`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`\${$variable}px`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`@variable`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`e1`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`wordPX`).nodes[0]).number).toBe(null)
	expect(getDimension(valueParser(`..0`).nodes[0]).number).toBe(null)
})

it(`getDimension positions`, () => {
	// Where each character of the copy the reading was taken from stands in the text the node holds. A word no cut touches maps onto itself
	expect(getDimension(valueParser(`10px`).nodes[0]).positions).toEqual([0, 1, 2, 3])
	expect(getDimension(valueParser(`.5REM`).nodes[0]).positions).toEqual([0, 1, 2, 3, 4])
	expect(getDimension(valueParser(`1px!important`).nodes[0]).positions).toEqual([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

	// A hack unit closing the word leaves the copy ending where the unit does
	expect(getDimension(valueParser(`10px\\0`).nodes[0]).positions).toEqual([0, 1, 2, 3])
	expect(getDimension(valueParser(`10px\\9`).nodes[0]).positions).toEqual([0, 1, 2, 3])

	// A hack unit standing anywhere else moves everything written behind it
	expect(getDimension(valueParser(`1PX\\9!important`).nodes[0]).positions).toEqual([0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
	expect(getDimension(valueParser(`10PX\\9*2rem`).nodes[0]).positions).toEqual([0, 1, 2, 3, 6, 7, 8, 9, 10])

	// The brace a broken interpolation left behind is cut like every other character an interpolation is spelled with
	expect(getDimension(valueParser(`2px}`).nodes[0]).positions).toEqual([0, 1, 2])

	// Two such braces in one word: the second cut is made first, so that the first one still finds its run where the scan saw it
	expect(getDimension(valueParser(`1}px}`).nodes[0]).positions).toEqual([0, 2, 3])

	// Nothing was read, so there is nowhere to point
	expect(getDimension().positions).toBe(null)
	expect(getDimension({}).positions).toBe(null)
	expect(getDimension(valueParser(`#fff`).nodes[0]).positions).toBe(null)
	expect(getDimension(valueParser(`$variable`).nodes[0]).positions).toBe(null)
	expect(getDimension(valueParser(`"100px"`).nodes[0]).positions).toBe(null)
	expect(getDimension(valueParser(`word`).nodes[0]).positions).toBe(null)
})
