import { messages, ruleName } from "./index.ts"

let testRule = createTestRule({ ruleName, autoStripIndent: false })

testRule({
	ruleName,
	config: [0],

	accept: [
		{
			description: `a line break in front of the selector`,
			code: `\n.foo { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\n.foo { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\n.foo { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `.foo\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `.foo\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `.foo\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break inside the block`,
			code: `.foo {\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo {\r\n}`,
		},
		{
			description: `a blank line inside the block`,
			code: `.foo {\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo {\r\n\r\n}`,
		},
		{
			description: `two blank lines inside the block`,
			code: `.foo {\n\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo {\r\n\r\n\r\n}`,
		},
		{
			description: `a line break behind the rule`,
			code: `.foo { }\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo { }\r\n`,
		},
		{
			description: `a blank line behind the rule`,
			code: `.foo { }\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo { }\r\n\r\n`,
		},
		{
			description: `two blank lines behind the rule`,
			code: `.foo { }\n\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo { }\r\n\r\n\r\n`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\n.foo, .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo, .bar { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\n.foo, .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo, .bar { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\n.foo, .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo, .bar { }`,
		},
		{
			description: `a selector written on one line`,
			code: `.foo, .bar { }`,
		},
		{
			description: `a line break after the first comma`,
			code: `.foo,\n.bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n.bar { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `.foo, .bar\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `.foo, .bar\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `.foo, .bar\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break inside the block`,
			code: `.foo, .bar {\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar {\r\n}`,
		},
		{
			description: `a blank line inside the block`,
			code: `.foo, .bar {\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar {\r\n\r\n}`,
		},
		{
			description: `two blank lines inside the block`,
			code: `.foo, .bar {\n\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar {\r\n\r\n\r\n}`,
		},
		{
			description: `a line break behind the rule`,
			code: `.foo, .bar { }\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar { }\r\n`,
		},
		{
			description: `a blank line behind the rule`,
			code: `.foo, .bar { }\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar { }\r\n\r\n`,
		},
		{
			description: `two blank lines behind the rule`,
			code: `.foo, .bar { }\n\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar { }\r\n\r\n\r\n`,
		},
		{
			description: `a selector written on one line`,
			code: `.foo .bar { }`,
		},
		{
			description: `a line break inside the selector`,
			code: `.foo\n.bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar { }`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\n.foo .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo .bar { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\n.foo .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo .bar { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\n.foo .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo .bar { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `.foo .bar\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `.foo .bar\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `.foo .bar\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break inside the block`,
			code: `.foo .bar {\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar {\r\n}`,
		},
		{
			description: `a blank line inside the block`,
			code: `.foo .bar {\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar {\r\n\r\n}`,
		},
		{
			description: `two blank lines inside the block`,
			code: `.foo .bar {\n\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar {\r\n\r\n\r\n}`,
		},
		{
			description: `a line break behind the rule`,
			code: `.foo .bar { }\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar { }\r\n`,
		},
		{
			description: `a blank line behind the rule`,
			code: `.foo .bar { }\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar { }\r\n\r\n`,
		},
		{
			description: `two blank lines behind the rule`,
			code: `.foo .bar { }\n\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar { }\r\n\r\n\r\n`,
		},
		{
			description: `a selector written on one line`,
			code: `.foo > .bar { }`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\n.foo > .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo > .bar { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\n.foo > .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo > .bar { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\n.foo > .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo > .bar { }`,
		},
		{
			description: `a line break in front of the first combinator`,
			code: `.foo\n> .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n> .bar { }`,
		},
		{
			description: `a line break after the first combinator`,
			code: `.foo >\n.bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo >\r\n.bar { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `.foo > .bar\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `.foo > .bar\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `.foo > .bar\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break inside the block`,
			code: `.foo > .bar {\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar {\r\n}`,
		},
		{
			description: `a blank line inside the block`,
			code: `.foo > .bar {\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar {\r\n\r\n}`,
		},
		{
			description: `two blank lines inside the block`,
			code: `.foo > .bar {\n\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar {\r\n\r\n\r\n}`,
		},
		{
			description: `a line break behind the rule`,
			code: `.foo > .bar { }\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar { }\r\n`,
		},
		{
			description: `a blank line behind the rule`,
			code: `.foo > .bar { }\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar { }\r\n\r\n`,
		},
		{
			description: `two blank lines behind the rule`,
			code: `.foo > .bar { }\n\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar { }\r\n\r\n\r\n`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\na[itemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\na[itemprop=url] { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\na[itemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\na[itemprop=url] { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\na[itemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\na[itemprop=url] { }`,
		},
		{
			description: `a line break inside the selector`,
			code: `a\n[itemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n[itemprop=url] { }`,
		},
		{
			description: `a line break after the opening bracket of the attribute selector`,
			code: `a[\nitemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[\r\nitemprop=url] { }`,
		},
		{
			description: `a line break in front of the operator of the attribute selector`,
			code: `a[itemprop\n=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop\r\n=url] { }`,
		},
		{
			description: `a line break after the operator of the attribute selector`,
			code: `a[itemprop=\nurl] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=\r\nurl] { }`,
		},
		{
			description: `a line break in front of the closing bracket of the attribute selector`,
			code: `a[itemprop=url\n] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url\r\n] { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `a[itemprop=url]\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url]\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `a[itemprop=url]\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url]\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `a[itemprop=url]\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url]\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\na:hover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\na:hover { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\na:hover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\na:hover { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\na:hover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\na:hover { }`,
		},
		{
			description: `a line break in front of the pseudo-class`,
			code: `a\n:hover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n:hover { }`,
		},
		{
			description: `a line break after the colon of the pseudo-class`,
			code: `a:\nhover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:\r\nhover { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `a:hover\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:hover\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `a:hover\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:hover\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `a:hover\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:hover\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\na::before { }`,
		},
		{
			description: `a line break in front of the selector, written with carriage-return line breaks`,
			code: `\r\na::before  { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\na::before { }`,
		},
		{
			description: `a blank line in front of the selector, written with carriage-return line breaks`,
			code: `\r\n\r\na::before  { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\na::before { }`,
		},
		{
			description: `two blank lines in front of the selector, written with carriage-return line breaks`,
			code: `\r\n\r\n\r\na::before  { }`,
		},
		{
			description: `a line break in front of the pseudo-element`,
			code: `a\n::before  { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n::before  { }`,
		},
		{
			description: `a line break after the colons of the pseudo-element`,
			code: `a::\nbefore { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a::\r\nbefore { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `a::before\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a::before\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `a::before\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a::before\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `a::before\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a::before\r\n\r\n\r\n{ }`,
		},
		{
			description: `a custom property under the root selector`,
			code: `:root { --foo: 1px; }`,
		},
		{
			description: `a custom property under a type selector`,
			code: `html { --foo: 1px; }`,
		},
		{
			description: `a custom property set under the root selector`,
			code: `:root { --custom-property-set: {} }`,
		},
		{
			description: `a custom property set under a type selector`,
			code: `html { --custom-property-set: {} }`,
		},
		{
			description: `a line break behind a comment inside the selector`,
			code: `/*comment*/\n.foo{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `/*comment*/\r\n.foo{ }`,
		},
		{
			description: `a line break in front of a comment inside the selector and a line break behind a comment inside the selector`,
			code: `.foo \n/*comment*/\n .bar { }`,
		},
		{
			description: `a line break in front of a comment inside the selector and a blank line behind a comment inside the selector, written with carriage-return line breaks`,
			code: `.foo \r\n/*comment*/\n\r .bar { }`,
		},
	],

	reject: [
		{
			description: `a blank line inside the selector`,
			code: `.foo\n\n.bar { }`,
			fixed: `.foo\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar { }`,
			fixed: `.foo\r\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line after the first comma`,
			code: `.foo,\n\n.bar { }`,
			fixed: `.foo,\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n\r\n.bar { }`,
			fixed: `.foo,\r\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the first comma`,
			code: `.foo\n\n,.bar { }`,
			fixed: `.foo\n,.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n,.bar { }`,
			fixed: `.foo\r\n,.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line after the second comma`,
			code: `.foo, .bar,\n\n.other { }`,
			fixed: `.foo, .bar,\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar,\r\n\r\n.other { }`,
			fixed: `.foo, .bar,\r\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break after the first comma and a blank line after the second comma`,
			code: `.foo,\n.bar,\n\n.other { }`,
			fixed: `.foo,\n.bar,\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n.bar,\r\n\r\n.other { }`,
			fixed: `.foo,\r\n.bar,\r\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break after the first comma, a blank line after the second comma and a line break between the selector and the opening brace`,
			code: `.foo,\n.bar,\n\n.other\n{ }`,
			fixed: `.foo,\n.bar,\n.other\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n.bar,\r\n\r\n.other\r\n{ }`,
			fixed: `.foo,\r\n.bar,\r\n.other\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break after the first comma, a blank line after the second comma and a blank line between the selector and the opening brace`,
			code: `.foo,\n.bar,\n\n.other\n\n{ }`,
			fixed: `.foo,\n.bar,\n.other\n\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n.bar,\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `.foo,\r\n.bar,\r\n.other\r\n\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break in front of the selector, a line break after the first comma, a blank line after the second comma and a blank line between the selector and the opening brace`,
			code: `\n.foo,\n.bar,\n\n.other\n\n{ }`,
			fixed: `\n.foo,\n.bar,\n.other\n\n{ }`,
			line: 2,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo,\r\n.bar,\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n.foo,\r\n.bar,\r\n.other\r\n\r\n{ }`,
			line: 2,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the selector, a line break after the first comma, a blank line after the second comma and a blank line between the selector and the opening brace`,
			code: `\n\n.foo,\n.bar,\n\n.other\n\n{ }`,
			fixed: `\n\n.foo,\n.bar,\n.other\n\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo,\r\n.bar,\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo,\r\n.bar,\r\n.other\r\n\r\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line inside the selector`,
			code: `.foo .bar\n\n.other { }`,
			fixed: `.foo .bar\n.other { }`,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar\r\n\r\n.other { }`,
			fixed: `.foo .bar\r\n.other { }`,
			message: messages.expected(0),
		},
		{
			description: `a line break inside the selector and a blank line further along it`,
			code: `.foo\n.bar\n\n.other { }`,
			fixed: `.foo\n.bar\n.other { }`,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n.other { }`,
			fixed: `.foo\r\n.bar\r\n.other { }`,
			message: messages.expected(0),
		},
		{
			description: `a line break inside the selector, a blank line further along it and a line break between the selector and the opening brace`,
			code: `.foo\n.bar\n\n.other\n{ }`,
			fixed: `.foo\n.bar\n.other\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n.other\r\n{ }`,
			fixed: `.foo\r\n.bar\r\n.other\r\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `a line break inside the selector, a blank line further along it and a blank line between the selector and the opening brace`,
			code: `.foo\n.bar\n\n.other\n\n{ }`,
			fixed: `.foo\n.bar\n.other\n\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `.foo\r\n.bar\r\n.other\r\n\r\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `a line break in front of the selector, a line break inside the selector, a blank line further along it and a blank line between the selector and the opening brace`,
			code: `\n.foo\n.bar\n\n.other\n\n{ }`,
			fixed: `\n.foo\n.bar\n.other\n\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo\r\n.bar\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n.foo\r\n.bar\r\n.other\r\n\r\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the selector, a line break inside the selector, a blank line further along it and a blank line between the selector and the opening brace`,
			code: `\n\n.foo\n.bar\n\n.other\n\n{ }`,
			fixed: `\n\n.foo\n.bar\n.other\n\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo\r\n.bar\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo\r\n.bar\r\n.other\r\n\r\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `a blank line after the first combinator`,
			code: `.foo >\n\n.bar { }`,
			fixed: `.foo >\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo >\r\n\r\n.bar { }`,
			fixed: `.foo >\r\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the first combinator`,
			code: `.foo\n\n>.bar { }`,
			fixed: `.foo\n>.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the first combinator, written with carriage-return line breaks`,
			code: `.foo\r\n\r\n> .bar { }`,
			fixed: `.foo\r\n> .bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line after the first combinator`,
			code: `.foo .bar >\n\n.other { }`,
			fixed: `.foo .bar >\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line after the first combinator, written with carriage-return line breaks`,
			code: `.foo .bar >\r\n\r\n .other { }`,
			fixed: `.foo .bar >\r\n .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the first combinator`,
			code: `.foo .bar\n\n> .other { }`,
			fixed: `.foo .bar\n> .other { }`,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar\r\n\r\n> .other { }`,
			fixed: `.foo .bar\r\n> .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break inside the selector and a blank line after the first combinator`,
			code: `.foo\n.bar >\n\n.other { }`,
			fixed: `.foo\n.bar >\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar >\r\n\r\n.other { }`,
			fixed: `.foo\r\n.bar >\r\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break inside the selector and a blank line in front of the first combinator`,
			code: `.foo\n.bar\n\n> .other { }`,
			fixed: `.foo\n.bar\n> .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n> .other { }`,
			fixed: `.foo\r\n.bar\r\n> .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break inside the selector, a blank line after the first combinator and a line break between the selector and the opening brace`,
			code: `.foo\n.bar >\n\n.other\n{ }`,
			fixed: `.foo\n.bar >\n.other\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar >\r\n\r\n.other\r\n{ }`,
			fixed: `.foo\r\n.bar >\r\n.other\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break inside the selector, a blank line in front of the first combinator and a line break between the selector and the opening brace`,
			code: `.foo\n.bar\n\n> .other\n{ }`,
			fixed: `.foo\n.bar\n> .other\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break inside the selector, a blank line in front of the first combinator and a line break between the selector and the opening brace, written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n > .other\r\n{ }`,
			fixed: `.foo\r\n.bar\r\n > .other\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break inside the selector, a blank line after the first combinator and a blank line between the selector and the opening brace`,
			code: `.foo\n.bar >\n\n.other\n\n{ }`,
			fixed: `.foo\n.bar >\n.other\n\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar >\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `.foo\r\n.bar >\r\n.other\r\n\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break inside the selector, a blank line in front of the first combinator and a blank line between the selector and the opening brace`,
			code: `.foo\n.bar\n\n> .other\n\n{ }`,
			fixed: `.foo\n.bar\n> .other\n\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n> .other\r\n\r\n{ }`,
			fixed: `.foo\r\n.bar\r\n> .other\r\n\r\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `a line break in front of the selector, a line break inside the selector, a blank line after the first combinator and a blank line between the selector and the opening brace`,
			code: `\n.foo\n.bar >\n\n.other\n\n{ }`,
			fixed: `\n.foo\n.bar >\n.other\n\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo\r\n.bar >\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n.foo\r\n.bar >\r\n.other\r\n\r\n{ }`,
			line: 2,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break in front of the selector, a line break inside the selector, a blank line in front of the first combinator and a blank line between the selector and the opening brace`,
			code: `\n.foo\n.bar\n\n> .other\n\n{ }`,
			fixed: `\n.foo\n.bar\n> .other\n\n{ }`,
			line: 2,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo\r\n.bar\r\n\r\n> .other\r\n\r\n{ }`,
			fixed: `\r\n.foo\r\n.bar\r\n> .other\r\n\r\n{ }`,
			line: 2,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the selector, a line break inside the selector, a blank line after the first combinator and a blank line between the selector and the opening brace`,
			code: `\n\n.foo\n.bar >\n\n.other\n\n{ }`,
			fixed: `\n\n.foo\n.bar >\n.other\n\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo\r\n.bar >\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo\r\n.bar >\r\n.other\r\n\r\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the selector, a line break inside the selector, a blank line in front of the first combinator and a blank line between the selector and the opening brace`,
			code: `\n\n.foo\n.bar\n\n >.other\n\n{ }`,
			fixed: `\n\n.foo\n.bar\n >.other\n\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the selector, a line break inside the selector, a blank line in front of the first combinator and a blank line between the selector and the opening brace, written with carriage-return line breaks`,
			code: `\r\n\r\n.foo\r\n.bar\r\n\r\n> .other\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo\r\n.bar\r\n> .other\r\n\r\n{ }`,
			message: messages.expected(0),
		},
		{
			description: `a blank line after the opening bracket of the attribute selector`,
			code: `a[\n\nitemprop=url] { }`,
			fixed: `a[\nitemprop=url] { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[\r\n\r\nitemprop=url] { }`,
			fixed: `a[\r\nitemprop=url] { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the operator of the attribute selector`,
			code: `a[itemprop\n\n=url] { }`,
			fixed: `a[itemprop\n=url] { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop\r\n\r\n=url] { }`,
			fixed: `a[itemprop\r\n=url] { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line after the operator of the attribute selector`,
			code: `a[itemprop=\n\nurl] { }`,
			fixed: `a[itemprop=\nurl] { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=\r\n\r\nurl] { }`,
			fixed: `a[itemprop=\r\nurl] { }`,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the closing bracket of the attribute selector`,
			code: `a[itemprop=url\n\n] { }`,
			fixed: `a[itemprop=url\n] { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url\r\n\r\n] { }`,
			fixed: `a[itemprop=url\r\n] { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the pseudo-class`,
			code: `a\n\n:hover { }`,
			fixed: `a\n:hover { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n\r\n:hover { }`,
			fixed: `a\r\n:hover { }`,
			message: messages.expected(0),
		},
		{
			description: `a blank line after the colon of the pseudo-class`,
			code: `a:\n\nhover { }`,
			fixed: `a:\nhover { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:\r\n\r\nhover { }`,
			fixed: `a:\r\nhover { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of the pseudo-element`,
			code: `a\n\n::before { }`,
			fixed: `a\n::before { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n\r\n::before { }`,
			fixed: `a\r\n::before { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line after the colons of a pseudo-element, in the second of two rules`,
			code: `a { }\na::\n\nbefore { }`,
			fixed: `a { }\na::\nbefore { }`,
			line: 2,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line after the colons of the pseudo-element, written with carriage-return line breaks`,
			code: `a::\r\n\r\nbefore { }`,
			fixed: `a::\r\nbefore { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of a comment inside the selector`,
			code: `.foo\n\n/*comment*/ .bar { }`,
			fixed: `.foo\n/*comment*/ .bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break in front of a comment inside the selector and a blank line behind a comment inside the selector`,
			code: `.foo\n/*comment*/\n\n.bar { }`,
			fixed: `.foo\n/*comment*/\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a blank line in front of a comment inside the selector, written with carriage-return line breaks`,
			code: `.foo\r\n\r\n/*comment*/ .bar { }`,
			fixed: `.foo\r\n/*comment*/ .bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
		{
			description: `a line break in front of a comment inside the selector and a blank line behind a comment inside the selector, written with carriage-return line breaks`,
			code: `.foo\r\n/*comment*/\r\n\r\n.bar { }`,
			fixed: `.foo\r\n/*comment*/\r\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(0),
		},
	],
})

testRule({
	ruleName,
	config: [1],

	accept: [
		{
			description: `a line break in front of the selector`,
			code: `\n.foo { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\n.foo { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\n.foo { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `.foo\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `.foo\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `.foo\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break inside the block`,
			code: `.foo {\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo {\r\n}`,
		},
		{
			description: `a blank line inside the block`,
			code: `.foo {\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo {\r\n\r\n}`,
		},
		{
			description: `two blank lines inside the block`,
			code: `.foo {\n\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo {\r\n\r\n\r\n}`,
		},
		{
			description: `a line break behind the rule`,
			code: `.foo { }\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo { }\r\n`,
		},
		{
			description: `a blank line behind the rule`,
			code: `.foo { }\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo { }\r\n\r\n`,
		},
		{
			description: `two blank lines behind the rule`,
			code: `.foo { }\n\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo { }\r\n\r\n\r\n`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\n.foo, .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo, .bar { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\n.foo, .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo, .bar { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\n.foo, .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo, .bar { }`,
		},
		{
			description: `a selector written on one line`,
			code: `.foo, .bar { }`,
		},
		{
			description: `a line break after the first comma`,
			code: `.foo,\n.bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n.bar { }`,
		},
		{
			description: `a blank line after the first comma`,
			code: `.foo,\n\n.bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n\r\n.bar { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `.foo, .bar\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `.foo, .bar\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `.foo, .bar\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break inside the block`,
			code: `.foo, .bar {\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar {\r\n}`,
		},
		{
			description: `a blank line inside the block`,
			code: `.foo, .bar {\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar {\r\n\r\n}`,
		},
		{
			description: `two blank lines inside the block`,
			code: `.foo, .bar {\n\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar {\r\n\r\n\r\n}`,
		},
		{
			description: `a line break behind the rule`,
			code: `.foo, .bar { }\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar { }\r\n`,
		},
		{
			description: `a blank line behind the rule`,
			code: `.foo, .bar { }\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar { }\r\n\r\n`,
		},
		{
			description: `two blank lines behind the rule`,
			code: `.foo, .bar { }\n\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar { }\r\n\r\n\r\n`,
		},
		{
			description: `a selector written on one line`,
			code: `.foo .bar { }`,
		},
		{
			description: `a line break inside the selector`,
			code: `.foo\n.bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar { }`,
		},
		{
			description: `a blank line inside the selector`,
			code: `.foo\n\n.bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar { }`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\n.foo .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo .bar { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\n.foo .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo .bar { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\n.foo .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo .bar { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `.foo .bar\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `.foo .bar\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `.foo .bar\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break inside the block`,
			code: `.foo .bar {\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar {\r\n}`,
		},
		{
			description: `a blank line inside the block`,
			code: `.foo .bar {\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar {\r\n\r\n}`,
		},
		{
			description: `two blank lines inside the block`,
			code: `.foo .bar {\n\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar {\r\n\r\n\r\n}`,
		},
		{
			description: `a line break behind the rule`,
			code: `.foo .bar { }\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar { }\r\n`,
		},
		{
			description: `a blank line behind the rule`,
			code: `.foo .bar { }\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar { }\r\n\r\n`,
		},
		{
			description: `two blank lines behind the rule`,
			code: `.foo .bar { }\n\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar { }\r\n\r\n\r\n`,
		},
		{
			description: `a selector written on one line`,
			code: `.foo > .bar { }`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\n.foo > .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo > .bar { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\n.foo > .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo > .bar { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\n.foo > .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo > .bar { }`,
		},
		{
			description: `a line break in front of the first combinator`,
			code: `.foo\n> .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n> .bar { }`,
		},
		{
			description: `a blank line in front of the first combinator`,
			code: `.foo\n\n> .bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n> .bar { }`,
		},
		{
			description: `a line break after the first combinator`,
			code: `.foo >\n.bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo >\r\n.bar { }`,
		},
		{
			description: `a blank line after the first combinator`,
			code: `.foo >\n\n.bar { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo >\r\n\r\n.bar { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `.foo > .bar\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `.foo > .bar\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `.foo > .bar\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break inside the block`,
			code: `.foo > .bar {\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar {\r\n}`,
		},
		{
			description: `a blank line inside the block`,
			code: `.foo > .bar {\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar {\r\n\r\n}`,
		},
		{
			description: `two blank lines inside the block`,
			code: `.foo > .bar {\n\n\n}`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar {\r\n\r\n\r\n}`,
		},
		{
			description: `a line break behind the rule`,
			code: `.foo > .bar { }\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar { }\r\n`,
		},
		{
			description: `a blank line behind the rule`,
			code: `.foo > .bar { }\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar { }\r\n\r\n`,
		},
		{
			description: `two blank lines behind the rule`,
			code: `.foo > .bar { }\n\n\n`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo > .bar { }\r\n\r\n\r\n`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\na[itemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\na[itemprop=url] { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\na[itemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\na[itemprop=url] { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\na[itemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\na[itemprop=url] { }`,
		},
		{
			description: `a line break inside the selector`,
			code: `a\n[itemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n[itemprop=url] { }`,
		},
		{
			description: `a blank line inside the selector`,
			code: `a\n\n[itemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n\r\n[itemprop=url] { }`,
		},
		{
			description: `a line break after the opening bracket of the attribute selector`,
			code: `a[\nitemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[\r\nitemprop=url] { }`,
		},
		{
			description: `a blank line after the opening bracket of the attribute selector`,
			code: `a[\n\nitemprop=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[\r\n\r\nitemprop=url] { }`,
		},
		{
			description: `a line break in front of the operator of the attribute selector`,
			code: `a[itemprop\n=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop\r\n=url] { }`,
		},
		{
			description: `a blank line in front of the operator of the attribute selector`,
			code: `a[itemprop\n\n=url] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop\r\n\r\n=url] { }`,
		},
		{
			description: `a line break after the operator of the attribute selector`,
			code: `a[itemprop=\nurl] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=\r\nurl] { }`,
		},
		{
			description: `a blank line after the operator of the attribute selector`,
			code: `a[itemprop=\n\nurl] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=\r\n\r\nurl] { }`,
		},
		{
			description: `a line break in front of the closing bracket of the attribute selector`,
			code: `a[itemprop=url\n] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url\r\n] { }`,
		},
		{
			description: `a blank line in front of the closing bracket of the attribute selector`,
			code: `a[itemprop=url\n\n] { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url\r\n\r\n] { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `a[itemprop=url]\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url]\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `a[itemprop=url]\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url]\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `a[itemprop=url]\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url]\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\na:hover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\na:hover { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\na:hover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\na:hover { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\na:hover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\na:hover { }`,
		},
		{
			description: `a line break in front of the pseudo-class`,
			code: `a\n:hover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n:hover { }`,
		},
		{
			description: `a blank line in front of the pseudo-class`,
			code: `a\n\n:hover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n\r\n:hover { }`,
		},
		{
			description: `a line break after the colon of the pseudo-class`,
			code: `a:\nhover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:\r\nhover { }`,
		},
		{
			description: `a blank line after the colon of the pseudo-class`,
			code: `a:\n\nhover { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:\r\n\r\nhover { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `a:hover\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:hover\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `a:hover\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:hover\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `a:hover\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:hover\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break in front of the selector`,
			code: `\na::before { }`,
		},
		{
			description: `a line break in front of the selector, written with carriage-return line breaks`,
			code: `\r\na::before  { }`,
		},
		{
			description: `a blank line in front of the selector`,
			code: `\n\na::before { }`,
		},
		{
			description: `a blank line in front of the selector, written with carriage-return line breaks`,
			code: `\r\n\r\na::before  { }`,
		},
		{
			description: `two blank lines in front of the selector`,
			code: `\n\n\na::before { }`,
		},
		{
			description: `two blank lines in front of the selector, written with carriage-return line breaks`,
			code: `\r\n\r\n\r\na::before  { }`,
		},
		{
			description: `a line break in front of the pseudo-element`,
			code: `a\n::before  { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n::before  { }`,
		},
		{
			description: `a blank line in front of the pseudo-element`,
			code: `a\n\n::before  { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n\r\n::before  { }`,
		},
		{
			description: `a line break after the colons of the pseudo-element`,
			code: `a::\nbefore { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a::\r\nbefore { }`,
		},
		{
			description: `a blank line after the colons of the pseudo-element`,
			code: `a::\n\nbefore { }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a::\r\n\r\nbefore { }`,
		},
		{
			description: `a line break between the selector and the opening brace`,
			code: `a::before\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a::before\r\n{ }`,
		},
		{
			description: `a blank line between the selector and the opening brace`,
			code: `a::before\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a::before\r\n\r\n{ }`,
		},
		{
			description: `two blank lines between the selector and the opening brace`,
			code: `a::before\n\n\n{ }`,
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a::before\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break in front of the selector and a line break behind a comment inside the selector`,
			code: `\n/*comment*/\n.foo { }`,
		},
		{
			description: `a blank line in front of the selector and a blank line behind a comment inside the selector`,
			code: `\n\n/*comment*/\n\n.foo { }`,
		},
		{
			description: `two blank lines in front of the selector and two blank lines behind a comment inside the selector`,
			code: `\n\n\n/*comment*/\n\n\n.foo { }`,
		},
		{
			description: `a line break in front of the selector and a line break behind a comment inside the selector, written with carriage-return line breaks`,
			code: `\r\n/*comment*/\r\n.foo { }`,
		},
		{
			description: `a blank line in front of the selector and a blank line behind a comment inside the selector, written with carriage-return line breaks`,
			code: `\r\n\r\n/*comment*/\r\n\r\n.foo { }`,
		},
		{
			description: `two blank lines in front of the selector and two blank lines behind a comment inside the selector, written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n/*comment*/\r\n\r\n\r\n.foo { }`,
		},
		{
			description: `a line break in front of a comment inside the selector and a line break between the selector and the opening brace`,
			code: `.foo\n/*comment*/\n{ }`,
		},
		{
			description: `a blank line in front of a comment inside the selector and a blank line between the selector and the opening brace`,
			code: `.foo\n\n/*comment*/\n\n{ }`,
		},
		{
			description: `two blank lines in front of a comment inside the selector and two blank lines between the selector and the opening brace`,
			code: `.foo\n\n\n/*comment*/\n\n\n{ }`,
		},
		{
			description: `a line break in front of a comment inside the selector and a line break between the selector and the opening brace, written with carriage-return line breaks`,
			code: `.foo\r\n/*comment*/\r\n{ }`,
		},
		{
			description: `a blank line in front of a comment inside the selector and a blank line between the selector and the opening brace, written with carriage-return line breaks`,
			code: `.foo\r\n\r\n/*comment*/\r\n\r\n{ }`,
		},
		{
			description: `two blank lines in front of a comment inside the selector and two blank lines between the selector and the opening brace, written with carriage-return line breaks`,
			code: `.foo\r\n\r\n\r\n/*comment*/\r\n\r\n\r\n{ }`,
		},
		{
			description: `a line break in front of a comment inside the selector and a line break behind a comment inside the selector`,
			code: `.foo\n/*comment*/\n.bar{ }`,
		},
		{
			description: `a blank line in front of a comment inside the selector and a blank line behind a comment inside the selector`,
			code: `.foo\n\n/*comment*/\n\n.bar{ }`,
		},
		{
			description: `a line break in front of a comment inside the selector and a line break behind a comment inside the selector, written with carriage-return line breaks`,
			code: `.foo\r\n/*comment*/\r\n.bar{ }`,
		},
		{
			description: `a blank line in front of a comment inside the selector and a blank line behind a comment inside the selector, written with carriage-return line breaks`,
			code: `.foo\r\n\r\n/*comment*/\r\n\r\n.bar{ }`,
		},
	],

	reject: [
		{
			description: `two blank lines inside the selector`,
			code: `.foo\n\n\n.bar { }`,
			fixed: `.foo\n\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n\r\n.bar { }`,
			fixed: `.foo\r\n\r\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines after the first comma`,
			code: `.foo,\n\n\n.bar { }`,
			fixed: `.foo,\n\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n\r\n\r\n.bar { }`,
			fixed: `.foo,\r\n\r\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines after the second comma`,
			code: `.foo, .bar,\n\n\n.other { }`,
			fixed: `.foo, .bar,\n\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo, .bar,\r\n\r\n\r\n.other { }`,
			fixed: `.foo, .bar,\r\n\r\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a line break after the first comma and two blank lines after the second comma`,
			code: `.foo,\n.bar,\n\n\n.other { }`,
			fixed: `.foo,\n.bar,\n\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n.bar,\r\n\r\n\r\n.other { }`,
			fixed: `.foo,\r\n.bar,\r\n\r\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line after the first comma and two blank lines after the second comma`,
			code: `.foo,\n\n.bar,\n\n\n.other { }`,
			fixed: `.foo,\n\n.bar,\n\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n\r\n.bar,\r\n\r\n\r\n.other { }`,
			fixed: `.foo,\r\n\r\n.bar,\r\n\r\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a line break after the first comma, two blank lines after the second comma and a line break between the selector and the opening brace`,
			code: `.foo,\n.bar,\n\n\n.other\n{ }`,
			fixed: `.foo,\n.bar,\n\n.other\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n.bar,\r\n\r\n\r\n.other\r\n{ }`,
			fixed: `.foo,\r\n.bar,\r\n\r\n.other\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line after the first comma, two blank lines after the second comma and a line break between the selector and the opening brace`,
			code: `.foo,\n\n.bar,\n\n\n.other\n{ }`,
			fixed: `.foo,\n\n.bar,\n\n.other\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n\r\n.bar,\r\n\r\n\r\n.other\r\n{ }`,
			fixed: `.foo,\r\n\r\n.bar,\r\n\r\n.other\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a line break after the first comma, two blank lines after the second comma and a blank line between the selector and the opening brace`,
			code: `.foo,\n.bar,\n\n\n.other\n\n{ }`,
			fixed: `.foo,\n.bar,\n\n.other\n\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n.bar,\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `.foo,\r\n.bar,\r\n\r\n.other\r\n\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line after the first comma, two blank lines after the second comma and two blank lines between the selector and the opening brace`,
			code: `.foo,\n\n.bar,\n\n\n.other\n\n\n{ }`,
			fixed: `.foo,\n\n.bar,\n\n.other\n\n\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo,\r\n\r\n.bar,\r\n\r\n\r\n.other\r\n\r\n\r\n{ }`,
			fixed: `.foo,\r\n\r\n.bar,\r\n\r\n.other\r\n\r\n\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a line break in front of the selector, a line break after the first comma, two blank lines after the second comma and a blank line between the selector and the opening brace`,
			code: `\n.foo,\n.bar,\n\n\n.other\n\n{ }`,
			fixed: `\n.foo,\n.bar,\n\n.other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo,\r\n.bar,\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n.foo,\r\n.bar,\r\n\r\n.other\r\n\r\n{ }`,
			line: 2,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line in front of the selector, a blank line after the first comma, two blank lines after the second comma and two blank lines between the selector and the opening brace`,
			code: `\n\n.foo,\n\n.bar,\n\n\n.other\n\n\n{ }`,
			fixed: `\n\n.foo,\n\n.bar,\n\n.other\n\n\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo,\r\n\r\n.bar,\r\n\r\n\r\n.other\r\n\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo,\r\n\r\n.bar,\r\n\r\n.other\r\n\r\n\r\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line in front of the selector, a line break after the first comma, two blank lines after the second comma and a blank line between the selector and the opening brace`,
			code: `\n\n.foo,\n.bar,\n\n\n.other\n\n{ }`,
			fixed: `\n\n.foo,\n.bar,\n\n.other\n\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo,\r\n.bar,\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo,\r\n.bar,\r\n\r\n.other\r\n\r\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the selector, a blank line after the first comma, two blank lines after the second comma and two blank lines between the selector and the opening brace`,
			code: `\n\n\n.foo,\n\n.bar,\n\n\n.other\n\n\n{ }`,
			fixed: `\n\n\n.foo,\n\n.bar,\n\n.other\n\n\n{ }`,
			line: 4,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo,\r\n\r\n.bar,\r\n\r\n\r\n.other\r\n\r\n\r\n{ }`,
			fixed: `\r\n\r\n\r\n.foo,\r\n\r\n.bar,\r\n\r\n.other\r\n\r\n\r\n{ }`,
			line: 4,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines inside the selector`,
			code: `.foo .bar\n\n\n.other { }`,
			fixed: `.foo .bar\n\n.other { }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar\r\n\r\n\r\n.other { }`,
			fixed: `.foo .bar\r\n\r\n.other { }`,
			message: messages.expected(1),
		},
		{
			description: `a line break inside the selector and two blank lines further along it`,
			code: `.foo\n.bar\n\n\n.other { }`,
			fixed: `.foo\n.bar\n\n.other { }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n\r\n.other { }`,
			fixed: `.foo\r\n.bar\r\n\r\n.other { }`,
			message: messages.expected(1),
		},
		{
			description: `a blank line inside the selector and two blank lines further along it`,
			code: `.foo\n\n.bar\n\n\n.other { }`,
			fixed: `.foo\n\n.bar\n\n.other { }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar\r\n\r\n\r\n.other { }`,
			fixed: `.foo\r\n\r\n.bar\r\n\r\n.other { }`,
			message: messages.expected(1),
		},
		{
			description: `a line break inside the selector, two blank lines further along it and a line break between the selector and the opening brace`,
			code: `.foo\n.bar\n\n\n.other\n{ }`,
			fixed: `.foo\n.bar\n\n.other\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n\r\n.other\r\n{ }`,
			fixed: `.foo\r\n.bar\r\n\r\n.other\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a blank line inside the selector, two blank lines further along it and a blank line between the selector and the opening brace`,
			code: `.foo\n\n.bar\n\n\n.other\n\n{ }`,
			fixed: `.foo\n\n.bar\n\n.other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `.foo\r\n\r\n.bar\r\n\r\n.other\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a line break inside the selector, two blank lines further along it and a blank line between the selector and the opening brace`,
			code: `.foo\n.bar\n\n\n.other\n\n{ }`,
			fixed: `.foo\n.bar\n\n.other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `.foo\r\n.bar\r\n\r\n.other\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a blank line inside the selector, two blank lines further along it and two blank lines between the selector and the opening brace`,
			code: `.foo\n\n.bar\n\n\n.other\n\n\n{ }`,
			fixed: `.foo\n\n.bar\n\n.other\n\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar\r\n\r\n\r\n.other\r\n\r\n\r\n{ }`,
			fixed: `.foo\r\n\r\n.bar\r\n\r\n.other\r\n\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a line break in front of the selector, a line break inside the selector, two blank lines further along it and a blank line between the selector and the opening brace`,
			code: `\n.foo\n.bar\n\n\n.other\n\n{ }`,
			fixed: `\n.foo\n.bar\n\n.other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo\r\n.bar\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n.foo\r\n.bar\r\n\r\n.other\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a blank line in front of the selector, a blank line inside the selector, two blank lines further along it and two blank lines between the selector and the opening brace`,
			code: `\n\n.foo\n\n.bar\n\n\n.other\n\n\n{ }`,
			fixed: `\n\n.foo\n\n.bar\n\n.other\n\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo\r\n\r\n.bar\r\n\r\n\r\n.other\r\n\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo\r\n\r\n.bar\r\n\r\n.other\r\n\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a blank line in front of the selector, a line break inside the selector, two blank lines further along it and a blank line between the selector and the opening brace`,
			code: `\n\n.foo\n.bar\n\n\n.other\n\n{ }`,
			fixed: `\n\n.foo\n.bar\n\n.other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo\r\n.bar\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo\r\n.bar\r\n\r\n.other\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the selector, a blank line inside the selector, two blank lines further along it and two blank lines between the selector and the opening brace`,
			code: `\n\n\n.foo\n\n.bar\n\n\n.other\n\n\n{ }`,
			fixed: `\n\n\n.foo\n\n.bar\n\n.other\n\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo\r\n\r\n.bar\r\n\r\n\r\n.other\r\n\r\n\r\n{ }`,
			fixed: `\r\n\r\n\r\n.foo\r\n\r\n.bar\r\n\r\n.other\r\n\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `two blank lines after the first combinator`,
			code: `.foo >\n\n\n.bar { }`,
			fixed: `.foo >\n\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo >\r\n\r\n\r\n.bar { }`,
			fixed: `.foo >\r\n\r\n.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the first combinator`,
			code: `.foo\n\n\n>.bar { }`,
			fixed: `.foo\n\n>.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the first combinator, written with carriage-return line breaks`,
			code: `.foo\r\n\r\n\r\n> .bar { }`,
			fixed: `.foo\r\n\r\n> .bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines after the first combinator`,
			code: `.foo .bar >\n\n\n.other { }`,
			fixed: `.foo .bar >\n\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines after the first combinator, written with carriage-return line breaks`,
			code: `.foo .bar >\r\n\r\n\r\n .other { }`,
			fixed: `.foo .bar >\r\n\r\n .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the first combinator`,
			code: `.foo .bar\n\n\n> .other { }`,
			fixed: `.foo .bar\n\n> .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo .bar\r\n\r\n\r\n> .other { }`,
			fixed: `.foo .bar\r\n\r\n> .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a line break inside the selector and two blank lines after the first combinator`,
			code: `.foo\n.bar >\n\n\n.other { }`,
			fixed: `.foo\n.bar >\n\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar >\r\n\r\n\r\n.other { }`,
			fixed: `.foo\r\n.bar >\r\n\r\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line inside the selector and two blank lines after the first combinator`,
			code: `.foo\n\n.bar >\n\n\n.other { }`,
			fixed: `.foo\n\n.bar >\n\n.other { }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar >\r\n\r\n\r\n.other { }`,
			fixed: `.foo\r\n\r\n.bar >\r\n\r\n.other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a line break inside the selector and two blank lines in front of the first combinator`,
			code: `.foo\n.bar\n\n\n> .other { }`,
			fixed: `.foo\n.bar\n\n> .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n\r\n> .other { }`,
			fixed: `.foo\r\n.bar\r\n\r\n> .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line inside the selector and two blank lines in front of the first combinator`,
			code: `.foo\n\n.bar\n\n\n> .other { }`,
			fixed: `.foo\n\n.bar\n\n> .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar\r\n\r\n\r\n> .other { }`,
			fixed: `.foo\r\n\r\n.bar\r\n\r\n> .other { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a line break inside the selector, two blank lines after the first combinator and a line break between the selector and the opening brace`,
			code: `.foo\n.bar >\n\n\n.other\n{ }`,
			fixed: `.foo\n.bar >\n\n.other\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar >\r\n\r\n\r\n.other\r\n{ }`,
			fixed: `.foo\r\n.bar >\r\n\r\n.other\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line inside the selector, two blank lines after the first combinator and a blank line between the selector and the opening brace`,
			code: `.foo\n\n.bar >\n\n\n.other\n\n{ }`,
			fixed: `.foo\n\n.bar >\n\n.other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar >\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `.foo\r\n\r\n.bar >\r\n\r\n.other\r\n\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a line break inside the selector, two blank lines in front of the first combinator and a line break between the selector and the opening brace`,
			code: `.foo\n.bar\n\n\n> .other\n{ }`,
			fixed: `.foo\n.bar\n\n> .other\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a line break inside the selector, two blank lines in front of the first combinator and a line break between the selector and the opening brace, written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n\r\n > .other\r\n{ }`,
			fixed: `.foo\r\n.bar\r\n\r\n > .other\r\n{ }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line inside the selector, two blank lines in front of the first combinator and a blank line between the selector and the opening brace`,
			code: `.foo\n\n.bar\n\n\n> .other\n\n{ }`,
			fixed: `.foo\n\n.bar\n\n> .other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a blank line inside the selector, two blank lines in front of the first combinator and a blank line between the selector and the opening brace, written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar\r\n\r\n\r\n > .other\r\n\r\n{ }`,
			fixed: `.foo\r\n\r\n.bar\r\n\r\n > .other\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a line break inside the selector, two blank lines after the first combinator and a blank line between the selector and the opening brace`,
			code: `.foo\n.bar >\n\n\n.other\n\n{ }`,
			fixed: `.foo\n.bar >\n\n.other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar >\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `.foo\r\n.bar >\r\n\r\n.other\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a blank line inside the selector, two blank lines after the first combinator and two blank lines between the selector and the opening brace`,
			code: `.foo\n\n.bar >\n\n\n.other\n\n\n{ }`,
			fixed: `.foo\n\n.bar >\n\n.other\n\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar >\r\n\r\n\r\n.other\r\n\r\n\r\n{ }`,
			fixed: `.foo\r\n\r\n.bar >\r\n\r\n.other\r\n\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a line break inside the selector, two blank lines in front of the first combinator and a blank line between the selector and the opening brace`,
			code: `.foo\n.bar\n\n\n> .other\n\n{ }`,
			fixed: `.foo\n.bar\n\n> .other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n.bar\r\n\r\n\r\n> .other\r\n\r\n{ }`,
			fixed: `.foo\r\n.bar\r\n\r\n> .other\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a blank line inside the selector, two blank lines in front of the first combinator and two blank lines between the selector and the opening brace`,
			code: `.foo\n\n.bar\n\n\n> .other\n\n\n{ }`,
			fixed: `.foo\n\n.bar\n\n> .other\n\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n.bar\r\n\r\n\r\n> .other\r\n\r\n\r\n{ }`,
			fixed: `.foo\r\n\r\n.bar\r\n\r\n> .other\r\n\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `a line break in front of the selector, a line break inside the selector, two blank lines after the first combinator and a blank line between the selector and the opening brace`,
			code: `\n.foo\n.bar >\n\n\n.other\n\n{ }`,
			fixed: `\n.foo\n.bar >\n\n.other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo\r\n.bar >\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n.foo\r\n.bar >\r\n\r\n.other\r\n\r\n{ }`,
			line: 2,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line in front of the selector, a blank line inside the selector, two blank lines after the first combinator and two blank lines between the selector and the opening brace`,
			code: `\n\n.foo\n\n.bar >\n\n\n.other\n\n\n{ }`,
			fixed: `\n\n.foo\n\n.bar >\n\n.other\n\n\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo\r\n\r\n.bar >\r\n\r\n\r\n.other\r\n\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo\r\n\r\n.bar >\r\n\r\n.other\r\n\r\n\r\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a line break in front of the selector, a line break inside the selector, two blank lines in front of the first combinator and a blank line between the selector and the opening brace`,
			code: `\n.foo\n.bar\n\n\n> .other\n\n{ }`,
			fixed: `\n.foo\n.bar\n\n> .other\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n.foo\r\n.bar\r\n\r\n\r\n> .other\r\n\r\n{ }`,
			fixed: `\r\n.foo\r\n.bar\r\n\r\n> .other\r\n\r\n{ }`,
			line: 2,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line in front of the selector, a blank line inside the selector, two blank lines in front of the first combinator and two blank lines between the selector and the opening brace`,
			code: `\n\n.foo\n\n.bar\n\n\n> .other\n\n\n{ }`,
			fixed: `\n\n.foo\n\n.bar\n\n> .other\n\n\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo\r\n\r\n.bar\r\n\r\n\r\n> .other\r\n\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo\r\n\r\n.bar\r\n\r\n> .other\r\n\r\n\r\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line in front of the selector, a line break inside the selector, two blank lines after the first combinator and a blank line between the selector and the opening brace`,
			code: `\n\n.foo\n.bar >\n\n\n.other\n\n{ }`,
			fixed: `\n\n.foo\n.bar >\n\n.other\n\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n.foo\r\n.bar >\r\n\r\n\r\n.other\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo\r\n.bar >\r\n\r\n.other\r\n\r\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the selector, a blank line inside the selector, two blank lines after the first combinator and two blank lines between the selector and the opening brace`,
			code: `\n\n\n.foo\n\n.bar >\n\n\n.other\n\n\n{ }`,
			fixed: `\n\n\n.foo\n\n.bar >\n\n.other\n\n\n{ }`,
			line: 4,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo\r\n\r\n.bar >\r\n\r\n\r\n.other\r\n\r\n\r\n{ }`,
			fixed: `\r\n\r\n\r\n.foo\r\n\r\n.bar >\r\n\r\n.other\r\n\r\n\r\n{ }`,
			line: 4,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line in front of the selector, a line break inside the selector, two blank lines in front of the first combinator and a blank line between the selector and the opening brace`,
			code: `\n\n.foo\n.bar\n\n\n >.other\n\n{ }`,
			fixed: `\n\n.foo\n.bar\n\n >.other\n\n{ }`,
			line: 3,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `a blank line in front of the selector, a line break inside the selector, two blank lines in front of the first combinator and a blank line between the selector and the opening brace, written with carriage-return line breaks`,
			code: `\r\n\r\n.foo\r\n.bar\r\n\r\n\r\n> .other\r\n\r\n{ }`,
			fixed: `\r\n\r\n.foo\r\n.bar\r\n\r\n> .other\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the selector, a blank line inside the selector, two blank lines in front of the first combinator and two blank lines between the selector and the opening brace`,
			code: `\n\n\n.foo\n\n.bar\n\n\n >.other\n\n\n{ }`,
			fixed: `\n\n\n.foo\n\n.bar\n\n >.other\n\n\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the selector, a blank line inside the selector, two blank lines in front of the first combinator and two blank lines between the selector and the opening brace, written with carriage-return line breaks`,
			code: `\r\n\r\n\r\n.foo\r\n\r\n.bar\r\n\r\n\r\n> .other\r\n\r\n\r\n{ }`,
			fixed: `\r\n\r\n\r\n.foo\r\n\r\n.bar\r\n\r\n> .other\r\n\r\n\r\n{ }`,
			message: messages.expected(1),
		},
		{
			description: `two blank lines after the opening bracket of the attribute selector`,
			code: `a[\n\n\nitemprop=url] { }`,
			fixed: `a[\n\nitemprop=url] { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[\r\n\r\n\r\nitemprop=url] { }`,
			fixed: `a[\r\n\r\nitemprop=url] { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the operator of the attribute selector`,
			code: `a[itemprop\n\n\n=url] { }`,
			fixed: `a[itemprop\n\n=url] { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop\r\n\r\n\r\n=url] { }`,
			fixed: `a[itemprop\r\n\r\n=url] { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines after the operator of the attribute selector`,
			code: `a[itemprop=\n\n\nurl] { }`,
			fixed: `a[itemprop=\n\nurl] { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=\r\n\r\n\r\nurl] { }`,
			fixed: `a[itemprop=\r\n\r\nurl] { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the closing bracket of the attribute selector`,
			code: `a[itemprop=url\n\n\n] { }`,
			fixed: `a[itemprop=url\n\n] { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a[itemprop=url\r\n\r\n\r\n] { }`,
			fixed: `a[itemprop=url\r\n\r\n] { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the pseudo-class`,
			code: `a\n\n\n:hover { }`,
			fixed: `a\n\n:hover { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n\r\n\r\n:hover { }`,
			fixed: `a\r\n\r\n:hover { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines after the colon of the pseudo-class`,
			code: `a:\n\n\nhover { }`,
			fixed: `a:\n\nhover { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a:\r\n\r\n\r\nhover { }`,
			fixed: `a:\r\n\r\nhover { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of the pseudo-element`,
			code: `a\n\n\n::before { }`,
			fixed: `a\n\n::before { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a\r\n\r\n\r\n::before { }`,
			fixed: `a\r\n\r\n::before { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines after the colons of the pseudo-element`,
			code: `a::\n\n\nbefore { }`,
			fixed: `a::\n\nbefore { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `a::\r\n\r\n\r\nbefore { }`,
			fixed: `a::\r\n\r\nbefore { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `two blank lines in front of a comment inside the selector`,
			code: `.foo\n\n\n/*comment*/.bar { }`,
			fixed: `.foo\n\n/*comment*/.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
		{
			description: `the same fixture written with carriage-return line breaks`,
			code: `.foo\r\n\r\n\r\n/*comment*/.bar { }`,
			fixed: `.foo\r\n\r\n/*comment*/.bar { }`,
			line: 1,
			column: 1,
			message: messages.expected(1),
		},
	],
})
