name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'

env:
  FORCE_COLOR: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          cache: true
          version: latest
      - run: pnpm ci
      - run: pnpm lint
      - run: pnpm test --reporter=github-actions --reporter=default
